/* ============================================================
   BPHS · Telugu — verse data
   Loaded by app.html (Expert mode shows the BPHS reference panel)
   Source: brihat-parasara-hora-sastra-telugu.pdf (Sanskrit verses
   in Telugu script transliteration). Telugu bhāva (meaning) added
   as a working translation; user-verified verses are gold-standard.
   ============================================================ */
window.BPHS_VERSES = {
  meta: {
    source: "Brihat Parashara Hora Shastra · Telugu transliteration",
    source_pdf: "brihat-parasara-hora-sastra-telugu.pdf",
    total_chapters_in_pdf: 97,
    total_pages_in_pdf: 160,
    extracted_chapters: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    note: "PDF contains Sanskrit verses transliterated into Telugu script. Telugu bhāva (meaning) added by Claude as a working translation. Each verse carries a 'verified' status — user-verified verses are gold-standard for citation in client readings."
  },
  chapters: {
    1: {
      title_te: "సృష్టిక్రమకథనాధ్యాయః",
      title_en: "Chapter on the Sequence of Creation (Maitreya's Question)",
      summary_te: "మహర్షి మైత్రేయుడు పరాశరమునిని సమీపించి జ్యోతిష్య శాస్త్రమును, సృష్టి-లయ క్రమమును, ఖగోళ-భూమిల సంబంధమును బోధించమని ప్రార్థించును. పరాశరుడు సూర్యునికి నమస్కరించి బ్రహ్మముఖము నుండి విన్న దానిని వివరించుట ప్రారంభించును. విష్ణువే అవ్యక్త-వ్యక్త రూపుడు, సకల సృష్టికర్త; శ్రీ-భూ-నీలాది శక్తులతో సహా జగత్తును పాలించు పరమాత్మ. సాత్త్విక-రాజస-తామస త్రిగుణములు, వ్యక్త-అవ్యక్త రూపములు, సంకర్షణ-ప్రద్యుమ్న-అనిరుద్ధ చతుర్వ్యూహములు వివరించబడెను.",
      verses: [
        {sl:1,page:2,sanskrit:"అథైకదా మునిశ్రేష్ఠం త్రికాలజ్ఞం పరాశరమ్‌ । పప్రచ్ఛేపేత్య మైత్రేయః ప్రణిపత్య కృతాంజలిః ॥ 1 ॥",telugu_bhava:"ఒకసారి, త్రికాలజ్ఞానము గల మునిశ్రేష్ఠుడైన పరాశర మహర్షిని సమీపించి, మైత్రేయ మహర్షి భక్తితో నమస్కరించి, చేతులు జోడించి (కృతాంజలి) ఇట్లు ప్రశ్నించెను.",english:"Once, having approached Parāśara — foremost of munis, knower of the three times — Maitreya, with folded hands and prostration, asked.",tags:["opening","maitreya","parashara"],verified:"auto"},
        {sl:2,page:2,sanskrit:"భగవన్‌ పరమం పుణ్యం గుహ్యం వేదాధికోత్తమమ్‌ । త్రిస్కన్ధం జ్యోతిషం హోరా గణితం సంహితేతి చ ॥ 2 ॥",telugu_bhava:"ఓ భగవన్‌! వేదముల కంటెను అత్యంత ఉత్తమమైన, పరమ పవిత్రమైన, రహస్యమైన, మూడు స్కంధములు (శాఖలు) గల జ్యోతిష్య శాస్త్రము — హోరా (జాతక), గణిత (సిద్ధాంత), సంహిత అను మూడు భాగములతో ఉండునది.",english:"O Bhagavan! Teach me jyotiṣa — supremely meritorious, secret, more excellent than the Vedas — having three skandhas: Hōrā (jātaka), Gaṇita (siddhānta), and Saṁhitā.",tags:["jyotisha","three-skandhas"],verified:"auto"},
        {sl:3,page:2,sanskrit:"ఏతేష్వపి త్రిషు శ్రేష్ఠా హోరేతి శ్రూయతే మునే । త్వత్తస్తాం శ్రోతుమిచ్ఛామి కృపయా వద మే ప్రభో ॥ 3 ॥",telugu_bhava:"ఓ మునీంద్రా! ఈ మూడింటిలో \"హోరా\" అను శాఖయే శ్రేష్ఠమని వినబడుచున్నది. దానిని మీ ద్వారా వినగోరుచున్నాను. దయతో నాకు చెప్పుడు, ఓ ప్రభో!",english:"Of these three, Hōrā is heard to be the foremost, O sage. I wish to hear of it from you — pray tell me, my lord.",tags:["hōrā","supremacy"],verified:"auto"},
        {sl:4,page:2,sanskrit:"కథం సృష్టిరియం జాతా జగతశ్చ లయః కథమ్‌ । ఖస్థానాం భూస్థానాం చ సమ్బన్ధం వద విస్తరాత్‌ ॥ 4 ॥",telugu_bhava:"ఈ సృష్టి ఎట్లు ఉద్భవించెను? జగత్తు ఎట్లు లయమగును? ఆకాశమున ఉండు (గ్రహ-నక్షత్రాది) వస్తువులకు, భూమిపై ఉండు ప్రాణులకు మధ్య సంబంధము ఎట్టిది? — విస్తారముగా చెప్పుడు.",english:"How did this creation come into being? How does the world dissolve? Tell me in detail the relationship between heavenly bodies and earthly beings.",tags:["creation","dissolution","ākāśa-bhū-sambandha"],verified:"auto"},
        {sl:5,page:2,sanskrit:"సాధు పృష్టం త్వయా విప్ర లోకానుగ్రహకారిణా । అథాహం పరమం బ్రహ్మ తచ్ఛక్తిం భారతీం పునః ॥ 5 ॥",telugu_bhava:"[పరాశర:] ఓ విప్రా! లోకములకు అనుగ్రహము కలిగించునట్లు మీరు మంచి ప్రశ్న వేసితిరి. ఇపుడు పరమ బ్రహ్మను, ఆ బ్రహ్మ యొక్క శక్తి అయిన భారతిని (సరస్వతిని) మరల [స్మరించుచున్నాను].",english:"Well-asked, O brāhmaṇa, with concern for the welfare of the worlds. Now I salute the supreme Brahman and again His Śakti — Bhāratī (Sarasvatī).",tags:["parashara-reply","saraswati"],verified:"auto"},
        {sl:6,page:2,sanskrit:"సూర్యం నత్వా గ్రహపతిం జగదుత్పత్తికారణమ్‌ । వక్ష్యామి వేదనయనం యథా బ్రహ్మముఖాచ్ఛ్రుతమ్‌ ॥ 6 ॥",telugu_bhava:"గ్రహముల అధిపతి, జగత్తు యొక్క ఉత్పత్తికి కారణభూతుడు అయిన సూర్యునికి నమస్కరించి, వేదముల నేత్రము (వేదనయనము = జ్యోతిషము) ను — బ్రహ్మదేవుని ముఖము నుండి నేను విన్నట్లుగా — చెప్పెదను.",english:"Bowing to Sūrya — lord of planets and cause of the world's creation — I shall declare the 'eye of the Vedas' (jyotiṣa) as I heard it from Brahmā's mouth.",tags:["surya","veda-nayana","lineage"],verified:"auto"},
        {sl:7,page:2,sanskrit:"శిష్యాయ గురుభక్తాయ పరమాణ పరుష్యవాదినే । ఆస్తికాయ ప్రదాతవ్యం తతః శ్రేయో హ్యవాప్స్యతి ॥ 7 ॥",telugu_bhava:"గురుభక్తి కల, మృదువుగా (కఠినముగా కాక) మాట్లాడు, ఆస్తిక్యత గల శిష్యునికి మాత్రమే ఈ శాస్త్రము ప్రదానము చేయవలెను. అటువంటి శిష్యునికి ఇచ్చిన మీదట గురువునకు శ్రేయస్సు కలుగును.",english:"This [science] should be imparted only to a disciple devoted to the guru, gentle in speech, and a believer (āstika) — therefrom does benefit accrue.",tags:["eligibility","shishya-qualification"],verified:"auto"},
        {sl:8,page:2,sanskrit:"న దేయం పరశిష్యాయ నాస్తికాయ శఠాయ వా । దత్తే ప్రతిదినం దుఃఖం జాయతే నాత్ర సంశయః ॥ 8 ॥",telugu_bhava:"మరొకరి శిష్యునికి, నాస్తికునికి, శఠునికి (కపటస్వభావి) — ఈ శాస్త్రము ఎన్నడును ఇవ్వరాదు. ఇచ్చినచో గురువుకు ప్రతిదినము దుఃఖము కలుగును — ఇందులో సందేహము లేదు.",english:"It should not be given to another's disciple, nor to an atheist, nor to a deceitful person. If given, daily suffering arises for the giver — no doubt in this.",tags:["restriction","eligibility"],verified:"auto"},
        {sl:9,page:2,sanskrit:"ఏకోఽవ్యక్తాత్మకో విష్ణురనాదిః ప్రభురీశ్వరః । శుద్ధసత్త్వో జగత్స్వామీ నిర్గుణస్త్రిగుణాన్వితః ॥ 9 ॥",telugu_bhava:"విష్ణువు ఒక్కడే — అవ్యక్తాత్మ స్వరూపుడు, అనాది (ఆది లేనివాడు), ప్రభువు, ఈశ్వరుడు, శుద్ధ సత్త్వ స్వరూపుడు, జగత్తునకు స్వామి. వస్తుతః నిర్గుణుడు అయినను త్రిగుణములతో (సత్త్వ-రజస్-తమో) కూడుకొని ఉండువాడు.",english:"Vishnu alone is — unmanifest in essence, beginningless, the Lord and Master, of pure sattva, ruler of the world; though Himself attribute-less (nirguṇa), He is endowed with the three guṇas.",tags:["vishnu","cosmology","trigunas"],verified:"auto"},
        {sl:10,page:2,sanskrit:"సంసారకారక శ్రీమాన్నిత్యాత్మా ప్రతాపవాన్‌ । ఏకాంశేన జగత్యత్ర స్వజత్యవతి లీలయా ॥ 10 ॥",telugu_bhava:"ఆ విష్ణువే సంసారమునకు కారణభూతుడు, శ్రీమంతుడు, నిత్యాత్మ, ప్రతాపవంతుడు. తన ఏకాంశ (ఒక చిన్న భాగము) చేతనే ఈ జగత్తును లీలగా సృష్టించుచు, పాలించుచు ఉండును.",english:"He is the cause of saṁsāra, possessed of Śrī, the eternal Self, the powerful one. By a single fragment of Himself He creates and sustains this world as mere līlā.",tags:["vishnu","creation","lila"],verified:"auto"},
        {sl:11,page:2,sanskrit:"త్రిపాదం తస్య దైవత్యం హ్యమృతం తత్త్వదర్శినః । విదన్తి తత్ప్రమాణం చ సప్రధానం తదైకికాపాత్‌ ॥ 11 ॥",telugu_bhava:"తత్త్వదర్శులు — ఆ విష్ణువు యొక్క మూడు పాదములను, దివ్య, అమృతస్వరూపమును, దాని ప్రమాణమును, ప్రధానముతో కూడిన ఆ ఏకాంశమును — తెలిసికొనుచున్నారు.",english:"The three pādas of His divinity are immortal — the seers of truth perceive its measure and the prominence of that single fragment.",tags:["vishnu","tripada","amrita"],verified:"auto"},
        {sl:12,page:2,sanskrit:"వ్యక్తావ్యక్తాత్మకో విష్ణుర్వాసుదేవస్తు గీయతే । యదవ్యక్తాత్మకో విష్ణుః శక్తిద్వయసమన్వితః ॥ 12 ॥",telugu_bhava:"వ్యక్త-అవ్యక్త రూపుడైన ఆ విష్ణువే వాసుదేవుడని కొనియాడబడును. అవ్యక్త రూపుడైన విష్ణువు రెండు శక్తులతో (శ్రీ-భూ) కూడుకొని ఉండును.",english:"Vishnu, of both manifest and unmanifest nature, is sung as Vāsudeva. As Unmanifest, He is endowed with two śaktis.",tags:["vasudeva","shakti","vyakta-avyakta"],verified:"auto"},
        {sl:13,page:2,sanskrit:"వ్యక్తాత్మకం స్త్రీభిరుక్తః కథ్యతే జనశక్తిమాన్‌ । సత్త్వప్రధానా శ్రీశక్తిర్భూశక్తిశ్చ రజోగుణా ॥ 13 ॥",telugu_bhava:"వ్యక్తరూపుడై స్త్రీలతో కూడినవాడు జనశక్తిమంతుడని చెప్పబడును. శ్రీశక్తి సత్త్వగుణ ప్రధానము; భూశక్తి రజోగుణ స్వరూపము.",english:"In the manifest form, He is called the Lord of beings. Śrī-śakti is sattva-predominant; Bhū-śakti is rajoguṇa.",tags:["sri","bhu","gunas"],verified:"auto"},
        {sl:14,page:2,sanskrit:"శక్తిస్తృతీయా యా ప్రోక్తా నీలాఖ్యా ధ్వాన్తరూపిణీ । వాసుదేవశ్చతుర్ధేఽభూచ్ఛక్త్యా ప్రీతో యదా ॥ 14 ॥",telugu_bhava:"మూడవ శక్తి — \"నీలా\" అని పిలువబడునది, తమోగుణ స్వరూపము (ధ్వాన్తరూపిణి = చీకటి రూపము). ఆ శక్తులతో ప్రీతుడై వాసుదేవుడు నాలుగు రూపములుగా (వ్యూహములుగా) అయ్యెను.",english:"The third śakti, called Nīlā, is of the form of darkness (tamoguṇa). Vāsudeva, pleased by these śaktis, became fourfold.",tags:["nila","vyuha","four-forms"],verified:"auto"},
        {sl:15,page:2,sanskrit:"సంకర్షణశ్చ ప్రద్యుమ్నః అనిరుద్ధ ఇతి మూర్తిధృక్‌ । తమశ్శక్త్యాన్వితో విష్ణురేవః సంకర్షణాభిధః ॥ 15 ॥",telugu_bhava:"సంకర్షణ, ప్రద్యుమ్న, అనిరుద్ధ — అను మూర్తులను ధరించెను. తమశ్శక్తి (నీలా) తో కూడిన విష్ణువే సంకర్షణుడు అని పిలువబడును.",english:"He bears the forms Saṁkarṣaṇa, Pradyumna, Aniruddha. Vishnu united with the tamas-śakti is called Saṁkarṣaṇa.",tags:["sankarshana","pradyumna","aniruddha","four-vyuhas"],verified:"auto"},
        {sl:16,page:2,sanskrit:"ప్రద్యుమ్నో రజసా శక్త్యాఽనిరుద్ధః సత్త్వయా యుతః । మహాన్‌ సంకర్షణాజ్జాతః ప్రద్యుమ్నాద్యదహంకృతిః ॥ 16 ॥",telugu_bhava:"ప్రద్యుమ్నుడు రజోశక్తితో, అనిరుద్ధుడు సత్త్వశక్తితో కూడినవాడు. సంకర్షణుని నుండి \"మహత్తత్త్వము\" జన్మించెను; ప్రద్యుమ్నుని నుండి \"అహంకారము\" జన్మించెను.",english:"Pradyumna is united with the rajas-śakti; Aniruddha with sattva. From Saṁkarṣaṇa came Mahat-tattva; from Pradyumna came Ahaṁkāra.",tags:["mahat","ahankara","cosmic-evolution"],verified:"auto"},
        {sl:17,page:2,sanskrit:"అనిరుద్ధాత్‌ స్వయం జాతో బ్రహ్మాహంకాకమూర్తిధృక్‌ । సర్వేషు సర్వశక్తిశ్చ స్వశక్త్యాఽధికయా యుతః ॥ 17 ॥",telugu_bhava:"అనిరుద్ధుని నుండి స్వయముగా బ్రహ్మదేవుడు ఉద్భవించెను — అహంకార మూర్తిని ధరించినవాడై. సర్వప్రాణులలో సర్వశక్తి స్వరూపుడై, తన శక్తి అధికముగా కూడినవాడై ఉండును.",english:"From Aniruddha, Brahmā Himself was born, bearing the form of ahaṁkāra. He is in all beings as all-power, endowed with His own greater śakti.",tags:["brahma","aniruddha","creator"],verified:"auto"},
        {sl:18,page:2,sanskrit:"అహంకారస్త్రిధా భూత్వా సర్వమేతద్విస్తరాత్‌ । సాత్త్వికో రాజసశ్చైవ తామసశ్చేదహంకృతిః ॥ 18 ॥",telugu_bhava:"అహంకారము మూడు రకములుగా (సాత్త్విక-రాజస-తామస) అయ్యి, ఈ సమస్త జగత్తును విస్తరింపజేయును.",english:"The Ahaṁkāra, having become threefold, extends into all this in detail — sāttvika, rājasa, and tāmasa are the three forms.",tags:["ahankara","trigunas"],verified:"auto"},
        {sl:19,page:2,sanskrit:"దేవా వైకారికాజ్జాతాస్తైజసాదీన్ద్రియాణి చ । తామసచ్చైవ భూతాని ఖాదీని స్వస్వశక్తిభిః ॥ 19 ॥",telugu_bhava:"దేవతలు సాత్త్విక (వైకారిక) అహంకారము నుండి, ఇంద్రియములు రాజస (తైజస) నుండి, పంచమహాభూతములు (ఆకాశాది) తామస నుండి — తమ తమ శక్తులతో జన్మించెను.",english:"The devas arose from the sāttvic (vaikārika), the indriyas from the rājasic (taijasa), and the great elements like ākāśa from the tāmasa — each by its own power.",tags:["devas","indriyas","bhutas","creation"],verified:"auto"},
        {sl:20,page:2,sanskrit:"శ్రీశక్త్యా సహితో విష్ణుః సదా పాతి జగత్త్రయమ్‌ । భూశక్త్యా సృజతే బ్రహ్మా నీలశక్త్యా శివోత్తి హి ॥ 20 ॥",telugu_bhava:"శ్రీశక్తితో సహా విష్ణువు ఎల్లప్పుడూ మూడు లోకములను పాలించుచుండును. భూశక్తితో బ్రహ్మ సృజించును; నీలశక్తితో శివుడు సంహరించును.",english:"With Śrī-śakti, Vishnu always protects the three worlds. With Bhū-śakti, Brahmā creates; with Nīlā-śakti, Śiva destroys.",tags:["trimurti","sri-bhu-nila","creation-preservation-dissolution"],verified:"auto"},
        {sl:21,page:2,sanskrit:"సర్వేషు చైవ జీవేషు పరమాత్మా విరాజతే । సర్వం హి తదిదం బ్రహ్మన్‌ స్థితం హి పరమాత్మని ॥ 21 ॥",telugu_bhava:"సకల జీవులలో పరమాత్మ ప్రకాశించుచుండును. ఓ బ్రహ్మన్‌! ఈ సమస్తము పరమాత్మ యందే స్థితమై ఉన్నది.",english:"In all beings the Paramātmā shines forth. All this, O Brāhmaṇa, is established in the Paramātmā alone.",tags:["paramatma","jiva","unity"],verified:"auto"},
        {sl:22,page:2,sanskrit:"సర్వేషు చైవ జీవేషు స్థితంహ్యంశద్వయం క్వచిత్‌ । జీవాంశో హ్యాధికస్తద్వత్‌ పరమాత్మాంశకః కిల ॥ 22 ॥",telugu_bhava:"సకల జీవులలోనూ రెండు అంశలు (జీవాంశ, పరమాత్మాంశ) ఏదో ఒక చోట ఉండును. కొన్నిటిలో జీవాంశ అధికము; కొన్నిటిలో పరమాత్మాంశ అధికమై ఉండును.",english:"In all beings, two parts coexist somewhere — in some the jīvāṁśa is greater, in others the Paramātmāṁśa is greater.",tags:["jiva-amsha","paramatma-amsha","duality"],verified:"auto"},
        {sl:23,page:2,sanskrit:"సూర్యాదయో గ్రహాః సర్వే బ్రహ్మకామద్యుపాదయః । ఏతే చాన్యే చ బాహవః పరమాత్మాంశకాధికాః ॥ 23 ॥",telugu_bhava:"సూర్యాది గ్రహములు అన్నీ, బ్రహ్మ-కామ-ఆది అధిదేవతలతో పాటు, మిగిలిన అనేక శక్తులూ — పరమాత్మ యొక్క అంశ అధికముగా కల్గినవి.",english:"The grahas beginning with Sūrya, along with Brahmā, Kāma and others, and many other beings — all have the Paramātmāṁśa predominant in them.",tags:["grahas","paramatma-amsha","divine-beings"],verified:"auto"},
        {sl:24,page:2,sanskrit:"శక్తయశ్చ తదైతేషమధికాః శ్రియాదయః । స్వస్వశక్తిషు చాన్యాను జ్ఞేయా జీవాంశకాధికాః ॥ 24 ॥",telugu_bhava:"వీరియొక్క శక్తులు — శ్రీ మొదలగునవి — అధికముగా ఉండును. తమ తమ శక్తులలో ఇతరులు జీవాంశ అధికముగా కల్గినవారని తెలిసికొనవలెను.",english:"Their śaktis (Śrī and others) are predominant in them. Others within their respective śaktis are to be known as having jīvāṁśa-predominance.",tags:["shaktis","jiva-amsha-predominance"],verified:"auto"}
      ]
    },
    2: {
      title_te: "అవతారకథనాధ్యాయః",
      title_en: "Chapter on the Description of Avatāras (Incarnations)",
      summary_te: "విష్ణు భగవానుని అవతారములను, ముఖ్యముగా 9 గ్రహములకు సంబంధించిన అవతారములను వివరించును. రామావతారము సూర్యునికి, కృష్ణావతారము చంద్రునికి, నృసింహావతారము కుజునికి, బుద్ధావతారము బుధునికి, వామనావతారము గురువునకు, పరశురామావతారము శుక్రునికి, కూర్మావతారము శనికి, వరాహావతారము రాహువునకు, మీనావతారము కేతువునకు సంబంధించినవి. జ్యోతిష్య శాస్త్రమును నిందించువారు రౌరవ నరకము పొందుదురని హెచ్చరిక.",
      verses: [
        {sl:1,page:3,sanskrit:"రామకృష్ణాదయో యే హ్యవతారా రమాపతేః । తేఽపి జీవాంశసంయుక్తాః కింవా బ్రూహి మునీశ్వర ॥ 1 ॥",telugu_bhava:"[మైత్రేయుడు:] ఓ మునీశ్వరా! రామ-కృష్ణాది అవతారములు రమాపతి (విష్ణువు) యొక్కవి. వారికి కూడా జీవాంశ ఉన్నదా? లేదా? — చెప్పుడు.",english:"O lord of munis! Are the avatāras of Ramāpati (Vishnu) like Rāma and Kr̥ṣṇa also endowed with jīvāṁśa? Tell me.",tags:["avatara","rama","krishna","question"],verified:"auto"},
        {sl:2,page:3,sanskrit:"రామః కృష్ణశ్చ హే విప్ర నృసింహః సూకరస్తథా । ఏతే పూర్ణావతారాశ్చ హ్యన్యే జీవాంశకాన్వితాః ॥ 2 ॥",telugu_bhava:"[పరాశర:] ఓ విప్రా! రాముడు, కృష్ణుడు, నృసింహుడు, సూకరుడు (వరాహము) — వీరు పూర్ణావతారములు; మిగిలిన అవతారములు జీవాంశతో కూడుకొన్నవి.",english:"O brāhmaṇa! Rāma, Kr̥ṣṇa, Nr̥siṁha, and Sūkara (Varāha) are pūrṇāvatāras (full incarnations); the rest are with jīvāṁśa.",tags:["purna-avatara","jiva-amsha"],verified:"auto"},
        {sl:3,page:3,sanskrit:"అవతారాణ్యనేకాని హ్యజస్య పరమాత్మనః । జీవానాం కర్మఫలదో గ్రహరూపీ జనార్దనః ॥ 3 ॥",telugu_bhava:"అజుడైన పరమాత్మ యొక్క అవతారములు అనేకములు. జీవులకు కర్మఫలమును ఇచ్చు జనార్దనుడే గ్రహరూపమున ఉండును.",english:"Many are the avatāras of the unborn Paramātmā. Janārdana, the giver of karma-fruits to jīvas, is in the form of grahas.",tags:["avataras-many","grahas-as-vishnu","karma-phala"],verified:"auto"},
        {sl:4,page:3,sanskrit:"దైత్యానాం బలనాశాయ దేవానాం బలబృద్ధయే । ధర్మసంస్థాపనార్థాయ గ్రహభూతః శుభః క్రమాత్‌ ॥ 4 ॥",telugu_bhava:"దైత్యుల (అసురుల) బలమును నశింపజేయుటకు, దేవతల బలమును పెంచుటకు, ధర్మ స్థాపన కొరకు — క్రమముగా ఈ గ్రహముల రూపమున శుభముగా అవతరించును.",english:"To destroy the strength of daityas, increase that of the devas, and establish dharma — He becomes the grahas in due sequence, auspiciously.",tags:["dharma-sthapana","daitya-vinasha","grahas"],verified:"auto"},
        {sl:5,page:3,sanskrit:"రామోఽవతారః సూర్యస్య చన్ద్రస్య యదునాయకః । నృసింహో భూమిపుత్రస్య బుద్ధః సోమసుతస్య చ ॥ 5 ॥",telugu_bhava:"రామావతారము సూర్యునిది; యదునాయకుడు (కృష్ణుడు) చంద్రునిది; నృసింహావతారము భూమిపుత్రుడు (కుజుడు) నది; బుద్ధావతారము సోమసుతుడు (బుధుడు) నది.",english:"The Rāma avatāra is of Sūrya; the Lord of the Yadus (Kr̥ṣṇa) of Candra; Nr̥siṁha of Bhūmi-putra (Maṅgala); Buddha of Soma-suta (Budha).",tags:["surya-rama","chandra-krishna","mars-narasimha","mercury-buddha"],verified:"auto"},
        {sl:6,page:3,sanskrit:"వామనే విబుధేజ్యస్య భార్గవే భార్గవస్య చ । కూర్మో భాస్కరపుత్రస్య సైంహికేయస్య సూకరః ॥ 6 ॥",telugu_bhava:"వామనావతారము విబుధేజ్యుడు (గురువు) నది; భార్గవావతారము (పరశురాముడు) భార్గవుడు (శుక్రుడు) నది; కూర్మావతారము భాస్కరపుత్రుడు (శని) నది; సూకరావతారము సైంహికేయుడు (రాహువు) నది.",english:"Vāmana of the lord of the wise (Br̥haspati); Bhārgava (Paraśurāma) of Bhārgava (Śukra); Kūrma of the Sun's son (Śani); Sūkara (Varāha) of Siṁhikā's son (Rāhu).",tags:["jupiter-vamana","venus-parashurama","saturn-kurma","rahu-varaha"],verified:"auto"},
        {sl:7,page:3,sanskrit:"కేతోర్మీనావతారశ్చ యే చాన్యే తేఽపి ఖేటజాః । పరాత్మాంశోఽధికో యేషు తే సర్వే ఖేచరాభిధాః ॥ 7 ॥",telugu_bhava:"కేతువునకు మీనావతారము; మిగిలిన అవతారములు కూడా గ్రహముల నుండి ఉద్భవించునవి. ఎవరిలో పరమాత్మాంశ అధికముగా ఉండునో — వారు \"ఖేచరులు\" (గ్రహ తుల్యులు) అని చెప్పబడుదురు.",english:"Of Ketu is the Mīna avatāra; others too come from grahas. Those in whom Paramātmāṁśa predominates are all called Khecaras (sky-movers).",tags:["ketu-matsya","khechara","paramatma-amsha"],verified:"auto"},
        {sl:8,page:3,sanskrit:"జీవాంశోఽహ్యధికో యేషు జీవాస్తే ప్రకీర్తితాః । సూర్యాదిభో గ్రహేభ్యశ్చ పరమాత్మాంశనిసృతాః ॥ 8 ॥",telugu_bhava:"ఎవరిలో జీవాంశ అధికముగా ఉండునో — వారు \"జీవులు\" (సాధారణ ప్రాణులు) అని చెప్పబడుదురు. సూర్యాది గ్రహముల నుండి పరమాత్మాంశ నిసృత (నిర్గమించినది) అయి ఉండును.",english:"Those in whom jīvāṁśa predominates are called jīvas. From the grahas Sūrya and others, the Paramātmāṁśa flows forth.",tags:["jiva","paramatma-amsha","grahas-source"],verified:"auto"},
        {sl:9,page:3,sanskrit:"రామకృష్ణాదయః సర్వే హ్యవతారా భవన్తి చై । తత్రైవ తే విలీయన్తే పునః కార్యోత్తర సదా ॥ 9 ॥",telugu_bhava:"రామ-కృష్ణాది అవతారములు అన్నీ గ్రహముల నుండియే ఉద్భవించి, తమ కార్యము ముగిసిన పిమ్మట మరల వాటిలోనే విలీనమగును.",english:"All the avatāras like Rāma and Kr̥ṣṇa arise from the grahas; once their work is done, they merge back into them.",tags:["avatara-cycle","layana","completion"],verified:"auto"},
        {sl:10,page:3,sanskrit:"జీవాంశకనిసృతాస్త్వేషాం తేభ్యో జాతా నరాదయః । తేఽపి తత్రైవ లీయన్తే తేషువ్యక్తే సమయన్తి హి ॥ 10 ॥",telugu_bhava:"గ్రహముల యొక్క జీవాంశ నుండి నరాది ప్రాణులు ఉద్భవించును. వారు కూడా చివరికి అదే గ్రహములలో విలీనమగుదురు. అవ్యక్త స్థితిలో సమయప్రకారము లీనమై ఉందురు.",english:"Humans and other beings arise from the grahas' jīvāṁśa. They too merge back into the grahas, dissolving at their proper time in the unmanifest.",tags:["humans","reabsorption","cycle"],verified:"auto"},
        {sl:11,page:3,sanskrit:"ఇదం తే కథితం విప్ర సర్వం యున్మానం భవేదిత । భూతాన్యపి భవిష్యన్తి తత్త్వజ్ఞానన్తి తద్విదః ॥ 11 ॥",telugu_bhava:"ఓ విప్రా! ఇది అంతయూ నీకు చెప్పబడెను — ఇది ప్రమాణముతో కూడినది. ప్రాణులు భవిష్యత్తులో కూడా ఉద్భవించును; తత్త్వజ్ఞులు ఈ తత్త్వమును తెలిసికొందురు.",english:"All this is told to you, O brāhmaṇa, with proper measure. Beings will also come into being in the future; the knowers of truth understand this principle.",tags:["confirmation","tattva-jnana"],verified:"auto"},
        {sl:12,page:3,sanskrit:"వినా తజ్జ్యోతిషం నాన్యే జ్ఞాతుం శక్నోతి కర్హిచిత్‌ । తస్మాదవశ్యమధ్యేయం బ్రాహ్మణేశ్చ విశేషతః ॥ 12 ॥",telugu_bhava:"ఆ జ్యోతిష్య శాస్త్రము లేకుండా ఎవరూ ఎన్నడూ ఈ తత్త్వమును తెలిసికొనజాలరు. కావున — ఈ శాస్త్రమును అవశ్యముగా అధ్యయనము చేయవలెను; విశేషముగా బ్రాహ్మణులు.",english:"Without that jyotiṣa, no one can ever know this. Therefore it must necessarily be studied — especially by brāhmaṇas.",tags:["jyotisha-essential","brahmana-study"],verified:"auto"},
        {sl:13,page:3,sanskrit:"యో నరః శాస్త్రమజ్ఞాత్వా జ్యోతిషం ఖలు నిన్దతి । రౌరవం నరకం భుక్త్వా చాన్దత్వం చాన్యజన్మని ॥ 13 ॥",telugu_bhava:"ఏ మనుజుడు ఈ జ్యోతిష్య శాస్త్రమును తెలిసికొనకుండా దానిని నిందించునో — అతడు రౌరవ నరకమును అనుభవించి, మరుజన్మలో అంధుడు (గ్రుడ్డివాడు) అగును.",english:"The person who, without knowing the śāstra, slanders jyotiṣa — having endured the Raurava hell, becomes blind in the next birth.",tags:["nindana","raurava-naraka","blindness"],verified:"auto"}
      ]
    },
    3: {
      title_te: "గ్రహగుణస్వరూపాధ్యాయః",
      title_en: "Chapter on the Qualities and Forms of Planets",
      summary_te: "భక్షక్రము (నక్షత్ర మండలము) యొక్క 27 భాగములు — అశ్వన్యాది నక్షత్రములు. స్థిరమైనవి నక్షత్రములు, సంచరించునవి గ్రహములు. సూర్యాది 9 గ్రహముల వర్ణములు, స్వభావములు, కారక శక్తులు. సూర్య-చంద్రులు రాజులు, కుజుడు సేనాపతి, బుధుడు రాజకుమారుడు, గురు-శుక్రులు మంత్రులు, శని ప్రేష్యకుడు (దాసుడు), రాహు-కేతువులు సేనా.",
      verses: [
        {sl:1,page:4,sanskrit:"కథితం భవతా ప్రేమ్ణా గ్రహోఽవతరణం మునే । తేషాం గుణస్వరూపాద్యం కృపయా కథ్యతాం పునః ॥ 1 ॥",telugu_bhava:"[మైత్రేయుడు:] ఓ మునీ! మీరు ప్రేమతో గ్రహ అవతారణ క్రమమును చెప్పితిరి. ఇపుడు దయతో వారి గుణములు, స్వరూపము మొదలగువానిని కూడా చెప్పుడు.",english:"O sage! You have lovingly told the descent of grahas. Now kindly tell their qualities, forms, and so on.",tags:["question","graha-qualities"],verified:"auto"},
        {sl:2,page:4,sanskrit:"శృణు విప్ర ప్రవక్ష్యామి భర్గోహాణాం పరిస్థితిమ్‌ । ఆకాశే యాని దృశ్యన్తే జ్యోతీర్బిమ్బాన్యనేకశః ॥ 2 ॥",telugu_bhava:"[పరాశర:] ఓ విప్రా! వినుము — గ్రహముల పరిస్థితిని చెప్పెదను. ఆకాశమున అనేకములుగా కనిపించు జ్యోతిర్బిమ్బములు (కాంతి బింబములు) ఉన్నవి.",english:"Listen, O brāhmaṇa — I shall declare the position of the bhargohas. Many luminous orbs are seen in the sky.",tags:["sky-bodies","jyotir-bimba"],verified:"auto"},
        {sl:3,page:4,sanskrit:"తేషు నక్షత్రసంజ్ఞాని గ్రహసంజ్ఞాని కానిచిత్‌ । తాని నక్షత్రనామాని స్థిరస్థానాని యాని చై ॥ 3 ॥",telugu_bhava:"వాటిలో కొన్ని నక్షత్రములు అని పిలువబడును, కొన్ని గ్రహములు అని. స్థిరమైన స్థానములు కల్గినవి నక్షత్రములు.",english:"Among these, some are called nakṣatras and some grahas. Those that have fixed positions are nakṣatras.",tags:["nakshatras","grahas-distinction","fixed-stars"],verified:"auto"},
        {sl:4,page:4,sanskrit:"గచ్ఛన్తి ఛాని గృహ్ణన్తి సతతం యే తు తే గ్రహాః । భచక్రస్య నగశ్యేంశా అశ్విన్యాదిసమాహ్వయాః ॥ 4 ॥",telugu_bhava:"ఏవి సంచరించుచు నక్షత్రములను గ్రహించుచుండునో — అవే గ్రహములు. భచక్రము (నక్షత్ర మండలము) యొక్క 27 భాగములే అశ్విన్యాది నక్షత్రములు.",english:"Those that move and seize the nakṣatras continuously are grahas. The 27 portions of the bhachakra are named Aśvinī etc.",tags:["graha-motion","27-nakshatras"],verified:"auto"},
        {sl:5,page:4,sanskrit:"తద్ద్వాదశవిభాగాస్తు తుల్య మేషాదిసంజ్ఞకాః । ప్రసిద్ధా రాశయః సన్తి గ్రహస్వర్యాదిసంజ్ఞకాః ॥ 5 ॥",telugu_bhava:"ఆ భచక్రము యొక్క 12 సమాన భాగములే మేషాది (12 రాశుల) పేర్లతో పిలువబడు ప్రసిద్ధ రాశులు; గ్రహముల అధిపత్యముతో పేర్లు కల్గి ఉండును.",english:"The 12 equal divisions [of the zodiac] are the well-known rāśis named Mēṣa etc., bearing the names of their planetary lords.",tags:["rasis","12-divisions","mesha-adi"],verified:"auto"},
        {sl:6,page:4,sanskrit:"రాశీనాముదయో లగ్నం తద్యశాదేవ జన్మినామ్‌ । గ్రాహయోగ్యవియోగాభ్యాం ఫలం చిన్త్యం శుభాశుభమ్‌ ॥ 6 ॥",telugu_bhava:"రాశుల ఉదయమే లగ్నము. దాని ద్వారానే జన్మించినవారికి ఫలము నిర్ణయింపబడును. గ్రహ యోగ-వియోగముల ద్వారా శుభాశుభ ఫలములు చింతించవలెను.",english:"The rising of rāśis is the lagna. By it alone the fruits of births are determined. Through grahas' conjunctions and disjunctions, auspicious-inauspicious fruits are to be considered.",tags:["lagna","udaya","yoga-viyoga"],verified:"auto"},
        {sl:7,page:4,sanskrit:"సంజ్ఞా నక్షత్రవృన్దానాం జ్ఞేయాః సామాన్యశాస్త్రతః । ఏతచ్ఛాస్త్రానుసారేణ రాశికేటఫలం బ్రువే ॥ 7 ॥",telugu_bhava:"నక్షత్ర సముదాయముల పేర్లు సామాన్య శాస్త్రముల ద్వారా తెలిసికొనవచ్చును. ఈ శాస్త్రము ప్రకారము — రాశి, గ్రహ ఫలములను చెప్పుచున్నాను.",english:"The names of nakṣatra groups are known from general śāstras. Following this śāstra, I declare the fruits of rāśis and grahas (kheṭas).",tags:["nakshatra-names","rasi-graha-phala"],verified:"auto"},
        {sl:8,page:4,sanskrit:"యస్మిన్‌ కాలే యతః ఖేటా యాన్తి దృగ్గణితైకతామ్‌ । తత ఏవ స్ఫుటాః కార్యాః దిక్కాలో చ స్ఫుటో విదా ॥ 8 ॥",telugu_bhava:"ఏ కాలములో ఏ గ్రహములు దృగ్గణిత ఏకత్వము (ప్రత్యక్ష పరిశీలన + గణిత గణన ఏకీభావము) పొందునో, ఆ ఆధారముననే గ్రహముల స్ఫుటములు లెక్కింపవలెను. దిక్కు, కాలము కూడ స్ఫుటముగా (ఖచ్చితముగా) తెలియవలెను.",english:"At whatever time and from whatever [position] the planets attain the unity of dr̥k (observation) and gaṇita (calculation), from that the sphuṭas (precise positions) must be derived. Direction and time too must be precise.",tags:["drik-ganita","sphuta","accuracy"],verified:"auto"},
        {sl:9,page:4,sanskrit:"స్వస్వదేశోద్భవైః సాధ్యం లగ్నం రాశ్యుదయైః స్ఫుటమ్‌ । అథాదౌ వచ్మి ఖేటానాం జాతిరూపగుణానహమ్‌ ॥ 9 ॥",telugu_bhava:"తమ తమ దేశములో జనించిన (అయా అక్షాంశ-రేఖాంశములలో గణించిన) రాశ్యుదయముల ద్వారా లగ్నము స్ఫుటముగా సాధించవలెను. ఇపుడు మొదట గ్రహముల జాతి, రూపము, గుణములను చెప్పెదను.",english:"Lagna must be precisely computed from the rising rāśis based on one's own locality. Now first I declare the jāti (caste/class), rūpa (form), and guṇa (qualities) of the grahas.",tags:["lagna-computation","local-rising","graha-jati-guna"],verified:"auto"},
        {sl:10,page:4,sanskrit:"అథ ఖేటా రవిశ్చన్ద్రో మఙ్గలశ్చ బుధస్తథా । గురుః శుక్రః శని రాహుః కేతుశ్చైతే యథాక్రమమ్‌ ॥ 10 ॥",telugu_bhava:"గ్రహములు (ఖేటములు) — రవి, చంద్రుడు, మంగళుడు, బుధుడు, గురువు, శుక్రుడు, శని, రాహువు, కేతువు — ఇవి యథాక్రమముగా 9 గ్రహములు.",english:"Now the grahas: Ravi, Candra, Maṅgala, Budha, Guru, Śukra, Śani, Rāhu, Ketu — these in due order.",tags:["nine-grahas","list"],verified:"auto"},
        {sl:11,page:4,sanskrit:"తత్రార్కశనిభూపుత్రాః క్షీణేన్దుదాహుకేతవః । క్రూరాః శేషగ్రహా సౌమ్యా క్రూరా క్రూరయుతో బుధః ॥ 11 ॥",telugu_bhava:"వాటిలో — సూర్యుడు, శని, భూపుత్ర (కుజుడు), క్షీణ చంద్రుడు, రాహువు, కేతువు — క్రూర గ్రహములు. మిగిలినవి సౌమ్య గ్రహములు. క్రూరులతో కూడిన బుధుడు క్రూరుడే.",english:"Of these — Sūrya, Śani, Maṅgala, the waning Moon, Rāhu, Ketu — are krūra (cruel/malefic). The rest are saumya (gentle/benefic). Mercury joined with malefics is also malefic.",tags:["malefics","benefics","krura-saumya","mercury-flexible"],verified:"auto"},
        {sl:12,page:4,sanskrit:"సర్వాత్మా చ దివానాధో మనః కుముదబాన్ధవః । సత్త్వం కుజో బుద్ధెః ప్రోక్తో బుధో వాణీప్రదాయకః ॥ 12 ॥",telugu_bhava:"దివసాధిపతి (సూర్యుడు) — సర్వాత్మ; కుముదబాంధవుడు (చంద్రుడు) — మనస్సు. కుజుడు సత్త్వ కారకుడు; బుధుడు బుద్ధి, వాక్కును ప్రసాదించు వాడు.",english:"The lord of day (Sūrya) is the universal Self (sarvātmā); the friend of lotuses (Candra) is the mind; Maṅgala is sattva (energy); Budha is said to bestow intellect and speech.",tags:["karaka","atma","manas","buddhi"],verified:"auto"},
        {sl:13,page:4,sanskrit:"దేవేజ్యో జ్ఞానసుఖదో భృగుర్వీర్యప్రదాయకః । ఋషిభిః ప్రోక్తయై ప్రోక్తశ్చాయసూస్త దుఃఖదః ॥ 13 ॥",telugu_bhava:"దేవేజ్యుడు (గురువు) జ్ఞానము, సుఖము ఇచ్చువాడు; భృగు (శుక్రుడు) వీర్యప్రదాత. ఋషులచే చెప్పబడిన ప్రకారము — చాయాసూతుడు (శని) దుఃఖప్రదాత.",english:"Devejya (Br̥haspati) gives wisdom and happiness; Bhr̥gu (Śukra) gives vital strength. As declared by the r̥ṣis, Chāyā-suta (Śani) is the bestower of sorrow.",tags:["jupiter-jnana","venus-veerya","saturn-duhkha"],verified:"auto"},
        {sl:14,page:4,sanskrit:"రవిచన్ద్రౌ తు రాజానో నేతా జ్యోతిర్ధరాత్మజః । బుధో రాజకుమారశ్చ సచివౌ గురుభార్గవౌ ॥ 14 ॥",telugu_bhava:"సూర్యచంద్రులు రాజులు; ధరాత్మజుడు (కుజుడు) సేనా నాయకుడు. బుధుడు రాజకుమారుడు; గురువు, శుక్రుడు — సచివులు (మంత్రులు).",english:"Sūrya and Candra are kings; Dharātmaja (Maṅgala) is the army chief. Budha is the prince; Guru and Bhārgava (Venus) are the ministers.",tags:["royalty","raja","senapati","mantri"],verified:"auto"},
        {sl:15,page:4,sanskrit:"ప్రేష్యకో రవిపుత్రశ్చ సేనా స్వర్యానుఘుచ్చకో । ఏవం క్రమేణ వై విప్ర సూర్యాదీన్‌ ప్రవిచిన్తయేత్‌ ॥ 15 ॥",telugu_bhava:"రవిపుత్రుడు (శని) ప్రేష్యకుడు (దాసుడు); రాహు-కేతువులు సేనా. ఈ క్రమములో — ఓ విప్రా — సూర్యాది గ్రహముల స్వభావమును చింతించవలెను.",english:"Ravi-putra (Śani) is the servant; the army are Rāhu and Ketu. Thus, O brāhmaṇa, one should consider Sūrya and the rest in due sequence.",tags:["saturn-servant","rahu-ketu-army"],verified:"auto"},
        {sl:16,page:4,sanskrit:"రక్తశ్యామో దివాధీశో గౌరగాత్రే నిశాకరః । నాత్యుద్యోద్ధః కుజో రక్తో దూర్వాశ్యామో బుధస్తథా ॥ 16 ॥",telugu_bhava:"దివాధీశుడు (సూర్యుడు) రక్తశ్యామ వర్ణము; నిశాకరుడు (చంద్రుడు) గౌర వర్ణ శరీరము. కుజుడు అతిగా ప్రకాశించని ఎర్రని వాడు; బుధుడు దూర్వాశ్యామ (గరిక-ఆకుపచ్చ) వర్ణము.",english:"The day-lord (Sūrya) is reddish-dark; the night-maker (Candra) has a fair body. Maṅgala is not too bright, red; Budha is dūrvā-green (grass-coloured).",tags:["varna","planet-colors"],verified:"auto"}
      ]
    },
    4: {
      title_te: "రాశిస్వరూపాధ్యాయః",
      title_en: "Chapter on the Forms of Rāśis (12 zodiac signs)",
      summary_te: "ద్వాదశ రాశుల పేర్లు, వర్ణములు, స్వభావములు, రూపములు, అధిపతులు మొదలగు లక్షణములు. విష్ణువుకు అవయవములుగా రాశులు: మేషము శిరస్సు, వృషభము ముఖము, మిథునము భుజములు ... ఈ వరుసలో మీనము పాదములు. చర-స్థిర-ద్విస్వభావ వర్గీకరణ; క్రూర-సౌమ్య విభజన; నర-స్త్రీ-నపుంసక లింగములు; తత్త్వములు (అగ్ని-పృథ్వి-వాయు-జల) ; దిక్కు, కాలబలము, ఉదయ క్రమము (శీర్షోదయ-పృష్ఠోదయ-ఉభయోదయ) ; అధిపతి గ్రహ, వర్ణ, వర్ణాధికారము — ఇవన్నీ వివరణ. చివర నిషేక లగ్న పరిశీలన గర్భస్థ ఫల జ్ఞానము కొరకు.",
      verses: [
        {sl:1,page:6,sanskrit:"అహోరాత్రస్య పూర్వాన్తలోపాద్ హోరాఽవశిష్యతే । తస్య విజ్ఞానమాత్రేణ జాతకర్మఫలం వదేత్‌ ॥ 1 ॥",telugu_bhava:"\"అహోరాత్రము\" అను పదమునకు మొదటి, చివరి అక్షరములను తీసివేసిన \"హోరా\" అను శబ్దము మిగులును. ఆ హోరాశాస్త్ర జ్ఞానము మాత్రముననే జాతకుని జన్మ-కర్మ ఫలములను చెప్పవచ్చును.",english:"Drop the first and last syllables of 'ahōrātra' (day-night), and 'hōrā' remains. Knowledge of that alone enables prediction of jātaka-karma-phala.",tags:["definition","horā"],verified:"auto"},
        {sl:2,page:6,sanskrit:"యదవ్యక్తాత్మకో విష్ణుః కాలరూపో జనార్దనః । తస్యాంగాని నిబోధ త్వం క్రమాన్మే పాదిరాశయః ॥ 2 ॥",telugu_bhava:"ఏ అవ్యక్త-ఆత్మస్వరూపుడు, కాలరూపుడు అయిన విష్ణువు ఉన్నాడో — ఆ జనార్దనుని అవయవములు (అంగములు) వరుసగా నీవు నా నుండి తెలిసికొనుము. మొదటిది: 12 రాశులే ఆ భగవంతుని పాదములు.",english:"The unmanifest Vishnu is Time-form Janārdana. Hear from me His limbs in sequence — the rāśis are His feet (the first limb).",tags:["cosmology","kāla","rāśi"],verified:"auto"},
        {sl:3,page:6,sanskrit:"మేషో వృషశ్చ మిథునం కర్కసింహకుమారికాః । తులాలిశ్చ ధనుర్నక్రే కుమ్భో మీనస్తతః పరమ్‌ ॥ 3 ॥",telugu_bhava:"మేషము, వృషభము, మిథునము, కర్కటకము, సింహము, కన్య (కుమారిక), తుల, వృశ్చికము (అలి), ధనుస్సు, మకరము (నక్ర), కుంభము, మీనము — ఇవియే ఆ పన్నెండు రాశులు.",english:"The twelve rāśis: Mēṣa, Vr̥ṣabha, Mithuna, Karka, Siṁha, Kanyā, Tulā, Vr̥ścika, Dhanus, Makara, Kumbha, Mīna.",tags:["rāśi","list"],verified:"auto"},
        {sl:4,page:6,sanskrit:"శీర్షానసే తథా బాహూ హృత్క్రోడకటిబస్తయః । గుహ్యోరుయుగలే జానుయుగ్మే వై జజ్ఞిరే తథా ॥ 4 ॥",telugu_bhava:"మేష = శిరస్సు; వృష = ముఖము; మిథున = బాహువులు (భుజములు); కర్కటక = హృదయము; సింహ = ఉదరము (క్రోడ); కన్య = నడుము-కటి; తుల = బస్తి (కటిప్రదేశము); వృశ్చిక = గుహ్యము (జననేంద్రియము); ధనుస్సు = తొడలు (ఊరువులు); మకర = మోకాళ్లు — ఈ క్రమములో జన్మించును.",english:"Head, face, the two arms; heart, belly, hips; loins (pelvic region), groin, the two thighs; the two knees — these were thus produced [as the rāśis Mēṣa to Makara].",tags:["kalapurusha","body-parts","rasi-anga"],verified:"auto"},
        {sl:5,page:6,sanskrit:"చరణౌ ద్వౌ తథా మేషాత్‌ జ్ఞేయాః శీర్షాదయః క్రమాత్‌ । చరస్థిరద్విస్వభావా క్రూరాక్రూరౌ నరస్త్రియౌ ॥ 5 ॥",telugu_bhava:"కుంభ = పిక్కలు, మీన = రెండు పాదములు. అట్లు మేషము నుండి ఆరంభించి శిరస్సు మొదలు పాదముల వరకు క్రమముగా 12 రాశులు అవయవములుగా తెలిసికొనవలెను. రాశులు చర-స్థిర-ద్విస్వభావములు; క్రూర-సౌమ్యములు; నర-స్త్రీ లింగములతో కల్గి ఉండును.",english:"Two feet [Mīna], beginning from Mēṣa as head — thus the rāśis are limbs in sequence. They are cara/sthira/dvisvabhāva (movable/fixed/dual), krūra/akrūra (cruel/gentle), and male/female.",tags:["chara-sthira-dvisvabhava","krura-akrura","male-female"],verified:"auto"},
        {sl:6,page:6,sanskrit:"పిత్తానిలద్రాత్త్వ్రకృశ్లేష్మికాశ్చ క్రియాదయః । రక్తవర్ణో బృహద్గాత్రశ్చతుష్పాదత్రివిక్రమీ ॥ 6 ॥",telugu_bhava:"మేషాది రాశులు పిత్త-వాత-పిత్తవాత-కఫాది ధాతువులతో కూడుకొన్నవి. మేష (క్రియ) — రక్తవర్ణ, విస్తృత శరీర, చతుష్పాద జాతి, త్రివిక్రమి (బలవంతుడు).",english:"Pitta, anila (vāta), [pitta-vāta mixed], śleṣmika — beginning with Krīya (Mēṣa). [Mēṣa is] red-coloured, large-bodied, four-footed, three-stepped (energetic).",tags:["dosha","mesha-properties","red"],verified:"auto"},
        {sl:7,page:6,sanskrit:"పూర్వావాసీ నృపజ్ఞాతిః శైలచారీ రజోగుణీ । పృష్ఠోదయః పావకే చ మేషరాశి కుజాధిపః ॥ 7 ॥",telugu_bhava:"మేష — తూర్పు దిక్కువాడు, రాజవంశజ్ఞాతి, శైలచారి (పర్వత నివాసి), రజోగుణ ప్రధాన; పృష్ఠోదయ (వెనుక భాగము ముందుగా ఉదయించునది), అగ్ని తత్త్వము, కుజుని అధిపత్యము.",english:"Eastward-dwelling, of royal lineage, mountain-roving, rajoguṇa-predominant; of pr̥ṣṭhōdaya (back-rising), of fire element, Mēṣa rāśi has Kuja (Mars) as lord.",tags:["mesha","direction-east","mars-lord","fire"],verified:"auto"},
        {sl:8,page:6,sanskrit:"శ్వేతః శుక్రాధిపో దీర్ఘశ్చతుష్పచ్చర్వరీతలీ । యామ్యేట గ్రామ్యో వణిగ్భూమిరజః పృష్ఠోదయో వృష ॥ 8 ॥",telugu_bhava:"వృషభ — శ్వేతవర్ణ, శుక్రుని అధిపత్యము, దీర్ఘ శరీర, చతుష్పాద, రాత్రిబలి, దక్షిణ దిక్కు, గ్రామచారి, వైశ్యజాతి, భూమి తత్త్వము, రజోగుణ, పృష్ఠోదయ.",english:"White, ruled by Śukra, long [body], four-footed, night-strong; southern, village-dweller, vaiśya, of earth element, rajoguṇa, pr̥ṣṭhōdaya — Vr̥ṣa.",tags:["vrishabha","venus-lord","earth","white"],verified:"auto"},
        {sl:9,page:6,sanskrit:"శీర్షోదయో నృమిథునం సగదం చ సవీణికమ్‌ । ప్రత్యగ్యాయుర్ద్విపాత్రాత్రిబలీ గ్రామపూర్యోనిలీ ॥ 9 ॥",telugu_bhava:"మిథున — శీర్షోదయ (శిరస్సు ముందుగా ఉదయించునది), మానవ-యుగళ స్వరూపము (నర-నారి), గద-వీణ సహితము, పశ్చిమ దిక్కు, ద్విపాద, రాత్రిబలి, గ్రామ-పుర నివాస, వాయు తత్త్వము.",english:"Śīrṣōdaya (head-rising), human couple [shape], with mace and lyre; westward, two-footed, night-strong, village-and-city dwelling, of air element — Mithuna.",tags:["mithuna","head-rising","west","air"],verified:"auto"},
        {sl:10,page:6,sanskrit:"సమగాత్రో హరిద్వర్ణో మిథునాఖ్యో బుధాధిపః । పాటలో వనచారీ చ బ్రాహ్మణో నిశి వీర్యవాన్‌ ॥ 10 ॥",telugu_bhava:"మిథున — సమ శరీర, ఆకుపచ్చ (హరిద్‌) వర్ణ, బుధుని అధిపత్యము. (కర్కటకము —) పాటల (గులాబి-ఎరుపు) వర్ణ, వనచారి, బ్రాహ్మణ జాతి, రాత్రి బలవంతుడు.",english:"Equal-bodied, green-coloured, named Mithuna, ruled by Budha. [Karka is] pinkish, forest-dwelling, brāhmaṇa, night-strong.",tags:["mithuna-mercury","karka-brahmana"],verified:"auto"},
        {sl:11,page:6,sanskrit:"బహుపాదచరః స్థాల్యతనుః సత్త్వగుణీ జలీ । పృష్ఠోదయో కర్కరాశిర్నిగాంకాబ్దిపతిః స్మృతః ॥ 11 ॥",telugu_bhava:"కర్కటకము — బహుపాదచరి (అనేక పాదములతో నడుచునది, పీత), స్థూల తనువు, సత్త్వగుణ, జల తత్త్వము, పృష్ఠోదయ, నిగాంకాబ్దిపతి (= చంద్రుని ఆధిపత్యము) అని చెప్పబడును.",english:"Many-footed, of stout body, sattva-guṇa, watery, pr̥ṣṭhōdaya — Karka rāśi, ruled by the lord of the sea (Candra).",tags:["karka","cancer","moon-lord","water"],verified:"auto"},
        {sl:12,page:6,sanskrit:"సింహః సూర్యాధిపః సత్త్వీ చతుష్పాత్‌ క్షత్రియో వనీ । శీర్షోదయో బృహద్గాత్రః పాణ్డుః పూర్వేద్‌ ద్యుదీర్యవాన్‌ ॥ 12 ॥",telugu_bhava:"సింహ — సూర్యుని అధిపత్యము, సత్త్వగుణ, చతుష్పాద, క్షత్రియ జాతి, వన నివాసి, శీర్షోదయ, విస్తృత శరీర, పాండు (తెలుపు-పీత) వర్ణ, తూర్పు దిక్కు, పగటి బలవంతుడు.",english:"Siṁha — ruled by Sūrya, sattvic, four-footed, kṣatriya, forest-dweller, śīrṣōdaya, large-bodied, pale-coloured, eastward, day-strong.",tags:["simha","sun-lord","kshatriya","day-strong"],verified:"auto"},
        {sl:13,page:6,sanskrit:"పార్వతీయాధ కన్యాఖ్యా రాశిర్దినబలాన్వితా । శీరోదయా చ మధ్యాంగా దీపపాదేఽమ్బరా చ సా ॥ 13 ॥",telugu_bhava:"కన్య (కుమారిక) — పర్వత ప్రాంతవాసి, దినబలాన్విత, శీర్షోదయ, మధ్య అవయవ స్త్రీరూప, దీపము-పాదములు-అంబరము (వస్త్రము) ధరించునది.",english:"Mountainous-region, named Kanyā, the rāśi endowed with day-strength; head-rising, of medium body, holding lamp, walking, robed.",tags:["kanya","virgin","day-strong","head-rising"],verified:"auto"},
        {sl:14,page:6,sanskrit:"సా సస్యదహనా వైశ్యా చిత్రవర్ణా ప్రభస్వినీ । కుమారీ తామసా యుక్తా బాలభావా బుధాధిపా ॥ 14 ॥",telugu_bhava:"కన్య — సస్య-దహన (పంట-అగ్ని సంబంధ), వైశ్య జాతి, చిత్రవర్ణ (వివిధ వర్ణ), ప్రకాశమంతురాలు, కుమారీ స్వరూప, తామస గుణ, బాల్యావస్థ, బుధ అధిపత్యము.",english:"Crop-burning, vaiśya, multi-coloured, radiant; virgin (kumārī), tāmasa, child-like, ruled by Budha.",tags:["kanya","vaishya","virgin","mercury"],verified:"auto"},
        {sl:15,page:6,sanskrit:"శీర్షోదయా ద్యువీర్యాద్యస్థూలః కృష్ణో రజోగుణీ । పశ్చిమో భూచరో ఘూ తీ శూద్రో మధ్యతనుర్ద్విపాత్‌ ॥ 15 ॥",telugu_bhava:"తుల — శీర్షోదయ, దివాబలి, స్థూల శరీర, కృష్ణ వర్ణ, రజోగుణ, పశ్చిమ దిక్కు, భూచర, శూద్ర జాతి, మధ్యమ తనువు, ద్విపాద.",english:"Head-rising, day-strong, stout, dark, rajoguṇa, western, earth-walker, śūdra, medium-bodied, two-footed — [Tulā].",tags:["tula","libra","west","sudra"],verified:"auto"},
        {sl:16,page:6,sanskrit:"శుక్రాధిపోఽథ స్వల్పాంగో బహుపాదధ్మాతో బలీ । సౌమ్యస్తో దినవీర్యాద్యః పీశంగో జలభూః వ ॥ 16 ॥",telugu_bhava:"తుల — శుక్రుని అధిపత్యము. (వృశ్చికము —) స్వల్పాంగ, బహుపాదచరి (అనేక పాదములు), బలవంతుడు, సౌమ్యస్థ, దివాబలి, పీశంగ (పసుపు-ఎరుపు) వర్ణ, జల-భూ తత్త్వములు.",english:"Ruled by Śukra. [Vr̥ścika is] small-limbed, many-footed, swollen, strong, gentle-stationed, day-strong, dusky-yellow, water-and-land.",tags:["tula-venus","vrischika"],verified:"auto"},
        {sl:17,page:6,sanskrit:"రోమస్వాద్యేఽతితీక్ష్ణాగ్రీ వృశ్చికశ్చ కుజాధిపః । పృష్ఠోదయో త్వథ ధనుర్గురుస్వామీ చ సాత్త్వికః ॥ 17 ॥",telugu_bhava:"వృశ్చికము — రోమవంతము, అతి తీక్ష్ణాగ్ర (అతి కఠినమైన అగ్రభాగము), కుజుని అధిపత్యము. ధనుస్సు — పృష్ఠోదయ, గురుని అధిపత్యము, సాత్త్విక గుణ.",english:"Hairy at first, sharp-pointed — Vr̥ścika ruled by Kuja (Mars). Pr̥ṣṭhōdaya, Dhanus ruled by Guru, of sattva-guṇa.",tags:["scorpion","mars","sagittarius","jupiter"],verified:"auto"},
        {sl:18,page:6,sanskrit:"పింగలో నిశివీర్యాద్యః పావకే క్షత్రియో ద్విపాద్‌ । ఆదావస్తే చతుష్పాదః సమగాత్రో ధనుర్ధరః ॥ 18 ॥",telugu_bhava:"ధనుస్సు — పింగళ (గోధుమ-తామ్ర) వర్ణ, రాత్రి బలి, అగ్ని తత్త్వము, క్షత్రియ, ద్విపాద [మొదటి అర్ధభాగము]; చివరి అర్ధభాగము చతుష్పాద; సమగాత్ర, ధనుర్ధర (విల్లు ధరించునది).",english:"Tawny, night-strong, of fire, kṣatriya, two-footed at start, four-footed at end, equal-bodied, bow-bearer.",tags:["sagittarius","dhanus","jupiter","fire"],verified:"auto"},
        {sl:19,page:6,sanskrit:"పూర్వాస్తో వసుధాచారీ తేజస్వీ బ్రాహ్మణో కృతః । మన్దాధిపస్త్వమి భౌమి యామ్యేట చ నిశి వీర్యవాన్‌ ॥ 19 ॥",telugu_bhava:"ధనుస్సు — తూర్పు దిక్కు, వసుధాచారి (భూమిపై సంచరించు), తేజస్వి, బ్రాహ్మణ. (మకర —) శని (మన్ద) అధిపత్యము, భూ తత్త్వము, దక్షిణ దిక్కు, రాత్రి వీర్యవంతుడు.",english:"Eastern, earth-roving, brilliant, brāhmaṇa. [Makara is] ruled by Manda (Saturn), earth-bound, southern, night-strong.",tags:["dhanus-east","makara-saturn"],verified:"auto"},
        {sl:20,page:6,sanskrit:"పృష్ఠోదయో బృహద్గాత్రః కర్బురో వనభూచరః । ఆదౌ చతుష్పదోఽన్తే తు విపదే జలగే మతః ॥ 20 ॥",telugu_bhava:"మకరము — పృష్ఠోదయ, విస్తృత శరీర, కర్బుర (నలుపు-తెలుపు మిశ్రమ) వర్ణ, వన-భూ చరి. మొదటి అర్ధభాగములో చతుష్పాద, చివరి అర్ధభాగములో విపద (పాదరహిత) జలగత.",english:"Pr̥ṣṭhōdaya, large-bodied, mottled, forest-and-land roving; four-footed at start, footless and aquatic at end.",tags:["makara","capricorn","crocodile-form"],verified:"auto"},
        {sl:21,page:6,sanskrit:"కుమ్భః కుమ్భీ నరో బభ్రువర్ణో మధ్యతనుర్ద్విపాత్‌ । ద్యువీర్యో జలమధ్యస్థో వాతశీర్షోదయః తమః ॥ 21 ॥",telugu_bhava:"కుంభము — కుండను ధరించిన నర రూపము, బభ్రు (గోధుమ) వర్ణ, మధ్యమ తనువు, ద్విపాద, దివాబలి, జలమధ్యస్థ, వాయు తత్త్వము, శీర్షోదయ, తామస గుణ.",english:"Kumbha — pot-bearer, human-shaped, brown-coloured, medium-bodied, two-footed, day-strong, mid-water-stationed, of air, head-rising, tamoguṇa.",tags:["kumbha","aquarius","pot-bearer","tamas"],verified:"auto"},
        {sl:22,page:6,sanskrit:"శూద్రః పశ్చిమదేశస్య స్వామీ దైవాకరి స్మృతః । మీనౌ పుచ్ఛాస్యసంలగ్నౌ మీనరాశిర్దివాబలీ ॥ 22 ॥",telugu_bhava:"కుంభము — శూద్ర జాతి, పశ్చిమ దిక్‌ స్వామి, శని (దైవాకరి) అధిపత్యము కల్గినది. మీనము — తోక-ముఖము పరస్పరము లగ్నమైన రెండు చేపలతో కూడిన రాశి, దివాబలి.",english:"Śūdra, lord of the western direction, said to be of Saturn. Mīna — two fish joined tail-to-mouth, the Pisces rāśi, day-strong.",tags:["kumbha-saturn","mina-pisces"],verified:"auto"},
        {sl:23,page:6,sanskrit:"జలీ సత్త్వగుణాడ్యశ్చ సస్థో జలచరో ద్విజః । అపదే మధ్యదేహీ చ సౌమ్యస్తో హ్యుభయోదయీ ॥ 23 ॥",telugu_bhava:"మీనము — జల తత్త్వము, సత్త్వగుణ సంపన్న, సహజ స్థితి, జలచర, ద్విజ (బ్రాహ్మణ), పాదరహిత, మధ్య దేహి, సౌమ్యస్థ, ఉభయోదయ (శీర్షోదయ-పృష్ఠోదయ రెండింటికీ).",english:"Watery, sattva-rich, well-stationed, aquatic, twice-born (brāhmaṇa), footless, medium-bodied, gentle-stationed, of both modes of rising.",tags:["mina","water","brahmana","ubhayodaya"],verified:"auto"},
        {sl:24,page:6,sanskrit:"సురాచార్యాధిపశ్చేతి రాశీనాం గదితా గుణాః । త్రింశద్వాద్యాత్మకానాం చ స్థూలసూక్ష్మఫలాయ చ ॥ 24 ॥",telugu_bhava:"మీనము — సురాచార్య (గురువు) అధిపత్యము. — ఇట్లు 30 అంశలతో కూడిన ద్వాదశ రాశుల గుణములు చెప్పబడెను; స్థూల-సూక్ష్మ ఫల ప్రయోగమునకు ఉపయోగము.",english:"Ruled by Surācārya (Br̥haspati). Thus the qualities of the rāśis — each of 30 [aṁśas] — are declared, for both gross and subtle phala-prediction.",tags:["mina-jupiter","rasi-summary","30-amshas"],verified:"auto"},
        {sl:25,page:6,sanskrit:"అథాతః సమ్ప్రవక్ష్యామి శృణుష్వ మునిపుంగవ । జన్మలగ్నం చ సంశోధ్య నిషేకం పరిశోధయేత్‌ ॥ 25 ॥",telugu_bhava:"ఇపుడు మరల చెప్పుచున్నాను — ఓ ముని-శ్రేష్ఠా, వినుము. జన్మ లగ్నమును సంశుద్ధి చేసి, దాని ఆధారముగా నిషేక (గర్భాధాన) లగ్నమును పరిశోధించవలెను.",english:"Now I shall declare — listen, foremost of munis. Having purified the birth-lagna, one must derive the niṣeka (conception) lagna.",tags:["niseka","conception-lagna","janma-lagna"],verified:"auto"},
        {sl:26,page:6,sanskrit:"తదాహం సంప్రవక్ష్యామి మైత్రేయ త్వం విధారయ । జన్మలగ్నాత్‌ పరిజ్ఞానం నిషేకం సర్వజ్ఞను యాత్‌ ॥ 26 ॥",telugu_bhava:"ఓ మైత్రేయా! దానిని ఇపుడు చెప్పెదను, నీవు మనస్సులో ధరించుము. జన్మ లగ్నము ద్వారా నిషేక లగ్నమును సర్వజ్ఞులు తెలిసికొనవచ్చును.",english:"That I shall now declare — Maitreya, hold it [in your mind]. By the birth-lagna, the niṣeka-lagna can be known by the all-knowing.",tags:["maitreya","conception","janma-lagna-derivation"],verified:"auto"},
        {sl:27,page:6,sanskrit:"యస్మిన్‌ భావే స్థితో మన్దస్య మాన్దర్యదన్తరమ్‌ । లగ్నభాగ్యాన్తరం యోజ్యం యచ్చ రాశ్యాది జాయతే ॥ 27 ॥",telugu_bhava:"జన్మ సమయములో ఏ భావములో మన్దుడు (శని) ఉన్నాడో, ఆ స్థాన అంతరమును తీసుకొని — లగ్న-భాగ్యాంతరమును (లగ్నము-9వ భావముల అంతరమును) దానిలో జతపరచిన ఏ రాశ్యాదికం వచ్చునో [అదే నిషేక లగ్నము].",english:"In whichever bhāva Manda (Saturn) is positioned, [taking] the difference of Manda; the lagna-bhāgya difference is to be added — whatever rāśi etc. is produced [is the niṣeka].",tags:["niseka-calculation","saturn-position"],verified:"auto"},
        {sl:28,page:6,sanskrit:"మాసాది తన్నితం జ్ఞేయం జన్మతః ప్రాక్‌ నిషేకజమ్‌ । యద్యదృశ్యదలేభ్యేషదిన్దోర్యక్తభాగయుక్‌ ॥ 28 ॥",telugu_bhava:"జన్మ తేదీకి ముందు కాలమునుండే నిషేక మాస-తేదీ ఆ గణితముతో తెలిసికొనవచ్చును. చంద్రుని అదృశ్య-భాగము (అమావాస్య పక్షభాగము) తో జతగూడిన ప్రకారము.",english:"From that one knows the [conception] month etc., as the niṣeka [time] preceding the birth — based on the Moon's invisible portion combined with the relevant degree.",tags:["niseka-month","moon-phase"],verified:"auto"},
        {sl:29,page:6,sanskrit:"తత్కాలే సాధయేల్లగ్నం శోధయేత్‌ పూర్వవత్తనుమ్‌ । తస్మాచ్చభాశుభం వాచ్యం గర్భస్థస్య విశేషతః ॥ 29 ॥",telugu_bhava:"ఆ కాలమునకు లగ్నమును సాధించి, పూర్వము చెప్పిన ప్రకారము శరీర-తనుభావమును పరిశోధించవలెను. దాని ఆధారముగా గర్భస్థ శిశువు యొక్క శుభాశుభములను విశేషముగా చెప్పవచ్చును.",english:"At that time compute the lagna, purify the body-house as before; from that, the auspicious-inauspicious for the foetus is to be told especially.",tags:["niseka-lagna","foetus-prediction"],verified:"auto"},
        {sl:30,page:6,sanskrit:"శుభాశుభం వదేత్‌ పేల్లీవనం మరణం తథా । ఏవం నిషేకలగ్నేన సమ్యగ్‌ జ్ఞేయం స్వకల్పనాత్‌ ॥ 30 ॥",telugu_bhava:"గర్భస్థ శిశువు యొక్క జీవిత-మరణాది శుభాశుభములను ఇట్లు చెప్పవలెను. ఈ విధముగా నిషేక లగ్నము ద్వారా సమగ్రముగా స్వ-గణనమనుసరించి తెలిసికొనవలెను.",english:"Auspicious-inauspicious is to be declared — life and death likewise. Thus by the niṣeka-lagna, all is to be known properly through one's own derivation.",tags:["niseka-prediction","life-death"],verified:"auto"}
      ]
    },
    5: {
      title_te: "విశేషలగ్నాధ్యాయః",
      title_en: "Chapter on Special Lagnas (Bhāva, Hōrā, Ghaṭi)",
      summary_te: "ఈ అధ్యాయములో మూడు విశేష లగ్నములు — భావ లగ్న, హోరా లగ్న, ఘటి లగ్నము — వాని నిర్వచనము, గణన పద్ధతి వివరింపబడెను. సూర్యోదయము నుండి ప్రతి 5 ఘటికలకు ఒక భావ లగ్న మారును; సార్ధ-ద్వి (2.5) ఘటికలకు హోరా లగ్నము; ఒక్కొక్క ఘటికకు ఘటి లగ్నము మారును. వీటిని జన్మ సమయము నుండి గణించి, ఆ కాలమునకు అనువైన భావ-చక్రములను నిర్మించి, గ్రహ స్థానములను రాశి-లగ్నము ప్రకారము నిర్ణయించవలెను.",
      verses: [
        {sl:1,page:7,sanskrit:"అథాహం సమ్ప్రవక్ష్యామి తవాగ్రే ద్విజసత్తమ । భావహోరాఘటిసంజ్ఞలగ్నానీతి పృథక్‌ పృథక్‌ ॥ 1 ॥",telugu_bhava:"ఓ ద్విజశ్రేష్ఠా! ఇపుడు నేను నీ ముందు భావలగ్న, హోరాలగ్న, ఘటిలగ్న — అను విశేష లగ్నములను వేరువేరుగా చెప్పెదను.",english:"Now, O best of brāhmaṇas, I shall declare separately the lagnas called Bhāva, Hōrā, and Ghaṭi.",tags:["special-lagna","bhava","hora","ghati"],verified:"auto"},
        {sl:2,page:7,sanskrit:"సూర్యోదయం సమారభ్య ఘటికానాం తు పంచకమ్‌ । ప్రయాతి జన్మపర్యన్తం భావలగ్నం తదేవ హి ॥ 2 ॥",telugu_bhava:"సూర్యోదయము నుండి ప్రారంభించి, ప్రతి 5 ఘటికలకు [= 2 గంటలకు] ఒక భావ లగ్నము గడిచిపోవును. జన్మ కాలము వరకు ఇట్లు గణించినదే భావ లగ్నము.",english:"Beginning from sunrise, every five ghaṭikās [= 2 hours]; what proceeds up to the birth-time is itself the Bhāva-lagna.",tags:["bhava-lagna","sunrise","5-ghatika"],verified:"auto"},
        {sl:3,page:7,sanskrit:"ఇష్టం ఘట్యాదికం భక్త్వా పంచభిర్బ్రాదిజం ఫలమ్‌ । యోజ్యమోదయికే సూర్యే భావలగ్నం స్ఫుటం చ తత్‌ ॥ 3 ॥",telugu_bhava:"ఇష్ట కాలము (జన్మ కాలము) యొక్క ఘటికాదికమును 5 చేత భాగించి, వచ్చిన మేషాది ఫలమును సూర్యోదయ లగ్నములో జతపరచిన అది స్ఫుట భావ లగ్నము.",english:"Divide the iṣṭa-time (in ghaṭikās etc.) by 5; the Mēṣa-onwards result, added to the rising-Sun lagna, gives the precise Bhāva-lagna.",tags:["bhava-calculation","ghati-by-5"],verified:"auto"},
        {sl:4,page:7,sanskrit:"తథా సార్ధద్విఘటికామితాదర్క్యోదయాద్‌ ద్విజ । ప్రయాతి లగ్నం తన్నామ హోరాలగ్నం ప్రచక్షతే ॥ 4 ॥",telugu_bhava:"ఓ ద్విజా! అట్లే సూర్యోదయము నుండి ప్రతి సార్ధ-ద్వి (2.5) ఘటికలకు [= 1 గంట = 1 హోర] ఒక లగ్నము గడిచిపోవును. దానినే హోరా లగ్నము అని చెప్పుదురు.",english:"Likewise, O brāhmaṇa, from sunrise every two-and-a-half ghaṭikās [= 1 hour = 1 hōrā], a lagna proceeds — that is called the Hōrā-lagna.",tags:["hora-lagna","2.5-ghatika","hour"],verified:"auto"},
        {sl:5,page:7,sanskrit:"ఇష్టఘుట్యాదికం దివ్షున్నం పఞ్చ్యాస్తం బాధికం చ యత్‌ । యోజ్యమోదయికే భానౌ హోరాలగ్నం స్ఫుటం హి తత్‌ ॥ 5 ॥",telugu_bhava:"ఇష్ట కాలము (ఘటికాది)ని 2 చే గుణించి, 5 చే భాగించి వచ్చిన శేష ఫలమును సూర్యోదయ లగ్నములో జతపరచిన అదే స్ఫుట హోరా లగ్నము.",english:"Multiply the iṣṭa-ghaṭi by 2 and divide by 5; whatever results, added to the rising-Sun's lagna, is the precise Hōrā-lagna.",tags:["hora-calculation"],verified:"auto"},
        {sl:6,page:7,sanskrit:"కథయామి ఘటిలగ్నం స్నను త్వం ద్విజసత్తమ । సూర్యోదయాత్‌ సమారభ జన్మ కాలావది క్రమాత్‌ ॥ 6 ॥",telugu_bhava:"ఓ ద్విజోత్తమా! ఇపుడు ఘటి లగ్నమును చెప్పెదను, వినుము. సూర్యోదయము నుండి ప్రారంభించి జన్మ కాలము వరకు క్రమముగా [గణించవలెను].",english:"I shall now declare the Ghaṭi-lagna — listen, O best of brāhmaṇas. Beginning from sunrise, in sequence up to the birth-time.",tags:["ghati-lagna","calculation"],verified:"auto"},
        {sl:7,page:7,sanskrit:"ఏకైకఘటికామానాత్‌ లగ్నం యద్యాత్‌ బాధికమ్‌ । తదేవ ఘటికాలగ్నం కథితం నారదాదిభిః ॥ 7 ॥",telugu_bhava:"ప్రతి ఒక్క ఘటిక మానము వరకు [= 24 నిమిషములకు] గడిచిన లగ్నము — అదే ఘటికా లగ్నము అని నారదాది మహర్షులచే చెప్పబడెను.",english:"That lagna proceeding by each single ghaṭikā [= 24 minutes] — that is called the Ghaṭikā-lagna by Nārada and others.",tags:["ghatika-lagna","narada","1-ghatika"],verified:"auto"},
        {sl:8,page:7,sanskrit:"రాశ్యస్ఫు ఘటితుల్యా: పలార్ధప్రమితాంశకాః । యోజ్యమోదయికే భానౌ ఘటిలగ్నం స్ఫుటం హి తత్‌ ॥ 8 ॥",telugu_bhava:"ఇష్ట ఘటికలతో సమానమైన రాశ్యంశలను, పలార్ధ ప్రమాణ అంశలతో సహా, సూర్యోదయ లగ్నములో కలిపిన అదే స్ఫుట ఘటి లగ్నము.",english:"Rāśi-aṁśas equal to the iṣṭa-ghaṭis, with palārdha-prameya parts; added to the rising-Sun's lagna, gives the precise Ghaṭi-lagna.",tags:["ghati-calculation","palardha"],verified:"auto"},
        {sl:9,page:7,sanskrit:"క్రమాదిషం చ లగ్నానాం భావకోష్ఠం పృథక్‌ లిఖేత్‌ । యే గ్రహా యత్ర భే తత్ర తే స్థాప్యా రాశిలగ్నవత్‌ ॥ 9 ॥",telugu_bhava:"క్రమముగా ఈ [మూడు] లగ్నములకు భావ-కోష్ఠములను (చక్రములను) వేరువేరుగా వ్రాయవలెను. ఏ గ్రహములు ఏ రాశిలో ఉన్నవో, ఆ స్థానములలో — రాశి లగ్న చక్రమువలెనే — స్థాపించవలెను.",english:"In sequence, draw separate bhāva-koṣṭha (charts) for each lagna. Whichever planets are in whichever rāśi, place them just as in the Rāśi-lagna chart.",tags:["bhava-koshtha","chart-construction"],verified:"auto"},
        {sl:10,page:7,sanskrit:"వర్ణదాఖ్యదశాం భానాం కథయామ్యధ తే.గ్రతః । యస్య విజ్ఞానమాత్రేణ వదేదాయుర్భవం ఫలమ్‌ ॥ 10 ॥",telugu_bhava:"ఇపుడు నీ ముందు 'వర్ణద' అను దశా (గ్రహ-దశా) ను చెప్పెదను. దాని జ్ఞానము మాత్రముననే ఆయుష్షు, జన్మ ఫలములను చెప్పవచ్చును.",english:"Now I shall declare to you the dasha called 'Varṇadā'. By its knowledge alone, one can predict longevity and birth-fruits.",tags:["varnada-dasha","longevity"],verified:"auto"},
        {sl:11,page:7,sanskrit:"ఓజలగ్నప్రసూతానాం మేషాదేర్గణయేత్‌ క్రమాత్‌ । సమలగ్నప్రసూతానామ్‌ మీనాదేరపసవ్యతః ॥ 11 ॥",telugu_bhava:"ఓజ (బేసి-సంఖ్య) లగ్నములో జన్మించినవారికి మేషాది క్రమములో గణించవలెను. సమ (సరి-సంఖ్య) లగ్నములో జన్మించినవారికి మీనాది అపసవ్య (ప్రతిలోమ) క్రమములో గణించవలెను.",english:"For those born in odd lagnas (Mēṣa, Mithuna, etc.), count from Mēṣa onwards in sequence. For those born in even lagnas, count from Mīna onwards in reverse.",tags:["odd-even-lagna","counting-direction","varnada"],verified:"auto"},
        {sl:12,page:7,sanskrit:"మేషమీనాదితః పశ్చాదద్యో రాశిః స తు వర్ణదః । తదైవ హోరాలగ్నానం గణయిత్వా తతః పరమ్‌ ॥ 12 ॥",telugu_bhava:"మేష-మీనాది క్రమములో [మొదట] వచ్చిన రాశియే 'వర్ణద' అని చెప్పబడును. అట్లే హోరా లగ్నము యొక్క గణనమును చేసి, ఆపై [మిగిలిన లగ్నములు].",english:"The first rāśi obtained from Mēṣa-Mīna sequence is the Varṇada. Likewise compute the Hōrā-lagna and then the rest.",tags:["varnada-rasi","hora-computation"],verified:"auto"},
        {sl:13,page:7,sanskrit:"ఓజత్వేన సమత్వేన సయాతీయే ఉభే యది । తర్తి సంఖ్యా యోజ్యయోతా వైజాత్యే తు వియోజయేత్‌ ॥ 13 ॥",telugu_bhava:"ఒకవేళ రెండు లగ్నములు (హోరాలగ్న, వర్ణద) ఓజత్వము (బేసి) లేదా సమత్వము (సరి) తో కలిసి ఒకే జాతిలో ఉన్నచో — వాని సంఖ్యలను కలుపవలెను. వేర్వేరు జాతిలో ఉన్నచో వియోగము (తీసివేత) చేయవలెను.",english:"If both [lagnas] are of the same parity (both odd or both even), add their counts together. If of different parity, subtract.",tags:["odd-even-combination","varnada-rule"],verified:"auto"},
        {sl:14,page:7,sanskrit:"ఏతత్త్రయోజనం వక్ష్యే శృణు త్వం ద్విజపుంగవ । హోరాలగ్నభయోర్వేణేయ సబలాదుర్బలాద్దశా ॥ 14 ॥",telugu_bhava:"ఈ ముడింటి (మూడు లగ్నముల) ప్రయోగమును నేను చెప్పెదను — ఓ ద్విజపుంగవా, వినుము. హోరాలగ్నము యొక్క భావనుండి బలవంతుని-బలహీనుని ఆధారముగా దశ నిర్ణయము.",english:"I shall declare the application of these three [lagnas] — listen, O foremost brāhmaṇa. From the strong or weak [graha] in the bhāva of the Hōrā-lagna, the dasha is to be determined.",tags:["three-lagnas-application","strong-weak-dasha"],verified:"auto"},
        {sl:15,page:7,sanskrit:"యత్సన్యే వర్ణదే లగ్నాత్‌ తత్తత్స్మ్యక్రమేణ తు । క్రమయుత్రమభేదేన దశా స్యాదోజయుగ్మయోః ॥ 15 ॥",telugu_bhava:"వర్ణద లగ్నము నుండి ఏది ఉన్నదో దాని క్రమ-సంయోగము ప్రకారము — క్రమ-వ్యుత్క్రమ భేదముతో — ఓజ-యుగ్మ లగ్నములలో దశ నిర్ణయము జరుగును.",english:"Whatever lies adjacent in the Varṇada-lagna, in due sequential combination — by direct or reverse order — the dasha applies for odd and even lagnas respectively.",tags:["dasha-direction","varnada"],verified:"auto"},
        {sl:16,page:7,sanskrit:"పాపదృష్టి పాపయోగే వర్ణస్య త్రికోణకే । యది స్యాత్‌ తర్తి తద్రాశిపర్యన్తం తస్య జీవనమ్‌ ॥ 16 ॥",telugu_bhava:"వర్ణద లగ్నము యొక్క త్రికోణములలో పాప దృష్టి, పాప యోగము ఉన్నచో — ఆ రాశి పర్యంతము జాతకుని జీవితకాలము.",english:"If there be malefic aspects or yogas in the trines of the Varṇada — life extends only up to that rāśi's [period].",tags:["papa-drishti","longevity-limit"],verified:"auto"},
        {sl:17,page:7,sanskrit:"రుద్రకూలే యద్దైవాయుర్క్రణాది నిరూప్యతే । తదైవ వర్ణదస్యపి త్రికోణ పాపసంగమీ ॥ 17 ॥",telugu_bhava:"రుద్ర భావములో దైవాయువు, మరణ కారణములు ఎట్లు నిరూపింపబడునో — అట్లే వర్ణద యొక్క త్రికోణములో పాప-సంగమము ఉన్నచో [అదే ఫలము].",english:"As in Rudra-bhāva (8th) the divine longevity-causes are determined, likewise for the Varṇada — by the malefic conjunction in its trines.",tags:["rudra-bhava","trines-malefic"],verified:"auto"},
        {sl:18,page:7,sanskrit:"వర్ణదాదపి భో విప్ర లగ్నవచ్చిన్త్రయేత్‌ ఫలమ్‌ । వర్ణదాత్‌ సప్తమాద్‌ భావత్‌ కల్త్రాయుర్విచిన్త్రయేత్‌ ॥ 18 ॥",telugu_bhava:"ఓ విప్రా! వర్ణద లగ్నము నుండి కూడా జన్మలగ్నము వలెనే ఫలము చింతించవలెను. వర్ణద నుండి 7వ భావములో కల్త్రాయువు (భార్య/భర్త ఆయుష్షు) చింతించవలెను.",english:"O brāhmaṇa! From the Varṇada too, fruits should be considered just as from the lagna. From the 7th from Varṇada, the longevity of the spouse is to be examined.",tags:["varnada-as-lagna","spouse-longevity"],verified:"auto"},
        {sl:19,page:7,sanskrit:"ఏకాదశాద్రజస్య తృతీయాత్తు యవీయసః । సుతస్య పంచమే విద్యాన్మాతుశ్చతుర్దభావత్‌ ॥ 19 ॥",telugu_bhava:"11వ భావము నుండి జ్యేష్ఠ సోదరుని, 3వ భావము నుండి కనిష్ఠ సోదరుని, 5వ భావము నుండి సంతానుని, 4వ భావము నుండి తల్లి యొక్క విషయము తెలిసికొనవలెను.",english:"From the 11th, the elder brother; from the 3rd, the younger; from the 5th, the children; from the 4th, the mother — [are to be examined].",tags:["bhava-meanings","relations"],verified:"auto"},
        {sl:20,page:7,sanskrit:"పితుశ్చ నవమాద్‌ భావాదాయురీవం విచిన్త్రయేత్‌ । శూలరాశిదశాయాం వై ప్రవలాయామారిష్టకమ్‌ ॥ 20 ॥",telugu_bhava:"తండ్రి కొరకు 9వ భావము నుండి ఆయుష్షు చింతించవలెను. ప్రబలమైన శూల-రాశి దశలో అరిష్టము (మరణ యోగము) సంభవించును.",english:"From the 9th [from Varṇada], the father's longevity is to be considered. In the strong Śūla-rāśi dasha period, riṣṭa (death-affliction) occurs.",tags:["father-longevity","9th-house","shula-rasi"],verified:"auto"},
        {sl:21,page:7,sanskrit:"ఏవం తన్యాదిభావానాం కర్తవ్యా వర్ణ దశా । పూర్వవచ్చ ఫలం జ్ఞేయం దేహేనాం చ శుభాశుభమ్‌ ॥ 21 ॥",telugu_bhava:"ఈ విధముగా తనుభావాది అన్ని భావములకు వర్ణ దశను నిర్వహించవలెను. పూర్వము చెప్పిన విధముగానే శరీరికుల (ప్రాణుల) శుభాశుభ ఫలములను తెలిసికొనవలెను.",english:"Thus the Varṇa-dasha should be applied to the bhāvas beginning with tanu. The fruits — auspicious and inauspicious for embodied beings — are to be known as before.",tags:["varna-dasha","bhava-fruits"],verified:"auto"},
        {sl:22,page:7,sanskrit:"గ్రహానాం వర్ణదా నైవ రాశీనాం వర్ణా దశా । కృత్వార్క్షదా రాశిదశాం క్రమదన్దరదశాం వదేత్‌ ॥ 22 ॥",telugu_bhava:"గ్రహములకు వర్ణ దశ లేదు — రాశులకు మాత్రమే వర్ణా దశ. ఋక్షదశ (నక్షత్ర దశ) ద్వారా రాశి దశను చేసి, క్రమ అన్తర్దశను చెప్పవలెను.",english:"Varṇa-dasha is not for grahas, only for rāśis. Having computed the Rāśi-dasha through R̥kṣa-dasha (nakṣatra dasha), the antar-dasha is told in sequence.",tags:["rasi-dasha","varna","graha-distinction"],verified:"auto"},
        {sl:23,page:7,sanskrit:"ఏవమన్తర్దశాదిం చ కృత్వా తేన ఫలా వదేత్‌ । క్రమవ్యుత్రమభేదేన లిభేదన్దరదశామపి ॥ 23 ॥",telugu_bhava:"ఈ విధముగా అన్తర్దశాదికమును నిర్వహించి, దాని ద్వారా ఫలములను చెప్పవలెను. క్రమ-వ్యుత్క్రమ భేదముతో అన్తర్దశలను కూడా [గణించవలెను].",english:"Having thus established the antar-dasha etc., predict the fruits accordingly — with direct or reverse [order] for the antar-dasha as well.",tags:["antar-dasha","krama-vyutkrama"],verified:"auto"},
        {sl:24,page:7,sanskrit:"స్వస్వదేశోద్భవం లగ్నం జన్మలగ్నం మిమిహోచ్యతే । భావహోరాదిలగ్నాన్‌ నాం సర్వత్రైవ సమక్రియా ॥ 24 ॥",telugu_bhava:"తమ తమ దేశ-స్థాన ఆధారముగా ఉద్భవించు లగ్నమునే 'జన్మలగ్నము' అని చెప్పబడును. భావ-హోరాది అన్ని విశేష లగ్నములకు కూడా ఇదే విధానము సర్వత్రా వర్తించును.",english:"The lagna arising from one's own locality is called the Janma-lagna. The same procedure applies universally to Bhāva, Hōrā and other special lagnas.",tags:["janma-lagna","local-rising","universal-procedure"],verified:"auto"}
      ]
    },
    6: {
      title_te: "షోడశవర్గాధ్యాయః",
      title_en: "Chapter on the Sixteen Vargas (Divisional Charts)",
      summary_te: "ఈ అధ్యాయము పదహారు వర్గ చక్రములను (షోడశ వర్గములు) వివరించును — క్షేత్ర (D-1 రాశి), హోర (D-2), ద్రేక్కాణ (D-3), చతుర్థాంశ (D-4), సప్తమాంశ (D-7), నవాంశ (D-9), దశాంశ (D-10), ద్వాదశాంశ (D-12 సూర్యాంశ్య), షోడశాంశ (D-16), వింశాంశ (D-20), చతుర్వింశాంశ (D-24 వేదవాహ్యాంశ), భాంశ (D-27 సప్తవింశ), త్రింశాంశ (D-30), ఖవేదాంశ (D-40 ఖపాదాంశ), అక్షవేదాంశ (D-45 ఏకవేదాంశ), షష్ట్యంశ (D-60). ప్రతి వర్గమునకు అధిదేవతలు, గణన పద్ధతి, ఫల వివరణ. బ్రహ్మ లోకపితామహుడిచే చెప్పబడిన పద్ధతి.",
      verses: [
        {sl:1,page:8,sanskrit:"శ్రుతా గ్రహగుణాస్త్వత్తస్తథా రాశిగుణా మునే । శ్రోతుమిచ్ఛామి భావానాం భేదంస్తాన్‌ కృపయా వద ॥ 1 ॥",telugu_bhava:"[మైత్రేయుడు:] ఓ మునీ! మీ నుండి గ్రహ గుణములు, రాశి గుణములు వింటిని. ఇపుడు భావముల భేదములను దయతో చెప్పుడు.",english:"O sage! I have heard from you the qualities of grahas and rāśis. Now I wish to hear the differentiations of the bhāvas — kindly tell me.",tags:["question","bhava-bheda"],verified:"auto"},
        {sl:2,page:8,sanskrit:"వర్గాన్‌ షోడశ యానాహ బ్రహ్మ లోకపితామహః । తానహం సమ్ప్రవక్ష్యామి మైత్రేయ స్రూయతామితి ॥ 2 ॥",telugu_bhava:"[పరాశర:] లోకపితామహుడైన బ్రహ్మదేవుడు 16 వర్గములను చెప్పెను. వాటిని ఇపుడు నేను చెప్పెదను — ఓ మైత్రేయా! వినుము.",english:"Brahmā the world-grandfather declared sixteen vargas. I shall now narrate them — listen, Maitreya.",tags:["sixteen-vargas","brahma","authority"],verified:"auto"},
        {sl:3,page:8,sanskrit:"క్షేత్రం హోరా చ ద్రేక్కాణస్తుర్యాంశః సప్తమాంశకః । నవాంశో దశమాంశశ్చ సూర్యాంశ్యా షోడశాంశకః ॥ 3 ॥",telugu_bhava:"క్షేత్ర (D-1, రాశి), హోర (D-2), ద్రేక్కాణ (D-3), తుర్యాంశ (D-4 / చతుర్థాంశ), సప్తమాంశ (D-7), నవాంశ (D-9), దశమాంశ (D-10), సూర్యాంశ్య (D-12 / ద్వాదశాంశ), షోడశాంశ (D-16) — [ఈ తొమ్మిది వర్గములు].",english:"Kṣetra, Hōrā, Drekkāṇa, Turyāṁśa, Saptamāṁśa, Navāṁśa, Daśamāṁśa, Sūryāṁśya (Dvādaśāṁśa), Ṣoḍaśāṁśa.",tags:["vargas-1-9","D-1","D-2","D-3","D-4","D-7","D-9","D-10","D-12","D-16"],verified:"auto"},
        {sl:4,page:8,sanskrit:"వింశాంశో వేదవాహ్యాంశో భాంశస్త్రింశాంశకస్తథః । ఖపాదాంశోఽఏకవేదాంశః షష్ట్యంశశ్చ తతః పరమ్‌ ॥ 4 ॥",telugu_bhava:"వింశాంశ (D-20), చతుర్వింశాంశ (D-24 / వేదవాహ్యాంశ), భాంశ (D-27 / నక్షత్రాంశ), త్రింశాంశ (D-30), ఖవేదాంశ (D-40 / ఖపాదాంశ), అక్షవేదాంశ (D-45 / ఏకవేదాంశ), షష్ట్యంశ (D-60) — ఇవి తరువాతి వర్గములు.",english:"Vimśāṁśa (D-20), Vedavāhyāṁśa (D-24), Bhāṁśa (D-27), Trimśāṁśa (D-30), Khapadāṁśa (D-40), Ekavedāṁśa (D-45), Ṣaṣṭyāṁśa (D-60) — these subsequently.",tags:["vargas-10-16","D-20","D-24","D-27","D-30","D-40","D-45","D-60"],verified:"auto"},
        {sl:5,page:8,sanskrit:"తత్క్షేత్రం తస్య ఘటస్య రాశీర్యో యస్య నాయకః । సూర్యేన్ద్వోర్ద్విషమే రాశౌ సమే తద్విపరీతకమ్‌ ॥ 5 ॥",telugu_bhava:"క్షేత్రము (D-1) అంటే — ఆ గ్రహము ఏ రాశిలో ఉన్నదో, ఆ రాశి యొక్క నాయకుడు (స్వామి). హోరా (D-2) లో — విషమ రాశులలో సూర్యచంద్రుల హోరలు; సమ రాశులలో దానికి విపరీతము.",english:"The Kṣetra is the rāśi in which a planet is, ruled by its lord. For Hōrā: in odd rāśis, [first half] of Sun, [second] of Moon; in even rāśis, the reverse.",tags:["kshetra-d1","hora-d2","odd-even"],verified:"auto"},
        {sl:6,page:8,sanskrit:"పిత్రశ్చన్ద్రహోరేకా దేవాః సూర్యస్య కీర్తితాః । రాశ్యర్ధం భవేద్ధోరా తాశ్చతుర్యంశతీః స్మృతా । మేషాది తాసాం హోరానాం పరివృత్తిత్రయం భవేత్‌ ॥ 6 ॥",telugu_bhava:"చంద్ర హోర = పితృలది; సూర్య హోర = దేవతలది అని చెప్పబడెను. రాశి యొక్క అర్ధభాగము = ఒక హోర = 15 అంశలు. మేషాది రాశులకు ఈ హోరల పరివృత్తి (చక్రము) మూడు సార్లు తిరుగును.",english:"Candra-hōrā belongs to pitr̥s; Sūrya-hōrā to devas. Half a rāśi is a hōrā — 15 degrees. From Mēṣa onwards, the hōrā cycle revolves three times.",tags:["hora-deities","pitru-deva","cycle"],verified:"auto"},
        {sl:7,page:8,sanskrit:"రాశిత్రిభాగాద్రేక్కాణాశ్చ చ పట్లుకదరితాః । పరివృత్తిత్రయం తేషాం మేషాదే క్రమశో భవేత్‌ ॥ 7 ॥",telugu_bhava:"రాశి యొక్క మూడవ భాగము = ఒక ద్రేక్కాణము (10 అంశలు). మేషాది రాశులకు దీని పరివృత్తి కూడా క్రమముగా మూడు సార్లు తిరుగును.",english:"A third of a rāśi is a Drekkāṇa (10 degrees). From Mēṣa onwards, its cycle also revolves three times in sequence.",tags:["drekkana-d3","third","10-degrees"],verified:"auto"},
        {sl:8,page:8,sanskrit:"స్వపంచనవమానాం చ రాశినాం క్రమశశ్చ తే । నారదాగస్తిదుర్వాసా ద్రేక్కాణేశాశ్చరాదిషు ॥ 8 ॥",telugu_bhava:"ఆ ద్రేక్కాణములు తమ తమ రాశులకు 1, 5, 9 (స్వ-పంచ-నవమ) ద్రేక్కాణములుగా ఉండును. చర-రాశుల ద్రేక్కాణాధిపతులు: నారద, అగస్త్య, దుర్వాస.",english:"They are the 1st, 5th, and 9th drekkāṇas of the rāśis sequentially. The lords of drekkāṇas in movable rāśis are Nārada, Agastya, and Durvāsa.",tags:["drekkana-lords","nāradā","agastya","durvāsa"],verified:"auto"},
        {sl:9,page:8,sanskrit:"స్వర్క్షదికేన్ద్రపతయస్తుర్యాంశేశాః క్రియాదిషు । సనకశ్చ సనన్దశ్చ కుమారశ్చ సనాతనః ॥ 9 ॥",telugu_bhava:"తుర్యాంశ (D-4) లో — స్వ-రాశి అధిపతులు, దిక్‌-అధిపతులు, ఇంద్రాది దేవతలు. అధిపతులు: సనక, సనందన, సనత్కుమార, సనాతన (నాలుగు సనకాది మహర్షులు).",english:"For Turyāṁśa (D-4), the lords are svakṣa-dik-Indra-patis (own-rāśi/direction/Indra). The deities are Sanaka, Sanandana, Sanatkumāra, and Sanātana.",tags:["turyamsa-d4","sanakadi","four-kumaras"],verified:"auto"},
        {sl:10,page:8,sanskrit:"...యుగ్మరాశౌ తు విజ్ఞేయాః సప్తమర్క్షదినాయకాత్‌ ॥ 10 ॥",telugu_bhava:"సప్తమాంశ (D-7) — ఓజ (విషమ) రాశులకు తమ రాశి నుండి ప్రారంభము; యుగ్మ (సమ) రాశులకు ఏడవ రాశి నుండి ప్రారంభముగా తెలిసికొనవలెను.",english:"For Saptamāṁśa (D-7), in even rāśis it should be known as starting from the seventh rāśi.",tags:["saptamsa-d7","odd-even-start"],verified:"auto"},
        {sl:11,page:8,sanskrit:"క్షారక్షీరో చ దధ్యాజ్యే తదేక్షురససమ్బవః । మధ్యశుద్ధజలావోతః సమే శుద్ధజలాదికాః ॥ 11 ॥",telugu_bhava:"సప్తమాంశ తత్త్వములు: క్షార-క్షీర-దధి-ఆజ్య-ఇక్షురస-మధ్య-శుద్ధజలము — విషమ రాశులకు. సమ రాశులకు శుద్ధజలాది [ప్రతిలోమ క్రమములో].",english:"The seven natures: salt, milk, curd, ghee, sugarcane juice, mead, pure water — for odd rāśis. For even rāśis, pure water etc. [in reverse].",tags:["saptamsa-tattvas","seven-elements"],verified:"auto"},
        {sl:12,page:8,sanskrit:"నవాంశేశాశ్చరే తస్మాత్తీరే తస్నుపమాదితః । ఉభయే తత్త్వంశమాదేరితి చిన్త్యం వివక్షణః । దేవా న్యూరక్షసాశ్చైవ చరాదిషు గృహేషు చ ॥ 12 ॥",telugu_bhava:"నవాంశ (D-9) — చర రాశులకు ఆ రాశి నుండే; స్థిర రాశులకు 9వ రాశి నుండి; ద్విస్వభావ రాశులకు 5వ రాశి నుండి (ఉభయే = తత్త్వంశ-ఆది). చర-గృహాలలో దేవ-నర-రాక్షస గణములు.",english:"Navāṁśa (D-9): for movable rāśis from same; for fixed from 9th; for dual from 5th. The cara-houses have deva-nara-rākṣasa categories.",tags:["navamsa-d9","cara-sthira-dvi","deva-nara-rakshasa"],verified:"auto"},
        {sl:13,page:8,sanskrit:"దశమాంశాః స్వతక్షైపే యుగ్మే తన్నవమాత్‌ స్మృతాః । దశ పూర్వాదిదిక్పాలా ఇన్ద్రాద్యగ్నియమర్క్షసాః ॥ 13 ॥",telugu_bhava:"దశమాంశ (D-10) — విషమ రాశులకు తమ రాశి నుండే; యుగ్మ (సమ) రాశులకు 9వ రాశి నుండి. అధిపతులు: 10 దిక్పాలకులు — ఇంద్ర, అగ్ని, యమ, నిర్‌ఋతి [మొదట 4].",english:"Daśamāṁśa (D-10): for odd rāśis from same; for even from the 9th. The lords are the ten dik-pālas (direction-lords): Indra, Agni, Yama, Nirr̥ti [first four].",tags:["dashamsa-d10","ten-dikpalas","indra-agni-yama-nirrti"],verified:"auto"},
        {sl:14,page:8,sanskrit:"వరుణో మారుతశ్చైవ కుబేరేశానపద్మజాః । అనన్తశ్చ క్రమాదీయే సమే వా వ్యుత్రమేణ తు ॥ 14 ॥",telugu_bhava:"[దశమాంశ అధిపతుల కొనసాగింపు:] వరుణ, మారుత (వాయు), కుబేర, ఈశాన, పద్మజ (బ్రహ్మ), అనన్త — ఇట్లు 10 దిక్పాలకులు. సమ రాశులకు వ్యుత్క్రమ క్రమములో.",english:"Varuṇa, Māruta (Vāyu), Kubera, Īśāna, Padmaja (Brahmā), and Ananta — these completing the ten in order; for even rāśis, in reverse.",tags:["dashamsa-lords-continued","varuna-vayu-kubera-isana"],verified:"auto"},
        {sl:15,page:8,sanskrit:"ద్వాదశాంశస్య గణనా తత్తత్క్షత్రాద్విస్థిర్దిశేత్‌ । తేషామధీశః క్రమశో గణేశోఽశ్వియమాహయాః ॥ 15 ॥",telugu_bhava:"ద్వాదశాంశ (D-12) యొక్క గణన — ఆ ఆ రాశి నుండే విస్తరించును. వాని అధిపతులు క్రమములో గణేశ, అశ్వి, యమ, ఆహి (అహి = సర్ప) — [4 దేవతలు].",english:"The Dvādaśāṁśa (D-12) computation extends from each respective rāśi. Their lords in sequence: Gaṇeśa, Aśvi, Yama, Āhi (Ahi/Sarpa).",tags:["dvadasamsa-d12","ganesha","ashwi","yama","ahi"],verified:"auto"},
        {sl:16,page:8,sanskrit:"అజసింహోచ్ఛ్వీతో జ్ఞేయా షోడశాంశశ్చరాదిషు । అజవిష్ణు హార సూర్యే హ్యోజే యుగ్మే ప్రతీపకమ్‌ ॥ 16 ॥",telugu_bhava:"షోడశాంశ (D-16) — చర రాశులలో మేషాది నుండి, స్థిర రాశులలో సింహాది నుండి, ద్విస్వభావ రాశులలో ధనుసాది (ఉచ్ఛ్రాది) నుండి. అధిపతులు ఓజ రాశులలో అజ-విష్ణు-హర-సూర్య; యుగ్మ రాశులలో ప్రతీప (వ్యుత్క్రమ).",english:"Ṣoḍaśāṁśa (D-16): in cara from Mēṣa-Aja, sthira from Siṁha, dvisvabhāva from Dhanus. Lords in odd: Aja, Viṣṇu, Hara, Sūrya; in even: reverse.",tags:["shodashamsa-d16","aja-vishnu-hara-surya"],verified:"auto"},
        {sl:17,page:8,sanskrit:"అథ వింశతిభాగానామధిపా బ్రహ్మణోదితాః । క్రియాచ్చరే స్థిరే దాపాన్‌ మృగుదాత్‌ ద్విస్వభావకే ॥ 17 ॥",telugu_bhava:"వింశాంశ (D-20) యొక్క అధిపతులు బ్రహ్మదేవుని ద్వారా చెప్పబడెను: చర రాశులకు క్రియాది (మేషాది) నుండి, స్థిర రాశులకు దాపుని (ధనుర్‌) నుండి, ద్విస్వభావ రాశులకు మృగుని (మకర) నుండి.",english:"Lords of Vimśāṁśa (D-20) are declared by Brahmā: from Krīya (Mēṣa) for cara; from Dhanu for sthira; from Mr̥ga (Makara) for dvisvabhāva.",tags:["vimshamsa-d20","brahma-declared"],verified:"auto"},
        {sl:18,page:8,sanskrit:"కాలీ గౌరీ లక్ష్మీవిజయా విమలా సతీ । తారా జ్వాలాముఖీ శ్వేతా లలితా బగలాముఖీ ॥ 18 ॥",telugu_bhava:"వింశాంశ దేవతలు (చర రాశులకు): కాళి, గౌరి, లక్ష్మి, విజయ, విమల, సతి, తార, జ్వాలాముఖి, శ్వేత, లలిత — ఇవి 10 దేవీ నామములు.",english:"Vimśāṁśa deities (movable rāśis): Kālī, Gaurī, Lakṣmī, Vijayā, Vimalā, Satī, Tārā, Jvālāmukhī, Śvetā, Lalitā, Bagalāmukhī.",tags:["vimshamsa-deities","mahavidyas"],verified:"auto"},
        {sl:19,page:8,sanskrit:"ప్రత్యజ్‌బైరా శచీ రౌద్రీ భవానీ వరదా జయా । త్రిపురా సుముఖీ చేతి విషమా పరిచిన్త్యయేత్‌ ॥ 19 ॥",telugu_bhava:"[వింశాంశ దేవతలు, చర రాశులకు తరువాతి భాగము:] ప్రత్యంగిర, శచి, రౌద్రి, భవాని, వరద, జయ, త్రిపుర, సుముఖి — ఇవి విషమ (ఓజ) రాశులకు చింతించవలెను.",english:"Pratyaṅgirā, Śacī, Raudrī, Bhavānī, Varadā, Jayā, Tripurā, Sumukhī — these to be considered for odd rāśis.",tags:["vimshamsa-odd-deities"],verified:"auto"},
        {sl:20,page:8,sanskrit:"సమరాశౌ దయా మేధా చిన్న శీర్షా పిశాచినీ । ధూమావతీ చ మాతంగీ బాలా భద్రకరూణానలా ॥ 20 ॥",telugu_bhava:"సమ (యుగ్మ) రాశులకు దేవతలు: దయ, మేధ, ఛిన్నశీర్ష (ఛిన్నమస్త), పిశాచిని, ధూమావతి, మాతంగి, బాల, భద్రకరూణ, అనల, [మరియు మరికొందరు].",english:"For even rāśis: Dayā, Medhā, Chinna-Śīrṣā (Chinnamastā), Piśācinī, Dhūmāvatī, Mātaṅgī, Bālā, Bhadra-karuṇā, Analā.",tags:["vimshamsa-even-deities","mahavidyas"],verified:"auto"},
        {sl:22,page:8,sanskrit:"సిద్ధాంశకానామధిపాః సింహాదేభగే గ్రహా । కర్క్యదుగ్మృభగే ఘేటే స్క్రమే పర్యదరోఽనలాః ॥ 22 ॥",telugu_bhava:"చతుర్వింశాంశ (D-24, సిద్ధాంశ) యొక్క అధిపతులు — సింహాది రాశులలో గ్రహములు, కర్కటకాది రాశులలో [వేరే క్రమములో] అనలాది దేవతలు.",english:"Lords of the Caturvimśāṁśa (D-24, Siddhāṁśa): for the rāśis from Siṁha, the grahas; for the rāśis from Karka [in another sequence], Anala etc.",tags:["chaturvimshamsa-d24","siddhamsha"],verified:"auto"},
        {sl:25,page:8,sanskrit:"అర్యమార్క్యత్వష్టమరుదచ్చగ్నీ మిత్రైవాసవః । నిర్యత్యుదకవిశ్యేఽజాగోనీ విష్ణు వసువేశ్నృపః ॥ 25 ॥",telugu_bhava:"[భాంశ-D27 దేవతలు:] అర్యమ, ఆర్క (సూర్య), త్వష్ట, మరుత్‌, అగ్ని, మిత్ర, ఇంద్ర (వాసవ), నిరృతి, ఉదక (వరుణ), విశ్వే-దేవ, అజ-గోన, విష్ణు, వసు, ఈశ, నృప.",english:"[D-27 lords:] Aryamā, Ārka (Sūrya), Tvaṣṭā, Marut, Agni, Mitra, Vāsava (Indra), Nirr̥ti, Udaka (Varuṇa), Viśvedeva, Aja-Gōṇa, Viṣṇu, Vasu, Īśa, Nr̥pa.",tags:["bhamsha-d27","27-deities","nakshatra-lords"],verified:"auto"},
        {sl:27,page:8,sanskrit:"త్రింశాంశేశాశ్చ విషమే కుజార్క్యజ్ఞజ్ఞభార్గవాః । పంచపంచాష్టసప్తాష్టభాగానాం వ్యత్యయాత్‌ సమే ॥ 27 ॥",telugu_bhava:"త్రింశాంశ (D-30) అధిపతులు విషమ రాశులకు — కుజ, శని, బుధ, గురు, శుక్ర. వాని భాగములు 5-5-8-7-8 అంశలు. సమ రాశులకు దీని వ్యత్యయము (వ్యుత్క్రమము).",english:"Trimśāṁśa (D-30) lords for odd rāśis: Mars, Saturn, Mercury, Jupiter, Venus, with portions 5°-5°-8°-7°-5°. For even rāśis, the reverse order.",tags:["trimshamsa-d30","mars-saturn-mercury-jupiter-venus","unequal-divisions"],verified:"auto"},
        {sl:30,page:8,sanskrit:"విష్ణుశ్చన్ద్రే మరీచిశ్చ త్వష్టా ధాతా శివో రవి । యమో యక్షశ్చ గన్ధర్వః కాలో వరుణ ఏవ చ ॥ 30 ॥",telugu_bhava:"[ఖవేదాంశ-D40 దేవతలు:] విష్ణు, చన్ద్ర, మరీచి, త్వష్ట, ధాత, శివ, రవి, యమ, యక్ష, గన్ధర్వ, కాల, వరుణ.",english:"[Khavedāṁśa D-40 deities:] Viṣṇu, Candra, Marīci, Tvaṣṭā, Dhātā, Śiva, Ravi, Yama, Yakṣa, Gandharva, Kāla, Varuṇa.",tags:["khavedamsa-d40","12-deities"],verified:"auto"},
        {sl:32,page:8,sanskrit:"ఈశాముఖ్యసురజ్యేష్టా విష్ణుకేశాః స్థిరే ద్విభే । దేవాః పంచదశావృత్త్యా విజ్ఞేయా ద్విజసత్తమ ॥ 32 ॥",telugu_bhava:"ఈశాది ముఖ్య సురులు, జ్యేష్ఠ, విష్ణు, కేశ — స్థిర-ద్విస్వభావ రాశులలో. ఓ ద్విజసత్తమా! 15 దేవతలు 3 సార్లు ఆవృత్తి (revolutionary cycle) తో అక్షవేదాంశలో [D-45] తెలిసికొనవలెను.",english:"Īśāmukhya, Sura-jyeṣṭha, Viṣṇu, Keśa — for fixed and dual rāśis. O foremost brāhmaṇa, fifteen deities by three-fold revolution are to be known in [D-45].",tags:["aksavedamsa-d45","15-deities","3-cycles"],verified:"auto"},
        {sl:33,page:8,sanskrit:"రాశీనాం విభజ్యా ఘటస్య ద్విష్ను మంఖజ్ఞ్యమర్క్షహృత్‌ । శేషం సైకం తద్రాశీర్యా షష్ట్యంశకాః స్మృతాః ॥ 33 ॥",telugu_bhava:"గ్రహ యొక్క స్థానమును రాశి విభజన ద్వారా 2 చే గుణించి, 12 తీసివేసి శేష + 1 = ఆ రాశి యొక్క షష్ట్యంశ (D-60). ఇట్లు షష్ట్యంశలు నిర్ణయింపబడును.",english:"Multiply the planet's [position within rāśi] by 2, divide by 12, take remainder + 1 = that rāśi's Ṣaṣṭyāṁśa (D-60).",tags:["shastyamsa-d60","calculation"],verified:"auto"}
      ]
    },
    7: {
      title_te: "వర్గవివేకాధ్యాయః",
      title_en: "Chapter on the Distinction of Vargas (Their Predictive Purpose)",
      summary_te: "ఈ అధ్యాయము పదహారు వర్గ చక్రములలో ప్రతి దానికి ఏమి విషయము చింతించవలెనో వివరించును. లగ్న చక్రము — శరీరము, హోర చక్రము — సంపద, ద్రేక్కాణ — సోదరులు, చతుర్థాంశ — సుఖము, సప్తమాంశ — పుత్ర-పౌత్రాది, నవాంశ — భార్య/భర్త, దశమాంశ — మహత్త్వము/వృత్తి, ద్వాదశాంశ — తల్లిదండ్రులు, షోడశాంశ — వాహన-సుఖ సుఖము, వింశాంశ — ఉపాసన (దేవతా ఆరాధన), చతుర్వింశాంశ — విద్య, భాంశ — బలాబలము, త్రింశాంశ — అరిష్టము, ఖవేదాంశ — శుభాశుభము, అక్షవేదాంశ — సకల ఫలములు, షష్ట్యంశ — సూక్ష్మ ఫలము.",
      verses: [
        {sl:1,page:10,sanskrit:"అథ షోడశవర్గస్య వివేకం చ వదామ్యహమ్‌ । లగ్నే దేహస్య విజ్ఞానం హోరాయాం సమ్పదాదికమ్‌ ॥ 1 ॥",telugu_bhava:"ఇపుడు పదహారు వర్గ చక్రముల వివేకము (ఏ విషయము ఏ చక్రములో పరిశీలించవలెనో) నేను చెప్పెదను. లగ్న చక్రములో దేహ (శరీర) విజ్ఞానము, హోర చక్రములో సంపదాదికము.",english:"Now I declare the discrimination of the sixteen vargas. In the lagna [D-1] is known the body; in Hōrā [D-2], wealth and the like.",tags:["varga-purpose","D1-body","D2-wealth"],verified:"auto"},
        {sl:2,page:10,sanskrit:"ద్రేక్కాణే భ్రాతృజ్ఞానం సౌఖ్యం తుర్యాంశకే భవేత్‌ । పుత్రిప్రౌత్రాదికానాం చై చిన్తనం సప్తమాంశకే ॥ 2 ॥",telugu_bhava:"ద్రేక్కాణ చక్రములో (D-3) సోదరుల జ్ఞానము; తుర్యాంశ (D-4) లో సుఖము; సప్తమాంశ (D-7) లో పుత్ర, పౌత్ర మొదలగువారిని చింతించవలెను.",english:"In Drekkāṇa [D-3], knowledge of brothers; in Turyāṁśa [D-4], happiness; in Saptamāṁśa [D-7], the consideration of children, grandchildren, etc.",tags:["D3-brothers","D4-sukha","D7-progeny"],verified:"auto"},
        {sl:3,page:10,sanskrit:"నవమాంశే కల్త్రాణాం దశమాంశే మహాత్త్వలమ్‌ । ద్వాదశాంశే తథా పిత్రోశ్చిన్తనం షోడశాంశకే ॥ 3 ॥",telugu_bhava:"నవమాంశ (D-9) లో భార్య/భర్త (కల్త్ర) ; దశమాంశ (D-10) లో మహత్త్వము (వృత్తి, ప్రతిష్ఠ) ; ద్వాదశాంశ (D-12) లో తల్లిదండ్రుల చింతనము; షోడశాంశ (D-16) లో [వాహనాది].",english:"In Navāṁśa [D-9], the spouse; in Daśamāṁśa [D-10], greatness/profession; in Dvādaśāṁśa [D-12], the parents; in Ṣoḍaśāṁśa [D-16], [vehicles etc.].",tags:["D9-spouse","D10-profession","D12-parents","D16-vehicles"],verified:"auto"},
        {sl:4,page:10,sanskrit:"సుఖాసుఖస్య విజ్ఞానం వాహనానాం తథైవ చ । ఉపాసనానాం విజ్ఞానం స్యాద్యం వింశతిభాగకే ॥ 4 ॥",telugu_bhava:"షోడశాంశ (D-16) లో సుఖ-అసుఖ విజ్ఞానము, వాహనముల జ్ఞానము; వింశాంశ (D-20) లో ఉపాసన (ఇష్టదేవతా-ఆరాధన) జ్ఞానము.",english:"In [D-16], the knowledge of happiness-sorrow and vehicles likewise; in Vimśāṁśa [D-20], the knowledge of upāsana (deity-worship).",tags:["D16-sukha-vahana","D20-upasana"],verified:"auto"},
        {sl:5,page:10,sanskrit:"విద్యాయా వేదబాహ్యాంశే భాంశే చైవ బలాబలమ్‌ । త్రింశాంశే రిష్టచిన్తా చ ఖవేదే చ శుభాశుభమ్‌ ॥ 5 ॥",telugu_bhava:"చతుర్వింశాంశ (D-24, వేదబాహ్యాంశ) లో విద్య యొక్క విజ్ఞానము; భాంశ (D-27, నక్షత్రాంశ) లో బలాబలము; త్రింశాంశ (D-30) లో అరిష్టము యొక్క చింతన; ఖవేదాంశ (D-40) లో శుభాశుభము.",english:"In Vedabāhyāṁśa [D-24], knowledge of education; in Bhāṁśa [D-27], strength-weakness; in Trimśāṁśa [D-30], affliction-consideration; in Khavedāṁśa [D-40], auspicious-inauspicious.",tags:["D24-education","D27-strength","D30-arishta","D40-shubha-ashubha"],verified:"auto"}
      ]
    },
    8: {
      title_te: "రాశిదృష్టికథనాధ్యాయః",
      title_en: "Chapter on Rāśi Aspects (How Signs Aspect Each Other)",
      summary_te: "ఈ అధ్యాయము మేషాది రాశుల పరస్పర దృష్టిని (అస్పెక్ట్) వివరించును. చర-స్థిర-ద్విస్వభావ రాశుల మధ్య దృష్టి నియమములు: చర రాశులు స్థిర రాశులను చూచును (సమీపమైనది మినహా); స్థిర రాశులు చర రాశులను చూచును; ద్విస్వభావ రాశులు ద్విస్వభావ రాశులను చూచును. దృష్టి విభజన మూడు రకాలు: చతుష్యజాకారం (చతుర్‌-భుజ చదరం) లేదా వృత్తాకారం. దిక్కుల ప్రకారం రాశుల స్థానము: తుల-అలి (పశ్చిమ), మృగ-గుహి (దక్షిణ), ఈశ-కోటే (ఉత్తర), నైరృత్యాది (వాయవ్య).",
      verses: [
        {sl:1,page:12,sanskrit:"అథ మేషాదిరాశీనాం చరాదీనాం పృథక్‌ పృథక్‌ । దృష్టిభేదం ప్రవక్ష్యామి శ్రుణు త్వం ద్విజసత్తమ ॥ 1 ॥",telugu_bhava:"ఇపుడు మేషాది రాశుల (చర-స్థిర-ద్విస్వభావ రాశుల) దృష్టి భేదమును వేరువేరుగా చెప్పెదను. ఓ ద్విజోత్తమా! వినుము.",english:"Now I declare the differences in aspects (dr̥ṣṭi) for the rāśis from Mēṣa onwards — cara, sthira, etc. — separately. Listen, foremost of brāhmaṇas.",tags:["rasi-drishti","aspects-introduction"],verified:"auto"},
        {sl:2,page:12,sanskrit:"రాశ్యోఽవిముఖం విప్ర తథా పశ్యన్తి పార్శ్వభే । యథా చర స్థిరాస్మే స్థిర పశ్యన్తి పై చరాన్‌ ॥ 2 ॥",telugu_bhava:"ఓ విప్రా! రాశులు ముఖాముఖిగా (విముఖము) చూచును, ప్రక్క రాశుల ద్వారా (పార్శ్వము) చూచును. చర రాశులు స్థిర రాశులను చూచును; స్థిర రాశులు చర రాశులను చూచును.",english:"O brāhmaṇa, rāśis aspect 'face-to-face' and side-rāśis. Cara aspects sthira; sthira aspects cara.",tags:["dvistha-aspect","cara-sthira"],verified:"auto"},
        {sl:3,page:12,sanskrit:"ద్విస్వభావో విస్నాత్యానాం ద్విస్వభావాన్‌ ప్రవీక్రియ । సమీపస్యం పరిత్యజ్య భోతస్త్రి గర్‌స్త్రాః ॥ 3 ॥",telugu_bhava:"ద్విస్వభావ రాశులు ద్విస్వభావ రాశులను చూచును (విస్తరించి), కానీ సమీపమైన దానిని విడిచిపెట్టి. — ఇట్లు మూడు విధములుగా దృష్టి జరుగును.",english:"Dual rāśis aspect dual rāśis (extending the view), but excluding the immediately adjacent. Three modes of aspect.",tags:["dvisvabhava","exclude-adjacent"],verified:"auto"},
        {sl:4,page:12,sanskrit:"చరేషు సన్స్థిరాః ఖేటా పశ్యన్తి స్థిరస్థాన్‌ । స్థిరేషు సంస్థిరా ఏవం పశ్యన్తి చరసంస్థాన్‌ ॥ 4 ॥",telugu_bhava:"చర రాశులలో ఉన్న గ్రహములు స్థిర-స్థిత గ్రహములను చూచును. స్థిర రాశులలో ఉన్న గ్రహములు ఇట్లే చర-స్థిత గ్రహములను చూచును.",english:"Planets situated in cara rāśis aspect planets in sthira rāśis; planets in sthira rāśis likewise aspect planets in cara rāśis.",tags:["graha-aspect-rasi","cara-sthira-graha"],verified:"auto"},
        {sl:5,page:12,sanskrit:"ఉభయస్థాస్తు సూర్యాద్యా పశ్యన్త్యుభయసంస్థాన్‌ । నికటస్థం వినా ఖేటా పశ్యన్తీత్యాయమాగమః ॥ 5 ॥",telugu_bhava:"ద్విస్వభావ (ఉభయ) రాశులలో ఉన్న సూర్యాది గ్రహములు ఇతర ద్విస్వభావ రాశులలోని గ్రహములను చూచును — సమీపము నందలి దానిని విడిచి. ఇది శాస్త్ర ఆగమ నియమము.",english:"Planets in dual rāśis aspect those in dual rāśis — excluding the closest. This is the canonical (āgama) rule.",tags:["dvisvabhava-aspect","exclude-nearest"],verified:"auto"},
        {sl:6,page:12,sanskrit:"దృష్టికథమినా పశ్యే యుయాచేద్‌ బుద్ధ్యాగోతమ । తను విస్యునిమవ్యేణ దృష్టిభేః ప్రజ్యాపతే ॥ 6 ॥",telugu_bhava:"దృష్టి కథనమును ఎట్లు తెలుపుకొనవలెనో — ఓ గోతమ! బుద్ధితో చింతించుము. తను-విస్యునిమ-అవ్యయము ద్వారా దృష్టి భేదముల జ్ఞానము — ప్రజాపతి (బ్రహ్మ) చే చెప్పబడెను.",english:"How aspect is to be told — O Gotama, consider with intellect. By tanu-visyunima-avyaya, the differences of aspect are known — declared by Prajāpati.",tags:["drishti-method","brahma-declared"],verified:"auto"},
        {sl:7,page:12,sanskrit:"పాచి విమిషప్యయి లఏస్యో కస్యసింహా తథైతరే । తులాలికి పశ్చిమే విప్రి మృగుగుహిప్యి చ దక్షిణే ॥ 7 ॥",telugu_bhava:"మేషము-సింహము తూర్పు దిక్కు; కన్య-సింహ ఇతర; తుల-వృశ్చిక పశ్చిమ దిక్కు; మకర-గుహ్య (కుంభ) దక్షిణ దిక్కు.",english:"Mēṣa-Siṁha eastern; Kanyā-Siṁha and others; Tulā-Vr̥ścika western; Makara-Kumbha southern.",tags:["rasi-directions"],verified:"auto"},
        {sl:8,page:12,sanskrit:"ఈశకోటే తు మిరుసన వాయుహ్యి కస్యకాన్‌ తథా । నైరుత్క్యాదారిమాలిభ్యి మ్బోగ్రోకే యథా లిజేత్‌ ॥ 8 ॥",telugu_bhava:"ఈశాన (ఉత్తర-తూర్పు) దిక్కులో మిథున-కర్క; వాయవ్య (ఉత్తర-పశ్చిమ) దిక్కులో కన్య; నైరృత్య (దక్షిణ-పశ్చిమ) దిక్కులో అలి-మాలి (వృశ్చిక-తుల).",english:"Mithuna-Karka in īśāna (NE); Kanyā in vāyavya (NW); Vr̥ścika-Tulā in nairr̥tya (SW).",tags:["rasi-corner-directions"],verified:"auto"},
        {sl:9,page:12,sanskrit:"ఏవం చరుక్యుజాకారం వృత్తాకారయథాపి వా । దృష్టివక్షం ప్రవిన్తేస్యం తోతే దృష్టిం విదారయేత్‌ ॥ 9 ॥",telugu_bhava:"ఈ విధముగా చతుర్భుజాకారము లేదా వృత్తాకారము ద్వారా దృష్టిని వ్యక్తపరుస్తూ — దృష్టి విభజన చేయవలెను.",english:"Thus by quadrangular shape or by circular shape, the aspects are to be diagrammed and the aspect-distinctions made.",tags:["aspect-diagram","quadrangle-circle"],verified:"auto"}
      ]
    },
    9: {
      title_te: "అరిష్టాధ్యాయః",
      title_en: "Chapter on Riṣṭas (Afflictions, Bālāriṣṭa — Child Mortality)",
      summary_te: "ఈ అధ్యాయము జాతకుని చిన్నతనములో సంభవించు అరిష్టములను (బాలారిష్టము = 8 సంవత్సరములు లోపు మరణ యోగములు) వివరించును. క్షీణ చంద్ర, పాప గ్రహముల కేంద్ర-త్రికోణ స్థితి, లగ్నమునకు పాప దృష్టి, చంద్ర-రాహు యుతి మొదలగు కారణములు. యోగారిష్టము (యోగము ద్వారా అరిష్టము) , బాలారిష్టము (8 ఏళ్లలోపు), యోగపరిహారము (అరిష్టము భంగమగు యోగములు) వివరించబడెను. యోగాలు: కేమద్రుమ, శకట, వేశి, అనపా, శుభ-యుతి సహా అనేకము.",
      verses: [
        {sl:1,page:13,sanskrit:"అథ ఆయుర్భేదే విప్ర దృష్టిభేదం విచారయేత్‌ । శతాయుర్మానవానాహుర్జాతవేదాః చతుః సంహి ॥ 1 ॥",telugu_bhava:"ఓ విప్రా! ఇపుడు ఆయుష్షు భేదమును, దృష్టి భేదమును పరిశీలించవలెను. మనుజులకు 100 సంవత్సరములు ఆయుర్దాయము అని చెప్పబడెను. (అది 4 భాగములుగా: బాలారిష్ట [8 ఏళ్లు], యోగారిష్ట [20 ఏళ్లు], అల్పాయు [32], మధ్యాయు [70], పూర్ణాయు [100]).",english:"O brāhmaṇa! Now consider the differentiation of longevity and of aspects. The wise declare 100 years as the human life-span — divided into [bālāriṣṭa, yogāriṣṭa, alpa-, madhya-, pūrṇa-āyu].",tags:["ayur-bheda","100-years","life-stages"],verified:"auto"},
        {sl:2,page:13,sanskrit:"అష్టాబ్దంతు భవేద్‌ బాలం బ్యోగ్యరిష్టమతః పరమ్‌ । అల్పమధ్యం పూర్ణం స్యాత్‌ ద్విగుణం ప్రోక్తదర్షణాత్‌ ॥ 2 ॥",telugu_bhava:"8 సంవత్సరములు బాలారిష్ట (బాల్య దశ) అని, దాని తరువాత యోగారిష్ట [20 ఏళ్ల వరకు]. అల్పాయు, మధ్యాయు, పూర్ణాయు అను మూడు దశలు — క్రమముగా [32, 70, 100 ఏళ్లు] — ద్విగుణితముగా చెప్పబడెను.",english:"Up to 8 years is bāla [-āriṣṭa]; thereafter yogāriṣṭa [up to 20]. Alpa, madhya, and pūrṇa āyu are then progressively double-fold (32, 70, 100).",tags:["balarishta","yogarishta","life-divisions"],verified:"auto"},
        {sl:3,page:13,sanskrit:"జాతః సన్‌ ద్యూక్యత స్యాత్‌ తపోజయం నిబన్ధదాత్త్యగా । స్థితో ద్యూక్యత స్యాత్‌ ముఖదాసప్తపరో శిశుః ॥ 3 ॥",telugu_bhava:"పుట్టగానే మరణించెడి శిశువు (జాతఃసన్) ఆ పూర్వ-తపో-బంధ ఫలమునే అనుభవించును. స్థితిగా ముఖదశ-సప్త-రోగములతో శిశువు మరణించును.",english:"A child who dies at birth experiences the fruits of past tapas-bondage. By position, the infant succumbs to mukha-rōga and seven [other afflictions].",tags:["birth-death","past-karma","infant-diseases"],verified:"auto"}
      ]
    },
    10: {
      title_te: "అరిష్టభంగాధ్యాయః",
      title_en: "Chapter on the Cancellation of Riṣṭas",
      summary_te: "ఈ అధ్యాయము పూర్వము చెప్పబడిన అరిష్ట (బాలారిష్ట) ఎట్లు భంగమగును (cancelled) అని వివరించును. గురు, శుక్ర, బుధ — ఈ శుభ గ్రహములలో ఒక్కరు కూడా కేంద్రములో (1, 4, 7, 10) ఉన్నచో అరిష్టము పూర్తిగా నశించును (సూర్యుడు చీకటిని హరించునట్లు). బలవంతుడైన బృహస్పతి (గురు) లగ్నములో ఉండుట, శుక్రుని కేంద్ర స్థితి, వృషభములో సూర్యచంద్రులు ఉండుట, గురుడు కేంద్రములో ఉన్నచో దీర్ఘాయువు, ఇత్యాది యోగములు అరిష్ట భంగమునకు హేతువులు. దీర్ఘాయువు యోగములు: 4 కేంద్రములలో శుభ గ్రహములు, పాపులు సౌమ్యుల మధ్యనుండి తొలగించబడుట.",
      verses: [
        {sl:1,page:15,sanskrit:"ఇత్యరిష్టం మయా ప్రోక్తం తద్యథ్యక్క్యావది కథ్యతే । యత్ర సమాలోక్యం బారాతాం రిష్టోరిష్టం ఖద్దుదః ॥ 1 ॥",telugu_bhava:"ఈ విధముగా అరిష్టము నేను చెప్పితిని. ఇపుడు అది ఎచ్చట (ఏ యోగములతో) భంగమగునో చెప్పెదను. బాధితునిని పరిశీలించి అరిష్టము-అరిష్టభంగమును [నిర్ధారించవలెను].",english:"Thus is riṣṭa declared by me. Now its cancellation is spoken of. Examining the [chart], one must determine where the affliction does or does not befall.",tags:["arishta-bhanga","cancellation"],verified:"auto"},
        {sl:2,page:15,sanskrit:"ఏకోఽపి జ్యార్యకిత్రాణాం లగ్నాత్‌ కేన్ద్రగో యది । అరిష్టం నిఖిలం హన్తి తిమిరం భాస్కరో యథా ॥ 2 ॥",telugu_bhava:"గురు, శుక్ర, బుధ — ఈ ముగ్గురిలో ఒక్కడు కూడా లగ్నము నుండి కేంద్ర (1, 4, 7, 10) స్థానములో ఉన్నచో — సూర్యుడు చీకటిని నశింపజేయునట్లుగా — సకల అరిష్టమును పూర్తిగా నశింపజేయును.",english:"If even one of Jīva (Jupiter), Bhārgava (Venus), or Mercury is in a kendra from the lagna, it destroys all riṣṭa as the Sun [destroys] darkness.",tags:["benefic-kendra","arishta-cancellation","jupiter-venus-mercury"],verified:"auto"},
        {sl:3,page:15,sanskrit:"ఏక ఏవ బలీ జీవే లగ్నస్థో దివ్యనందాయమమ్‌ । పాపి పాంచకం భక్త్యా ప్రజాను ఇవ హారిణః ॥ 3 ॥",telugu_bhava:"బలవంతుడైన బృహస్పతి ఒక్కడే లగ్నములో ఉన్నచో — దివ్యానందము, దీర్ఘాయుష్షు. పాప గ్రహముల పంచకమును భక్తితో — హరిణి తన ప్రజలను రక్షించునట్లు — తొలగించును.",english:"Strong Jupiter alone in the lagna grants divine bliss [and longevity]; it removes the five malefics' [evil] just as a doe protects her young.",tags:["jupiter-lagna","strong-jupiter","arishta-removal"],verified:"auto"},
        {sl:4,page:15,sanskrit:"ఏక ఏవ విలగ్నేఽశ్‌ కేన్ద్రసంస్థో అలబ్ధ్యకః । అరిష్టం నిఖిలం హన్తి పిచారీ త్రిమ్బరం యథా ॥ 4 ॥",telugu_bhava:"లగ్నాధిపతి ఒక్కడే కేంద్రములో అలబ్ధ్య (బాధ లేకుండా) స్థితిలో ఉన్నచో — త్రిమ్బరమును పిచారి తొలగించునట్లు — సకల అరిష్టమును నశింపజేయును.",english:"The lagneśa alone, kendra-stationed and unafflicted, removes all riṣṭa as a wraith dispels obstacles.",tags:["lagna-lord-kendra","afflictionless","arishta-bhanga"],verified:"auto"},
        {sl:5,page:15,sanskrit:"కుజపతి షా పాపిష్ణు లగ్నీ సౌమ్యానిరీక్షితే । విపరీతం కృష్ణపే తరాగదినాశం ॥ 5 ॥",telugu_bhava:"కుజ-అధిపతి (లగ్నలో), పాపిష్టమైన — సౌమ్య (బుధ) దృష్టి లేకుండా ఉన్నచో — విపరీతముగా (అశుభ ఫలము); కృష్ణ పక్షములో [జన్మించిన] శిశువుకు తీవ్ర రోగములు, మరణ నాశము.",english:"If the Kuja-pati (?) afflicts the lagna without saumya (Mercury) aspect, the result is reverse; in kr̥ṣṇa-pakṣa [birth], severe disease and death-affliction.",tags:["mars-affliction","krishna-paksha-birth","negative-result"],verified:"auto"},
        {sl:6,page:15,sanskrit:"వృషస్థాని యదా సూర్యచన్ద్రాలగ్నీ తు జాయతే । జీవే సి కేంద్రగాని దీర్ఘాయుర్లగ్నే భవేత్‌ ॥ 6 ॥",telugu_bhava:"వృషభములో సూర్య-చంద్రులు, లగ్నము కూడా [వృషభము] అయిన జన్మ సమయములో — గురువు కేంద్రములో ఉన్నచో — లగ్నములో దీర్ఘాయువు సిద్ధించును.",english:"When Sun and Moon are in Vr̥ṣabha [Taurus] and the lagna is [there too], with Jupiter in kendra — long life accrues from the lagna.",tags:["vrishabha-yoga","sun-moon-jupiter","longevity"],verified:"auto"}
      ]
    },
    11: {
      title_te: "భావవివేకాధ్యాయః",
      title_en: "Chapter on the Distinction of Bhāvas (12 Houses)",
      summary_te: "ఈ అధ్యాయము ద్వాదశ భావముల వేర్వేరు అర్థములను, వాని ద్వారా చింతించవలసిన విషయములను వివరించును. తనుర్‌ (1) — శరీరము-రూపము-బలం; ధనం (2) — ధనం-కుటుంబం; సహజ (3) — సోదరులు-ధైర్యం; సుఖ (4) — తల్లి-గృహ-వాహన; పుత్ర (5) — సంతానం-విద్య; శత్రు (6) — శత్రువులు-రోగములు; కల్త్ర (7) — భార్య/భర్త-భాగస్వామ్యం; ఆయు (8) — ఆయుష్షు-మరణ హేతువులు; భాగ్య (9) — తండ్రి-అదృష్టం-ధర్మం; కర్మ (10) — వృత్తి-కీర్తి; లాభ (11) — ఆదాయం; వ్యయ (12) — వ్యయం-నష్టం. ఆలోచనా క్రమములు, తాత్కాలిక-చిరకాలిక ఫలముల వివరణ.",
      verses: [
        {sl:1,page:16,sanskrit:"అరిష్టం తథ్యక్తలం చ శ్రుతం త్వార్యా మయా మునీ । కస్మిన్‌ భావాత్‌ బలాత్‌ కిం కిం విధార్యమినీ మే వద ॥ 1 ॥",telugu_bhava:"[మైత్రేయుడు:] అరిష్టము, దాని భంగము నేను మీ నుండి వింటిని ఓ మునీ. ఇపుడు ఏ భావము యొక్క బలము ద్వారా ఏ ఏ విషయములను తెలిసికొనవలెనో నాకు చెప్పుడు.",english:"Riṣṭa and its cancellation I have heard from you, O sage. Now tell me from the strength of which bhāva, what is to be considered.",tags:["question","bhava-meaning","strength"],verified:"auto"},
        {sl:2,page:16,sanskrit:"దేహం రూపం చ జ్ఞానం చ వర్ణం చైవ బలాబలమ్‌ । సుఖం దుఃఖం స్యభావాశ్చ లగ్నభావాన్నిరీక్షయేత్‌ ॥ 2 ॥",telugu_bhava:"దేహము, రూపము, జ్ఞానము, వర్ణము, బలాబలము, సుఖము, దుఃఖము, స్వభావము — ఇవి అన్నీ లగ్న భావము (1వ భావము) నుండి పరిశీలించవలెను.",english:"Body, form, knowledge, complexion, strength-weakness, happiness, sorrow, nature — all these are to be examined from the lagna-bhāva.",tags:["lagna-bhava-meanings","D1-significations"],verified:"auto"},
        {sl:3,page:16,sanskrit:"ధనధాన్యం కుటుమ్బాత్త్యై మృత్యుర్యత్రామిత్రకుః । చార్యాత్యానేకం సర్వం ధనస్థానా చ్చిన్త్రయేత్‌ ॥ 3 ॥",telugu_bhava:"ధనము, ధాన్యము, కుటుంబము, మృత్యువు (మరణ హేతువులు), అమిత్రులు (శత్రువులు), చార్యత్యానేకం (ఇంకా అనేక విషయములు) — అన్ని ధన స్థానము (2వ భావము) నుండి చింతించవలెను.",english:"Wealth, grain, family, [secondary] cause of death, enemies, and many other things — all from the dhana-sthāna (2nd house) are to be considered.",tags:["dhana-bhava","2nd-house","family-wealth"],verified:"auto"},
        {sl:4,page:16,sanskrit:"విక్రమో మరణ విష్ణు దుశ్చ్యక్యాత్‌ నీరేక్షయేత్‌ । వాహానాన్యచ్చ బన్ధాంశ్చ మాతృతః సౌఖ్యం స్యాత్‌ తృగాన్‌ ॥ 4 ॥",telugu_bhava:"పరాక్రమము, మరణ హేతువులు, బంధువులతో సంబంధము — ఇవి దుశ్చ్యక్య (3వ భావము) నుండి పరిశీలించవలెను. వాహనములు, బంధువులు, మాతృ సుఖము — ఇవి చతుర్ధ (4వ) నుండి [చింతించవలెను].",english:"Valor, manner of death, [siblings], from duścikya (3rd) — to be examined. Vehicles, relatives, mother's happiness — from the 4th.",tags:["3rd-house","valor","4th-house","mother-vehicles"],verified:"auto"},
        {sl:5,page:16,sanskrit:"నిధి క్షేత్ర గృహాన్‌ చాపి చతుర్థాత్‌ పరిచిన్తయేత్‌ । యుత్రామృత్యా తథా విద్యా బుద్ధిశ్చ ధ్వజదాదికమ్‌ ॥ 5 ॥",telugu_bhava:"నిధి, క్షేత్రములు (భూములు), గృహములు — అన్నీ చతుర్ధ (4వ) నుండి చింతించవలెను. యుక్తి-అమృత తో కూడిన విద్య, బుద్ధి, ధ్వజ-రాజచిహ్నాదికము [5వ నుండి].",english:"Treasures, fields, houses — all from the 4th. Knowledge full of yukti and amr̥ta, intellect, [royal] insignia — [from the 5th].",tags:["4th-house","property","5th-house","intellect"],verified:"auto"},
        {sl:6,page:16,sanskrit:"పుత్రమన్త్రాధికారాదీన్‌ పశ్చమే పుత్రభేయుత్‌ । మామకర్తృశక్తికారాణాం శత్రుభ్యశ్చ ప్రజావసేత్‌ ॥ 6 ॥",telugu_bhava:"పుత్రులు, మంత్ర, అధికారము — మొదలగు విషయములు పంచమ (5వ) భావము — పుత్ర భావము — నుండి. మాతృకర్త శక్తి కారణములు, శత్రువుల నుండి [కలుగు] ప్రజాధనము — [6వ నుండి].",english:"Children, mantras, authority — and the like, from the 5th [house of progeny]. The causes of mother's strength, and prosperity from enemies — [from the 6th].",tags:["5th-house","children-mantra","6th-house"],verified:"auto"}
      ]
    },
    12: {
      title_te: "తనుభావఫలాధ్యాయః",
      title_en: "Chapter on the Fruits of the Tanu-Bhāva (1st House)",
      summary_te: "ఈ అధ్యాయము లగ్న భావము (తనుర్‌, శరీర భావము) యొక్క ఫలములను వివరించును. లగ్నాధిపతి స్థానము, పాప-సౌమ్య గ్రహముల ప్రభావము, దృష్టులు — శరీర ఆరోగ్యం, రూపం, స్వభావం, దీర్ఘాయుష్షు, ముఖ లక్షణములు, వ్యాధులు — అన్నీ వీటి నుండి తెలిసికొనబడును. లగ్నములో పాప గ్రహముల వలన దోషములు; శుభ గ్రహముల వలన సుఖ ఫలములు. లగ్నేశుని కేంద్ర-కోణ స్థితి, బలం, దృష్టి — ఈ అన్నీ ముఖ్యమైన ఫల-కారణములు.",
      verses: [
        {sl:1,page:17,sanskrit:"సపాపో దేహచేష్టార్యంయుగే దేహాత్మశుహ్వాత్‌ । కష్టే కో పే స్థితో పజే సదా దేహాముఖం దిశేత్‌ ॥ 1 ॥",telugu_bhava:"పాప గ్రహముతో కూడిన లగ్నము — దేహ చేష్ట లోపం, దేహాత్మ సుఖ హ్రాస కారణము. కష్ట, కోప (క్రోధ) స్థితిలో ఉన్న వాడు ఎల్లప్పుడూ దేహ-ముఖ సంబంధ అశుభ ఫలములను సూచించును.",english:"Lagna with malefics — defects in body-action, loss of body's natural happiness. He whose lagna is in distress and anger always indicates body and face afflictions.",tags:["lagna-malefics","body-affliction"],verified:"auto"},
        {sl:2,page:17,sanskrit:"లగ్నేతిచ్చుపతిత్‌ నీచే శత్రుపే రోగదః భవేత్‌ । కుజః కేన్ద్రకోణాస్త సర్వగోచారః స్నుక్తాః ॥ 2 ॥",telugu_bhava:"లగ్నాధిపతి నీచ రాశిలో, శత్రు రాశిలో — రోగప్రదుడు. కుజుడు కేంద్ర-త్రికోణ స్థానములలో సర్వ గోచారము (సర్వ ఫలప్రదుడు) అని చెప్పబడెను.",english:"The lagneśa in debilitation or enemy-rāśi causes diseases. Kuja (Mars) in kendra-trikoṇa is said to be all-influencing.",tags:["lagna-lord-weak","mars-kendra"],verified:"auto"},
        {sl:3,page:17,sanskrit:"లగ్నే చన్ద్రమదః కూరగ్రహైర్దృష్టోద్యా యుతే । కుజదృష్టివవీసే చ జన్ప్యోర్యగుసు మహి ॥ 3 ॥",telugu_bhava:"లగ్నములో చంద్రుడు క్రూర గ్రహముల దృష్టి/యుతి తో ఉన్నచో — కుజ దృష్టి కూడా ఉన్నచో — అత్యంత అరిష్టము.",english:"Moon in lagna with malefic aspect/conjunction, plus Mars's aspect — gravely afflicting at birth.",tags:["moon-lagna","malefic-conjunction","mars-aspect"],verified:"auto"},
        {sl:4,page:17,sanskrit:"లగ్నే సౌమ్యా సురాయా స్యాద్‌ క్రూరరూపదేహవిగ్రేతః । సౌమ్యభేదుర్యకే దృష్టే లగ్నీ దేహాసుబాన్యికః ॥ 4 ॥",telugu_bhava:"లగ్నములో సౌమ్య (బెనెఫిక్) గ్రహ — క్రూర-రూప-దేహ-విగ్రహమును హరించును. సౌమ్య దృష్టి ఉన్న లగ్న జాతకుడు — దేహ-సుఖ సంపన్నుడు.",english:"Saumya (benefic) in lagna removes cruel form and bodily distress. With saumya aspect, the lagna-jātaka enjoys body-happiness.",tags:["benefic-lagna","body-happiness"],verified:"auto"},
        {sl:5,page:17,sanskrit:"లగ్నేశ జ్యా గురుర్యశ్చ్మిప్తి కతేంద్ర చ కేన్ద్రకీయాః । దీర్ఘాయుర్యదవాన్‌ జాతః బుద్ధిమాన్‌ రాజవల్లభః ॥ 5 ॥",telugu_bhava:"లగ్నేశుడు, బృహస్పతి, బుధ — కేంద్రములు, త్రికోణములలో ఉన్నచో — జాతకుడు దీర్ఘాయుష్షు, సంపదవంతుడు, బుద్ధిమంతుడు, రాజవల్లభుడు అగును.",english:"When the lagneśa, Jupiter, and Mercury are in kendras and trikoṇas — the native is long-lived, wealthy, intelligent, and a king's favorite.",tags:["lagna-lord-jupiter-mercury","kendra-trikona","raja-yoga"],verified:"auto"},
        {sl:6,page:17,sanskrit:"లగ్నే శి చరారిష్టే శుభగ్రహనిరీక్షితే । కరిష్యమాన్‌ మహాతేగీ దేహసాయనమినితః ॥ 6 ॥",telugu_bhava:"లగ్నేశుడు చర-అరిష్ట (చల-రాశి-బాధ) లో ఉన్నను శుభ గ్రహముల దృష్టి ఉన్నచో — జాతకుడు కార్యశీలి, మహాతేజస్వి, దేహ సాయన మినితుడు.",english:"Even if the lagneśa is in cara-affliction, with benefic aspect — the native is industrious, mighty, and bodily resilient.",tags:["lagna-lord-aspected","industriousness"],verified:"auto"}
      ]
    },
    13: {
      title_te: "ధనభావఫలాధ్యాయః",
      title_en: "Chapter on the Fruits of the Dhana-Bhāva (2nd House — Wealth)",
      summary_te: "ఈ అధ్యాయము ద్వితీయ భావము (ధన భావము) ఫలములను వివరించును. ధనేశుడు, ధనాధిపతి యొక్క స్థానము, కేంద్ర-త్రికోణ యోగము, శుభ-పాప గ్రహముల ప్రభావము — ధన లాభము/నష్టము నిర్ణయించును. గురు-శుక్రుల ధనేశ స్థానము ఉన్నచో మహా ధన యోగము. పాప గ్రహముల ధన భావ సంయోగము ధన నాశనమునకు హేతువు. కుటుంబ సంపద, వాక్చాతుర్యము, ఆహార-భోజన సుఖము కూడా ఈ భావము ద్వారానే.",
      verses: [
        {sl:1,page:18,sanskrit:"ధనభావఫలం వచ్మి స్నుణు త్వం ద్విజసత్తమ । ధనేశే ధనభావస్థే క్షస్త్రీగోకోపి వా ॥ 1 ॥",telugu_bhava:"ఓ ద్విజోత్తమా! ధన భావ ఫలమును ఇపుడు చెప్పెదను, వినుము. ధనేశుడు ధన భావమునందే ఉన్నను, క్షత్రియ-గో [స్థానములలో] ఉన్నను [మంచి ఫలము].",english:"O foremost brāhmaṇa, I declare the fruits of the dhana-bhāva — listen. The dhaneśa in the dhana-bhāva, or in kṣatriya-go positions [yields good fruit].",tags:["dhana-bhava","2nd-house","dhanesha"],verified:"auto"},
        {sl:2,page:18,sanskrit:"ధనవృద్ధికరో జ్ఞేయస్త్రయేకత్థో ధనసంపన్నః । ధనస్థ్యే ధనే సౌమ్యే పాపే ధనవినాకృత్‌ ॥ 2 ॥",telugu_bhava:"[ధనేశుడు ఇతర యోగములలో] ధన వృద్ధికరుడు అని తెలిసికొనవలెను; జాతకుడు ధన సంపన్నుడగును. ధన భావములో సౌమ్య గ్రహముతో [మంచి ఫలము], పాప గ్రహముతో ధన వినాశనము.",english:"[The dhaneśa otherwise] is known to cause wealth-growth — the native becomes wealthy. With saumya in dhana, [good]; with pāpa, wealth-destruction.",tags:["wealth-growth","saumya-papa-effect"],verified:"auto"},
        {sl:3,page:18,sanskrit:"ధనాదిపో గురుర్యస్య ధనభావగతో భవేత్‌ । భౌమేన సహితో వాపి దృశ్యోన స నరో భవేత్‌ ॥ 3 ॥",telugu_bhava:"ధనాధిపతియైన గురువు ధన భావములో ఉన్నచో — లేదా కుజునితో కలిసిన/దృష్టిలో ఉన్నచో — ఆ జాతకుడు [ధనవంతుడు] అగును.",english:"When Jupiter, the dhana-lord, is in the dhana-bhāva — or conjoined with/aspected by Mars — that man becomes [wealthy].",tags:["jupiter-2nd-house","mars-yuti"],verified:"auto"},
        {sl:4,page:18,sanskrit:"ధనేశ లాభభావస్థో లాభేశ ధ్యధ్‌గతి । తావుభౌ కేన్ద్రకోణస్థో దంచితదః వా నరో భవేత్‌ ॥ 4 ॥",telugu_bhava:"ధనేశుడు లాభ భావములో, లాభేశుడు ధన భావములో — వీరిద్దరూ కేంద్రములో-కోణములో ఉన్నచో — జాతకుడు ధన సంచితుడు, ధనవంతుడగును.",english:"Dhaneśa in 11th, lābheśa in 2nd — both in kendra-koṇa — the native accumulates wealth.",tags:["2nd-11th-exchange","wealth-yoga"],verified:"auto"},
        {sl:5,page:18,sanskrit:"ధనేశ కేన్ద్రకోష్ణ్థే లాభేశ ఐత్రికోన్నతః । గురుశుక్రయుతౌ దృష్టే ధనలాభమురీయేత్‌ ॥ 5 ॥",telugu_bhava:"ధనేశుడు కేంద్రములో-త్రికోణములో, లాభేశుడు త్రికోణ స్థానములో, గురు-శుక్రుల యుతి/దృష్టి ఉన్నచో — మహా ధన లాభము.",english:"Dhaneśa in kendra-trikoṇa, lābheśa in trikoṇa, with conjunction-aspect of Jupiter and Venus — great wealth-gain.",tags:["dhana-yoga","jupiter-venus","kendra-trikona"],verified:"auto"},
        {sl:6,page:18,sanskrit:"ధనేశే రిపుభావస్థో లాభేశ్చభద్రతే యది । ధనయో పాయయో దా రుఖ నిరాస ఏవ సః ॥ 6 ॥",telugu_bhava:"ధనేశుడు రిపు భావములో (6వ), లాభేశుడు [అశుభ స్థితిలో] ఉన్నచో — ధన-పాయములో (నష్టములో) జాతకుడు ఉంటాడు, లేదా అంత ధన నిరాకరణ.",english:"If the dhaneśa is in the ripu-bhāva (6th) and the lābheśa [unfavorable] — the native faces wealth-loss or wealth-rejection.",tags:["6th-house-dhana","wealth-loss"],verified:"auto"}
      ]
    },
    14: {
      title_te: "సహజభావఫలాధ్యాయః",
      title_en: "Chapter on the Fruits of the Sahaja-Bhāva (3rd House — Brothers)",
      summary_te: "ఈ అధ్యాయము సహజ భావము (3వ భావము — సోదరులు, ధైర్యము, స్వీయ ప్రయత్నము) యొక్క ఫలములను వివరించును. సహజేశుడి స్థానము, గురు-కుజుల ప్రభావము సోదరుల సంఖ్య, వారి సుఖము, పరస్పర సంబంధము నిర్ధారించును. క్రూర గ్రహ సహజ భావ స్థితి సోదర నాశమునకు హేతువు. శుభ గ్రహ ప్రభావము సోదర సుఖము, పరాక్రమము, ఉత్తమ స్నేహితులను ఇచ్చును.",
      verses: [
        {sl:1,page:19,sanskrit:"అథ విప్రవచ్మ్యద్య బలం భ్రాతృభావస్య ద్విజ । సహజే సౌమ్యయుయుక్తే భ్రాతృభిర్దృపితో నరః ॥ 1 ॥",telugu_bhava:"ఓ విప్రా! ఇపుడు సోదర భావ (3వ భావ) బలమును చెప్పెదను. సహజ భావములో సౌమ్య గ్రహ యుతి ఉన్నచో — జాతకుడు సోదరులతో పోషింపబడును (సోదరుల సుఖము పొందును).",english:"O brāhmaṇa! Now I declare the strength of the brātr̥-bhāva. Sahaja with saumya (benefic) — the native is nourished by his brothers.",tags:["3rd-house","brothers","sahaja-bhava"],verified:"auto"},
        {sl:2,page:19,sanskrit:"సహజే భ్రాతృపతౌ చ భ్రాతృభావస్య పశ్యతి । భ్రాతృగోత్రమర్‌ వాచో భ్రాతృభావం ప్రభుః ॥ 2 ॥",telugu_bhava:"సహజేశుడు సహజ భావమునే చూచుచున్నచో — సోదర వంశ-గోత్ర వృద్ధి, భ్రాతృ-సుఖము ప్రభుత్వము కల్గును.",english:"When the sahaja-lord aspects the sahaja-bhāva — there is increase of brother-clan-lineage, lordship of fraternal happiness.",tags:["sahaja-lord","aspect","brother-prosperity"],verified:"auto"},
        {sl:3,page:19,sanskrit:"ఆర్యశ్చ సహజాన్త్‌ సర్వో నీచగో న సంశయః । స్త్రీణాం భ్రాతృపతిః స్త్రీణాం భ్రాతృభావః ॥ 3 ॥",telugu_bhava:"జ్యేష్ఠ సోదరుడు సహజాంత్‌ (3వ భావములో) ఉన్నచో — నీచగతి (నీచ స్థితి) లో ఉండడు సందేహము లేదు. స్త్రీలకు భ్రాతృపతి (3వ-అధిపతి) స్త్రీ సోదరులతో సంబంధము.",english:"The eldest brother in the sahaja-end is undoubtedly not in lowly state. For women, the sahaja-lord [signifies female brothers].",tags:["eldest-brother","female-natives"],verified:"auto"},
        {sl:4,page:19,sanskrit:"భ్రాతోః స్త్రియా తథా బ్రాతా ధృత్యధికం స్కుణ్యౌ యది । మణి మిత్రులాం చార్క్యై బలాబలచిన్తాయిమి ॥ 4 ॥",telugu_bhava:"సోదరి-సోదరుల ధైర్యము-అధికత్వము గుర్తించబడును. గురు-శుక్రుల బలాబల చింతనతో [నిర్ధారింపవలెను].",english:"The strength-superiority of brothers-sisters is recognized; through Jupiter-Venus strength-weakness consideration.",tags:["sibling-strength","jupiter-venus"],verified:"auto"},
        {sl:5,page:19,sanskrit:"మంత్రే కూరగ్రహేయుర్‌ సహజేడిరికే ద్విజ । స్త్రుపోర్నోన వాచో ద్రోర్యమ్యధ్రుత్సర్థి యత్‌ ॥ 5 ॥",telugu_bhava:"క్రూర గ్రహ-యుతి సహజేడిరికే (3వ-6వ-11వ) లో ద్విజా! — సోదర నష్టము, వ్యర్థ ఆలోచనలు, ద్రోహ పరిత్యాగము.",english:"With malefic conjunction in 3rd-6th-11th — O brāhmaṇa, brother-loss, wasted thoughts, betrayal-renunciation.",tags:["malefic-3rd","brother-loss"],verified:"auto"}
      ]
    },
    15: {
      title_te: "సుఖభావఫలాధ్యాయః",
      title_en: "Chapter on the Fruits of the Sukha-Bhāva (4th House — Mother, Home, Vehicles, Happiness)",
      summary_te: "ఈ అధ్యాయము చతుర్థ భావము (సుఖ భావము) యొక్క ఫలములను వివరించును. తల్లి సుఖము, గృహ-భూమి-వాహన సంపద, మానసిక సంతృప్తి, విద్య-బుద్ధి-శక్తి — ఈ అన్నీ ఈ భావము నుండి. సుఖేశుడి స్థానము, శుభ-పాప గ్రహ ప్రభావము, చంద్రుని (సుఖ కారక) స్థితి ముఖ్యము. దిగ్బలములో శుక్రుడు 4వ భావములో ఉండుట గృహ-వాహన సుఖము యొక్క శుభ యోగము. తల్లి దీర్ఘాయుష్షు, ఆరోగ్య కూడా ఈ భావ ద్వారానే.",
      verses: [
        {sl:1,page:20,sanskrit:"ఇత్థం తృతీయభావస్య బలం సాశేష్షో మునః । సుఖభావఫలం చాపకే కథయామి ద్విజోత్తమ ॥ 1 ॥",telugu_bhava:"[పరాశర:] ఈ విధముగా తృతీయ భావ బలమును పూర్తిగా చెప్పితిని. ఇపుడు సుఖ భావ ఫలమును ఓ ద్విజోత్తమా! చెప్పెదను.",english:"Thus the strength of the third bhāva is wholly declared, O sage. Now, O foremost brāhmaṇa, I narrate the fruits of the sukha-bhāva.",tags:["transition","4th-house","sukha"],verified:"auto"},
        {sl:2,page:20,sanskrit:"సుఖేశే సుఖభావస్థో అగ్నిం శర్త్రృపేఽపి వా । సుఖధుః చ జాతస్య భూగృహాణాం వదేత్‌ ॥ 2 ॥",telugu_bhava:"సుఖేశుడు సుఖ భావములో — లేదా అగ్నికి/శత్రుపతికి సంబంధించినను — జాతకుని భూ-గృహ-సుఖధామము వృద్ధి చెందును.",english:"The sukheśa in the sukha-bhāva — even with malefic relations — increases the native's land-house-happiness.",tags:["sukha-lord-4th","land-house-prosperity"],verified:"auto"},
        {sl:3,page:20,sanskrit:"స్నుగతో స్యాశ్రితే ద్యోంత్రే సుఖభావాద్యి యదః । భూమియనామ్యచారీణాం సుఖం చాచ్యగతం తథా ॥ 3 ॥",telugu_bhava:"స్నుగతుడు ఆశ్రయించిన ద్యోంత్ర (సుఖ భావ ఆశ్రిత) స్థితిలో — భూమి యానాద్యచార-సంబంధ సుఖము.",english:"In the sukha-bhāva-stationed conditions, the happiness from land-vehicle-travel pursuits.",tags:["land-vehicles","conveyances"],verified:"auto"},
        {sl:4,page:20,sanskrit:"కన్యదశాయే సంయుక్తే కేన్త్రే గతో గ్రహస్యః । విస్తీర్ణవిభ్యే గ్రాహ్య్యత్తయా త్యశ్యమ్యే వదేత్‌ ॥ 4 ॥",telugu_bhava:"[సుఖ-సంబంధ గ్రహ] కన్యదశలో సంయోగము, కేంద్రములో ఉన్నచో — విస్తీర్ణ వైభ గ్రాహ్యత్వము కల్గును.",english:"In conjunction during the kanyā-daśā, kendra-stationed planet — bestows expansive prosperity.",tags:["dasha-conjunction","kendra-effect"],verified:"auto"}
      ]
    }
  }
};
