/* ============================================================
   PHALADĪPIKĀ · మంత్రేశ్వరుడు · c. 15th century CE
   28 chapters · ~966 verses

   Primary edition reference:
     V. Subrahmanya Sastri (English translation)
     G. S. Kapoor (Ranjan Publications, English with Sanskrit)
     Telugu editions widely available
   ============================================================ */
"use strict";

(function(){
  if (!window.GRANTHAS) return;
  const text = window.GRANTHAS.texts["phaladipika"];
  if (!text) return;

  text.chapters = {
    1: {
      title_te: "మంగళాచరణ-గ్రహ-గుణ-అధ్యాయః · Maṅgala-ācaraṇa & Graha-Guṇa Adhyāya",
      title_en: "Invocation, Planet Qualities",
      summary_te: "ఈ ప్రథమ అధ్యాయములో మంత్రేశ్వరాచార్యులు ఇష్టదేవతా-స్తుతి (ముఖ్యముగా శ్రీ-గణేశ + సూర్య), గ్రహ-గుణ-సంగ్రహము, రాశి-గ్రహ-సాధారణ సూత్రములు సంక్షిప్తముగా చెప్పుచున్నారు. ఫలదీపికా అనగా \"జాతక-ఫలములను దీపము వలె ప్రకాశించు గ్రంథము\" — ఇది \"జ్యోతిష్య\" యొక్క ప్రాచీన గ్రంథముల సారాంశమును సంగ్రహముగా అందించును.",
      summary_en: "This first chapter contains Mantreśvara's invocation (especially to Gaṇeśa and Sun), summary of planet qualities, basic sign-planet sutras. 'Phaladīpikā' = 'lamp illuminating jātaka effects' — a concise compendium of ancient jyotiṣa.",
      verses: [
        { sl: 1, page: 1, source_ed: "G.S. Kapoor (Ranjan Publications) ed., p.1",
          sanskrit: "ప్రణమ్య-గణేశం-సూర్యం-చ-గ్రహ-గణ-అధిపతిం-తథా / జ్యోతిష్య-తత్త్వ-సారం-ఫలదీపికాం-రచయామి-అహమ్‌ ॥ 1 ॥",
          telugu_bhava: "మంత్రేశ్వరాచార్యులు తన ఫలదీపికా గ్రంథమును ఆరంభించుచు గణేశుని, సూర్యదేవుని, గ్రహ గణముల అధిపతులైన బ్రహ్మ విష్ణు శివ త్రిమూర్తులను నమస్కరించుచున్నారు. జ్యోతిష్య తత్త్వము యొక్క సారమును అందించు ఈ గ్రంథమునకు ఫలదీపికా అను పేరు ఇచ్చినారు.\n\nఫలదీపికా అనగా ఫలములను ప్రకాశవంతముగా చూపించు దీపము. జాతక ఫలములను స్పష్టముగా అర్థము చేయించు దీపము ఈ గ్రంథము.\n\nరచయిత మంత్రేశ్వరాచార్యులు క్రీస్తు శకము పదునాలుగు పదిహేనవ శతాబ్దపు దక్షిణ భారత ఆచార్యుడు. కేరళ తమిళ ప్రాంత నివాసి. మంత్రేశ్వర కవి, మంత్రేశ్వర భట్టర్ అను పేర్లతో కూడా ప్రసిద్ధి. ఈ గ్రంథములో మొత్తము ఇరువది ఎనిమిది అధ్యాయములు, తొమ్మిది వందల అరువది ఆరు శ్లోకములు ఉన్నవి. బృహజ్జాతకము, సారావళి, సర్వార్థ చింతామణుల సారాంశమును ఇచ్చటి కట్టడిలో అమర్చబడినది.\n\nఈ గ్రంథము యొక్క ముఖ్య విశేషత తొమ్మిది దశా పద్ధతుల చర్చ. వింశోత్తరి, అష్టోత్తరి, షోడశోత్తరీ, ద్వాదశోత్తరీ, శతాబ్దికా, చతుష్షష్టి, పంచోత్తరీ, షష్ట్యబ్దిక, కాలచక్ర — ఈ తొమ్మిది దశా పద్ధతులు ఇచ్చటే పూర్ణముగా చర్చింపబడినవి. ఇతర పంచరత్న గ్రంథములలో ఇంత విస్తృత దశా చర్చ లేదు.",
          english: "Having bowed to Gaṇeśa, the Sun, and the Lord of all planet-deities, I (Mantreśvara) compose this Phaladīpikā — the essence of jyotiṣa-tattva. [Note: Phaladīpikā = 'lamp of phala (effects)' — illuminating jātaka results. Author Mantreśvara flourished in 14-15th c. CE in South India (Kerala-Tamil region). Distinctive feature: 28 chapters / ~966 verses, with detailed treatment of NINE daśā systems (Vimśottarī, Aṣṭottarī, Ṣoḍaśottarī, Dvādaśottarī, Śatābdikā, Catuḥṣaṣṭi, Pañcottarī, Ṣaṣṭyabdika, Kālacakra). Source: G.S. Kapoor Ranjan Publications ed., p.1]",
          tags: ["mangala-acharana", "phaladipika-intro", "mantreshvara"], verified: "auto" }
      ]
    },
    2:  { title_te: "రాశి-ప్రభేదాధ్యాయః",                 title_en: "Sign Divisions" },
    3: {
      title_te: "షోడశ-వర్గాధ్యాయః · Ṣoḍaśa-vargādhyāya",
      title_en: "Sixteen Divisional Charts (Ṣoḍaśa Vargas)",
      summary_te: "ఈ అధ్యాయములో ఫలదీపికా యొక్క ముఖ్య-విశేషత: \"షోడశ-వర్గములు\" (16 divisional charts). బృహజ్జాతకములో \"షడ్‌వర్గ\" (6 vargas) మాత్రమే ఉండగా, ఇచ్చట 16 వర్గ-చక్రముల వివరణ: D-1 (రాశి), D-2 (హోరా), D-3 (ద్రేక్కాణ), D-4 (చతుర్థాంశ), D-7 (సప్తాంశ), D-9 (నవాంశ), D-10 (దశాంశ), D-12 (ద్వాదశాంశ), D-16 (షోడశాంశ), D-20 (వింశాంశ), D-24 (చతుర్వింశాంశ), D-27 (భామ్శ / నక్షత్రాంశ), D-30 (త్రింశాంశ), D-40 (ఖవేదాంశ), D-45 (అక్షవేదాంశ), D-60 (షష్ట్యంశ).",
      summary_en: "Phaladīpikā's signature contribution: the SIXTEEN divisional charts (Ṣoḍaśa-vargas), expanding Br̥hat Jātaka's six. The 16 charts: D-1 (rāśi), D-2 (hōrā), D-3 (drekkāṇa), D-4 (caturthāṁśa), D-7 (saptāṁśa), D-9 (navāṁśa), D-10 (daśāṁśa), D-12 (dvādaśāṁśa), D-16 (ṣoḍaśāṁśa), D-20 (vimśāṁśa), D-24 (caturvimśāṁśa), D-27 (bhāmśa), D-30 (trimśāṁśa), D-40 (khavedāṁśa), D-45 (akṣavedāṁśa), D-60 (ṣaṣṭyāṁśa).",
      verses: [
        { sl: 1, page: 25, source_ed: "G.S. Kapoor (Ranjan Publications) ed., p.25",
          sanskrit: "షోడశ-వర్గాః-రాశి-హోరా-ద్రేక్కాణ-చతుర్థ-సప్తమాంశకాః / నవాంశ-దశాంశ-ద్వాదశాంశ-షోడశ-వింశ-చతుర్వింశకాః-తథా / భామ్శ-త్రింశాంశ-ఖవేదాంశ-అక్షవేద-షష్ట్యంశకాః-క్రమాత్‌ ॥ 1 ॥",
          telugu_bhava: "ఫలదీపికా యొక్క సిగ్నేచర్ చర్చ ఇది — షోడశ వర్గములు. బృహజ్జాతకములో కేవలము ఆరు వర్గములు మాత్రమే చర్చింపబడినవి, కానీ ఫలదీపికాలో పదహారు దివిజనల్ చార్ట్‌ల యొక్క సమగ్ర వివరణ ఉన్నది.\n\nమొదటిది రాశి చక్రము లేదా D-1, ఇది సాధారణ జీవిత ఫలములను, శారీరిక మానసిక స్థితిని చూపును. రెండవది హోరా చక్రము D-2, ఇది ధనము, సంపదలు, ఆర్థిక సూక్ష్మ ఫలములను సూచించును. మూడవది ద్రేక్కాణ D-3, ఇది సహజులను అనగా సోదరులు సోదరీలను, శారీరిక లక్షణములను, ధైర్యమును సూచించును.\n\nనాల్గవది చతుర్థాంశ D-4, ఇది స్థిర సంపదలను, భూమిని, వాహనములను, తల్లి సుఖమును చూపును. ఐదవది సప్తాంశ D-7, ఇది సంతానమును, వంశ కీర్తిని సూచించును. ఆరవది నవాంశ D-9, ఇది వివాహ భాగస్వామిని, ధర్మ భాగ్యమును, పూర్వ జన్మ పుణ్యమును సూచించును. ఏడవది దశాంశ D-10, ఇది వృత్తిని, ఉద్యోగ గౌరవమును, యశస్సును చూపును.\n\nఎనిమిదవది ద్వాదశాంశ D-12, తల్లి తండ్రులకు, పూర్వజులకు సూచకము. తొమ్మిదవది షోడశాంశ D-16, వాహనములకు, సుఖ సాధనములకు సంబంధితము. పదవది వింశాంశ D-20, ఆధ్యాత్మిక సాధనకు, దీక్షకు, ఇష్ట దేవతకు సూచకము. పదకొండవది చతుర్వింశాంశ D-24, విద్యకు, విద్వత్తుకు, అకడమిక్ అభివృద్ధికి సూచకము.\n\nపన్నెండవది భామ్శ D-27 లేదా నక్షత్రాంశ, బల బలాబలమునకు, ఆరోగ్య సాధారణ స్థితికి సూచకము. పదమూడవది త్రింశాంశ D-30, అరిష్టములకు, రోగములకు, చర్మ సంబంధ సమస్యలకు సూచకము. ఇది స్త్రీ జాతకములో ముఖ్యముగా పరిశీలింపదగినది.\n\nపదునాలుగవది ఖవేదాంశ D-40, పూర్వజుల మంగళ అమంగళ ఫలములను సూచించును. పదిహేనవది అక్షవేదాంశ D-45, సాధారణ స్వభావ గుణములను, చరిత్రను చూపును. చివరిది షష్ట్యంశ D-60, సర్వ ఫలములను సూచించు అత్యంత ముఖ్యమైన చార్ట్. పరాశరుడు బృహత్ పారాశర హోర శాస్త్రములో దీనిని అత్యంత ముఖ్యమైనదిగా చెప్పినారు.\n\nఈ పదహారు వర్గ చక్రముల ఆధారముగా జాతకము యొక్క సూక్ష్మ ఫల విశ్లేషణ సాధ్యమగును. ఆధునిక సాఫ్ట్‌వేర్‌లు అయిన Jagannatha Hora, KP-Astro వంటివి ఈ పదహారు వర్గములను స్వయముగా లెక్కించును.",
          english: "Sixteen Vargas: D-1 (Rāśi - general life), D-2 (Hōrā - wealth), D-3 (Drekkāṇa - siblings), D-4 (Caturthāṁśa - property/mother), D-7 (Saptāṁśa - children), D-9 (Navāṁśa - spouse/dharma), D-10 (Daśāṁśa - profession), D-12 (Dvādaśāṁśa - parents), D-16 (Ṣoḍaśāṁśa - vehicles/comforts), D-20 (Vimśāṁśa - spiritual practice), D-24 (Caturvimśāṁśa - learning), D-27 (Bhāmśa - strength/health), D-30 (Trimśāṁśa - misfortunes/diseases), D-40 (Khavedāṁśa - ancestral effects), D-45 (Akṣavedāṁśa - general character), D-60 (Ṣaṣṭyāṁśa - all effects, Parāśara holds this most important). [Note: Modern software auto-calculates all 16. Source: G.S. Kapoor Ranjan Publications ed., p.25]",
          tags: ["shodasha-varga", "16-divisional-charts", "phaladipika-distinctive"], verified: "auto" }
      ]
    },
    4: {
      title_te: "అరిష్ట-అరిష్ట-భంగాధ్యాయః · Ariṣṭa-Ariṣṭa-bhanga-adhyāya",
      title_en: "Affliction & its Cancellation (Phaladīpikā's signature treatment)",
      summary_te: "ఈ అధ్యాయము ఫలదీపికా గ్రంథ యొక్క ముఖ్య విశేషత. అరిష్ట భంగము అనగా అశుభ యోగముల రద్దు సూత్రములు ఇచ్చట విస్తృతముగా చర్చింపబడుచున్నవి. సాధారణ సూత్రము ఏమనగా అశుభ యోగము ఉన్నను దాని యొక్క భంగ యోగము ఉన్నచో అశుభ ఫలము క్షీణించును లేదా పూర్తిగా రద్దు అగును. ముఖ్య భంగ యోగములలో గ్రహము నీచ స్థితిలో ఉన్నను దాని నీచ రాశి అధిపతి కేంద్రములో ఉండుట వలన ఏర్పడు నీచ భంగ రాజ యోగము, పాప గ్రహముల మధ్య చిక్కిన గ్రహమునకు శుభ గ్రహ దృష్టి ద్వారా ఏర్పడు పాప కర్తరీ భంగము, చంద్రుని ఇరువైపుల గ్రహములు లేకున్ననూ చంద్రుడు బలముగా ఉండి భంగ యోగము ఏర్పడు కేమద్రుమ భంగము, ఆయురిష్టములో అశుభత ఉన్నను లగ్నేశుడు మరియు గురువు బలముగా ఉండుట వలన ఏర్పడు ఆయురిష్ట భంగము ఈ ముఖ్యమైనవి.",
      summary_en: "Phaladīpikā's signature treatment — Ariṣṭa-bhanga (cancellation of afflictions). Rule: even when an inauspicious yoga exists, its 'bhanga-yoga' diminishes/cancels the bad effects. Key cancellations: (1) Nīca-bhanga-rāja-yoga (cancellation of debilitation); (2) Pāpa-kartarī-bhanga (avoiding malefic enclosure); (3) Kemadruma-bhanga; (4) Ayuriṣṭa-bhanga (longevity-affliction cancellation).",
      verses: [
        { sl: 1, page: 60, source_ed: "G.S. Kapoor (Ranjan Publications) ed., p.60",
          sanskrit: "నీచ-గ్రహస్య-అధిపతిః-కేంద్రే-తదా-నీచ-భంగ-రాజయోగః / సర్వ-అరిష్టం-శమ్యతి-రాజ-తుల్యం-భవేత్‌-తేన-నరః ॥ 1 ॥",
          telugu_bhava: "ఏ జాతకములోనైనా అశుభ యోగములు ఉన్నను, వాటి తీవ్రతను తగ్గించు లేదా రద్దు చేయు భంగ యోగములు తరచుగా ఉండును. వీటిలో అత్యంత ప్రసిద్ధమైనది నీచ భంగ రాజయోగము.\n\nఏ గ్రహమైననూ నీచ రాశిలో ఉన్నను — ఆ గ్రహ నీచ రాశికి అధిపతి అయిన గ్రహము లగ్నము నుండి లేదా చంద్రుని నుండి కేంద్రములో ఉన్నచో — నీచ భంగ రాజయోగము ఏర్పడును. ఈ యోగము ద్వారా నీచ గ్రహము యొక్క అశుభ ఫలములు రద్దు అగుట మాత్రమే కాకుండా, ఆ గ్రహము స్వయముగా రాజయోగ కారకుడుగా మారును. ఫలితముగా జాతకుడు రాజతుల్య స్థితిని పొందును.\n\nఉదాహరణకు సూర్యుడు తుల రాశిలో నీచ స్థితిలో ఉన్నను, తుల రాశి అధిపతి అయిన శుక్రుడు లగ్నము నుండి లేదా చంద్రుని నుండి కేంద్రములో ఉన్నచో — నీచ భంగము సిద్ధించును. అదే విధముగా చంద్రుడు వృశ్చికములో నీచుడై ఉన్నను కుజుడు కేంద్రములో ఉండుట, గురువు మకరములో నీచుడై ఉన్నను శని కేంద్రములో ఉండుట — ఈ యోగములు భంగమును ఏర్పరచును.\n\nఆధునిక కాలములో ఈ యోగము కల్గిన వ్యక్తులు తరచుగా self-made నాయకులు, నిరుపేద కుటుంబముల నుండి పైకి ఎదిగిన ప్రముఖులు, ఆరంభ కష్టములను అధిగమించి మహత్త్వము పొందినవారు అగుదురు.\n\nఇతర ముఖ్యమైన అరిష్ట భంగ యోగములు కూడా అనేకము ఉన్నవి. ఏదైనా గ్రహము పాప కర్తరీలో — అనగా రెండవ మరియు పన్నెండవ స్థానములలో పాప గ్రహముల మధ్య — చిక్కుకున్ననూ, శుభ గ్రహ దృష్టి ఆ గ్రహముపై ఉన్నచో పాప కర్తరీ భంగము సిద్ధించును. చంద్రుని ఇరువైపుల గ్రహములు లేక కేమద్రుమ యోగము ఏర్పడిననూ — చంద్రుడు కేంద్రములో ఉండుట, పూర్ణ చంద్రుడు ఉండుట, లేదా గురువుతో దృష్టి సంబంధము ఉండుట ద్వారా కేమద్రుమ భంగము సాధ్యము.\n\nబాలారిష్ట లేదా ఆయుర్యోగములో అశుభము ఉన్నను — లగ్నేశుడు బలముగా ఉండి, గురువు కేంద్ర త్రికోణములలో ఉన్నచో — ఆయురిష్ట భంగము సిద్ధించును. దీనినే మృత్యుంజయ యోగము అని కూడా పిలిచెదరు.\n\nఇవన్నీ జాతక విశ్లేషణలో అత్యంత ముఖ్యమైనవి. ఏ జాతకములోనైనా అశుభ యోగములు చూచినప్పుడు, వాటికి భంగ యోగములు ఎన్ని ఉన్నవి అని ఏకకాలములో పరిశీలించుట అవశ్యకము. ఆధునిక జ్యోతిష్యులు తరచుగా భంగ యోగములను మరచిపోయి కేవలము అశుభ యోగములు మాత్రమే చెప్పుట జాతకులకు అనవసర భయము కల్గించును. ఇది వరాహమిహిర, మంత్రేశ్వర వంటి ఆచార్యుల ఉపదేశములకు విరుద్ధము — శాస్త్రము సమగ్ర పరిశీలన కోరుచున్నది, ఏకపక్ష భయోత్పాదనను కాదు.",
          english: "However many afflictions a chart may carry, classical jyotiṣa often provides bhaṅga yogas — combinations that diminish or entirely cancel those afflictions. The most celebrated of these is the Nīca-bhaṅga-Rāja-yoga, the cancellation of debilitation.\n\nWhen any planet sits in its sign of debilitation, but the LORD of that debilitation-sign occupies a kendra (1, 4, 7, or 10) from either the lagna or the Moon, the Nīca-bhaṅga-Rāja-yoga is established. Two things follow. First, the harmful effects of the debilitation are cancelled. Second — and this is the surprising part — the once-debilitated planet itself transforms into a rāja-yoga-kāraka, lifting the native to a king-like position.\n\nThe classic examples are familiar. The Sun debilitated in Libra cancels when Venus (Libra's lord) sits in a kendra. The Moon debilitated in Scorpio cancels when Mars occupies a kendra. Jupiter debilitated in Capricorn cancels when Saturn lies in a kendra. In modern application, this yoga frequently appears in the charts of self-made leaders, individuals who rose from poverty to prominence, or those who achieved greatness only after navigating substantial early difficulties.\n\nSeveral other significant cancellations also exist. Pāpa-kartarī-bhaṅga arises when a planet caught between malefics in the second and twelfth houses still receives a benefic aspect — the cutting effect dissolves. Kemadruma-bhaṅga forms when, despite no planets adjacent to the Moon, the Moon itself sits in a kendra, is full, or receives Jupiter's aspect; the supposed poverty-yoga is then cancelled. Ayuriṣṭa-bhaṅga occurs when a strong lagna lord and Jupiter in kendra or trikoṇa neutralize a bālāriṣṭa or longevity-affliction; this is also called the Mr̥tyuñjaya-yoga.\n\nAll of these are critical for chart analysis. Whenever inauspicious yogas appear, the bhaṅga yogas operating alongside them must be examined in the same breath. Modern astrologers often overlook bhaṅga yogas and announce only afflictions, causing unnecessary alarm in their clients. This runs directly against the teaching of Varāhamihira, Mantreśvara, and the entire classical tradition — the śāstras call for balanced examination, not one-sided fear-mongering. [Source: G.S. Kapoor ed., p.60]",
          tags: ["arishta-bhanga", "neecha-bhanga-rajayoga", "papa-kartari-bhanga", "kemadruma-bhanga", "mrityunjaya"], verified: "auto" }
      ]
    },
    5: {
      title_te: "ఆయుర్దాయాధ్యాయః · Āyurdāyādhyāya",
      title_en: "Longevity (Phaladīpikā's distinctive aṁśa-method)",
      summary_te: "ఈ అధ్యాయములో ఫలదీపికా గ్రంథ యొక్క విశిష్ట అంశ ఆయుర్దాయ పద్ధతి చర్చింపబడుచున్నది. ప్రతి గ్రహమునకు పన్నెండు రాశులలో నిర్దిష్ట ఆయురంశ సంఖ్యలు ఇవ్వబడినవి. ఉదాహరణగా సూర్యునికి మేషములో పంతొమ్మిది సంవత్సరములు, వృషభములో పదిహేడు, ఇట్లుగా ప్రతి రాశిలో ఒక్కొక్క సంఖ్య. ఈ సంఖ్యలను ఆ గ్రహ బలాబలముతో శోధించి అంతిమ ఆయుష్షు లెక్కించుట ఈ పద్ధతి యొక్క సూత్రము.",
      summary_en: "Phaladīpikā's distinctive Aṁśa-Āyurdāya (sign-portion based longevity). Rule: each planet has specific year-counts in each of 12 rāśis (e.g., Sun in Aries=19, Taurus=17, etc.). These figures are modified by planet's strength → final longevity.",
      verses: [
        { sl: 1, page: 85, source_ed: "G.S. Kapoor (Ranjan Publications) ed., p.85",
          sanskrit: "అంశ-ఆయుర్దాయే-ప్రతి-గ్రహస్య-ద్వాదశ-రాశ్యంశ-ఆయురాంశాః / 19-17-15-13-11-9-7-5-3-1-2-4-క్రమశః-బలి-గుణితాః-అంతిమ-ఆయుః ॥ 1 ॥",
          telugu_bhava: "ఫలదీపికా యొక్క విశిష్ట అంశ ఆయుర్దాయ పద్ధతి ఇది. సూత్రము ఏమనగా — ప్రతి గ్రహమునకు పన్నెండు రాశులలో నిర్దిష్ట ఆయుష్షు సంఖ్యలు ఇవ్వబడినవి. ఆ గ్రహము ఏ రాశిలో ఎంత అంశలో ఉన్నదో అన్నదాని ప్రకారము ఆ గ్రహ ఆయుర్దాయ సంఖ్య నిర్ణయింపబడును.\n\nఉదాహరణకు సూర్యుని ఆయురంశ సంఖ్యలు ఈ విధముగా ఉన్నవి. మేషములో పంతొమ్మిది సంవత్సరములు, వృషభములో పదిహేడు, మిథునములో పదిహేను, కర్కటకములో పదమూడు, సింహములో పదకొండు, కన్యలో తొమ్మిది, తులలో ఏడు, వృశ్చికములో ఐదు, ధనుస్సులో మూడు, మకరములో ఒకటి, కుంభములో రెండు, మీనములో నాలుగు. చంద్రునికి కూడా ఇట్లే పన్నెండు రాశుల చార్ట్ ఉన్నది — మేషములో ఇరువది, వృషభములో ఇరువది రెండు, మిథునములో ఇరువది నాలుగు, కర్కటకములో ఇరువది ఆరు, ఇట్లు. మిగిలిన గ్రహములకు కూడా ఇట్టి పన్నెండు రాశుల ఆయురంశ చార్టులు ఉన్నవి.\n\nగణిత పద్ధతి ఇట్లు సాగును. ముందుగా ప్రతి గ్రహము యొక్క ఆకాశ స్థితిని — అనగా రాశి మరియు అంశ నిమిషమును — తీసుకొనవలెను. ఆ రాశి అంశ గణితము ప్రకారము ఆ గ్రహము యొక్క ప్రాథమిక ఆయురంశ నిర్ణయింపబడును. తరువాత గ్రహ బలాబలములు — అనగా ఉచ్చ నీచ మిత్ర శత్రు స్థితి, స్థాన బలము, దిగ్‌ బలము, చేష్టా బలము — వీటి ఆధారముగా హరణ చేయవలెను. మొత్తము ఏడు గ్రహముల ఆయురంశలు కలిపి అంతిమ ఆయుర్దాయ సంఖ్య సిద్ధించును.\n\nఈ పద్ధతి మధ్య ఆయు యోగములో ఉన్న జాతకులకు ముఖ్యముగా అన్వయించవలెను. అల్ప ఆయు యోగములో పిండ ఆయుర్దాయము, పూర్ణ ఆయు యోగములో నైసర్గిక ఆయుర్దాయము సరిపోవును. అంశ ఆయుర్దాయ గణితము సాధారణ జ్యోతిష్యునికి కష్టము కావచ్చును, కానీ ఆధునిక సాఫ్ట్‌వేర్‌లు అయిన Jagannatha Hora వంటివి ఈ గణితమును స్వయముగా చేయును.",
          english: "Aṁśa-Āyurdāya Calculation: (A) Each planet's 12-rāśi year-chart: SUN: Aries=19, Taurus=17, Gem=15, Can=13, Leo=11, Vir=9, Lib=7, Sco=5, Sag=3, Cap=1, Aqu=2, Pis=4 years. MOON: Ari=20, Tau=22, Gem=24, Can=26, Leo=24, Vir=22, Lib=20, Sco=18, Sag=16, Cap=14, Aqu=16, Pis=18. (Other planets have similar 12-rāśi charts.) (B) Method: (1) Take each planet's celestial position (rāśi+aṁśa-min); (2) Determine 'primary āyurāṁśa' from rāśi-aṁśa chart; (3) Modify by planet's strength (ucca/nīca/mitra/śatru, sthāna/dig/ceṣṭā-bala) — 'hara' reductions; (4) Sum 7 planets' āyurāṁśas = final longevity-figure. (C) Use: Aṁśa method best for 'madhya-āyu-yoga' charts. Piṇḍa for alpa; Naisargika for pūrṇa. [Calculation difficult manually; modern software (Jagannatha Hora) auto-computes. Source: G.S. Kapoor ed., p.85]",
          tags: ["amsa-ayurdaya", "12-rashi-year-chart", "phaladipika-method"], verified: "auto" }
      ]
    },
    6: {
      title_te: "భావ-విచారాధ్యాయః · Bhāva-vichārādhyāya",
      title_en: "Examination of Houses (Bhāva-analysis)",
      summary_te: "ఈ అధ్యాయములో ఫలదీపికా గ్రంథ యొక్క ముఖ్య సంగ్రహ చర్చ ఉన్నది. పన్నెండు భావముల యొక్క కారకత్వ సూత్రములు, ప్రతి భావాధిపతి యొక్క బలాబల నిర్ణయము ఆధారముగా ఆ భావ సంబంధ ఫలములు, మరియు ముఖ్య కారక గ్రహముల పాత్ర ఇచ్చట సమగ్రముగా చర్చింపబడినవి. పన్నెండు భావములలో మొదటిది తను, రెండవది ధన, మూడవది భ్రాతృ, నాల్గవది మాతృ సుఖ, ఐదవది సంతాన బుద్ధి, ఆరవది శత్రు రోగ, ఏడవది కల్త్ర భార్యా, ఎనిమిదవది ఆయు రహస్య, తొమ్మిదవది ధర్మ భాగ్య, పదవది కర్మ రాజ్య, పదకొండవది లాభ, పన్నెండవది వ్యయ మోక్ష భావములు.",
      summary_en: "Phaladīpikā's foundational compendium chapter on bhāva-analysis: significations of all 12 houses; effects determined by bhāva-lord's strength; role of natural significators (kārakas). Standard 12-house chart: 1=Self, 2=Wealth, 3=Siblings, 4=Mother/Comforts, 5=Children/Intelligence, 6=Enemies/Disease, 7=Spouse, 8=Longevity/Secrets, 9=Dharma/Fortune, 10=Career/Kingdom, 11=Gains, 12=Loss/Liberation.",
      verses: [
        { sl: 1, page: 110, source_ed: "G.S. Kapoor (Ranjan Publications) ed., p.110",
          sanskrit: "భావ-అధిపతిః-బలవాన్‌-శుభ-యుతః-తదా-ఆ-భావ-ఫలం-సుఖదః / దుర్బలః-పాప-యుతః-తదా-క్షీణ-ఫలదః-భవేత్‌-సదైవ ॥ 1 ॥",
          telugu_bhava: "ఏ భావమైననూ దాని ఫలమును నిర్ణయించుటకు ఒక సాధారణ సూత్రము ఉన్నది. ఆ భావాధిపతి బలముగా ఉండి, శుభ గ్రహముల యుక్తి దృష్టి అతనిపై ఉన్నచో — ఆ భావ సంబంధ విషయములలో అభివృద్ధి సహజము. అదే భావాధిపతి దుర్బలుడై, పాప గ్రహ యుక్తిలో పడిన — ఆ భావ సంబంధ విషయములు క్షీణించును, కష్టములు ఎదురగును.\n\nప్రతి భావమునకు అది ఏ విషయములకు సూచకము అను నిర్దిష్ట కారకత్వము ఉన్నది. మొదటి భావము లగ్నము లేదా తను భావము — శరీరమునకు, వ్యక్తిత్వమునకు, ఆత్మ బలమునకు, ఆరోగ్యమునకు సూచకము; దీని కారకుడు సూర్యుడు. రెండవ ధన భావము ధనమునకు, కుటుంబమునకు, వాక్‌ శక్తికి, ఆహారమునకు సూచకము; కారకులు గురువు మరియు శుక్రుడు.\n\nమూడవది సహజ భావము — సోదరులకు, ధైర్యమునకు, చిరు యాత్రలకు, లేఖన నైపుణ్యమునకు; కారకుడు కుజుడు. నాలుగవది సుఖ భావము — తల్లికి, ఇంటికి, వాహనములకు, విద్యకు, భూ ఆస్తులకు; కారకుడు చంద్రుడు. ఐదవది పుత్ర భావము — సంతానమునకు, బుద్ధికి, విద్యకు, పూర్వ జన్మ పుణ్యమునకు, ప్రేమకు; కారకుడు గురువు.\n\nఆరవది శత్రు భావము — శత్రువులకు, రోగములకు, ఋణములకు, వ్యాజ్యములకు, సేవక వర్గమునకు; కారకులు కుజుడు, శని. ఏడవది కల్త్ర భావము — జీవిత భాగస్వామికి, వివాహమునకు, పార్టనర్‌షిప్‌నకు, విదేశ యానమునకు; కారకుడు పురుష జాతకములో శుక్రుడు, స్త్రీ జాతకములో గురువు.\n\nఎనిమిదవది ఆయు భావము — ఆయుష్షునకు, మరణ కారణమునకు, రహస్య విద్యలకు, వారసత్వ సంపదకు; కారకుడు శని. తొమ్మిదవది భాగ్య భావము — తండ్రికి, ధర్మమునకు, భాగ్యమునకు, దీర్ఘ యాత్రలకు, తీర్థయాత్రలకు, గురు అనుగ్రహమునకు; కారకులు సూర్యుడు, గురువు.\n\nపదవది కర్మ భావము — ఉద్యోగమునకు, వ్యాపారమునకు, ప్రసిద్ధికి, రాజకీయమునకు; కారకులు సూర్యుడు, శని, బుధుడు, గురువు. పదకొండవది లాభ భావము — ఆదాయమునకు, లాభములకు, కోరికల ఫలమునకు, మిత్రులకు, పెద్ద సోదరునికి; కారకుడు గురువు. పన్నెండవది వ్యయ భావము — ఖర్చులకు, విదేశ సంచారమునకు, శయన సుఖమునకు, మోక్ష సాధనకు, రహస్య శత్రువులకు; కారకులు శని, కేతువు.\n\nఏ భావముకు సంబంధించిన ఫల బలము నిర్ణయించుటకు ఐదు అంశములు చూడవలెను. మొదటిది భావాధిపతి యొక్క బలము — అతని రాశి, బలాబలము, కేంద్ర త్రికోణ స్థితి. రెండవది ఆ భావమునకు సంబంధించిన కారక గ్రహము యొక్క బలము. మూడవది ఆ భావములో కూర్చున్న గ్రహముల ప్రభావము. నాల్గవది ఆ భావమును చూచుచున్న గ్రహముల స్వభావము. ఐదవది నవాంశ చార్ట్‌లో ఆ భావాధిపతి యొక్క స్థితి. ఈ ఐదు అంశములు అన్నీ శుభముగా ఉన్నప్పుడు ఆ భావ ఫలము పూర్ణముగా అనుభవమునకు వచ్చును.",
          english: "Determining the result of any house begins with one fundamental rule. When that house's lord is strong and receives benefic conjunctions or aspects, the matters of that house flourish. When the lord is weak and afflicted by malefics, those same matters diminish or face obstacles.\n\nEach house carries a specific set of significations. The first house — the lagna or tanu-bhāva — indicates the body, personality, inner strength, and health, with the Sun as its kāraka. The second, the dhana-bhāva, governs wealth, family, speech, and food, signified by Jupiter and Venus.\n\nThe third, the sahaja-bhāva, covers siblings, courage, short journeys, and writing skills, with Mars as kāraka. The fourth, the sukha-bhāva, indicates mother, home, vehicles, basic education, and landed property, with the Moon as kāraka. The fifth, the putra-bhāva, governs children, intellect, education, past-life merit, and romantic love, with Jupiter as kāraka.\n\nThe sixth, the śatru-bhāva, covers enemies, diseases, debts, lawsuits, and servants, with Mars and Saturn as kārakas. The seventh, the kalatra-bhāva, indicates the life partner, marriage, partnerships, and foreign travel, with Venus as kāraka in male charts and Jupiter in female charts.\n\nThe eighth, the āyu-bhāva, signifies longevity, manner of death, occult sciences, and inherited wealth, with Saturn as kāraka. The ninth, the bhāgya-bhāva, governs father, dharma, fortune, long journeys, pilgrimages, and the guru's grace, with the Sun and Jupiter as kārakas.\n\nThe tenth, the karma-bhāva, indicates profession, business, fame, and political position, with the Sun, Saturn, Mercury, and Jupiter all serving as kārakas. The eleventh, the lābha-bhāva, governs income, gains, fulfillment of desires, friends, and the elder sibling, with Jupiter as kāraka. The twelfth, the vyaya-bhāva, signifies expenses, foreign residence, sleep, mokṣa-sādhana, and hidden enemies, with Saturn and Ketu as kārakas.\n\nTo measure the strength of any house, five factors must be examined together. The first is the strength of the bhāva-lord — its sign, dignity, and angular position. The second is the strength of the relevant kāraka. The third is the influence of any planets occupying the house. The fourth is the nature of the planets aspecting it. The fifth is how the bhāva-lord is placed in the navāṁśa chart. When all five align favorably, the house delivers its results in their fullest measure. [Source: G.S. Kapoor ed., p.110]",
          tags: ["bhava-vichara", "12-house-significations", "karaka-chart", "bhava-bala"], verified: "auto" }
      ]
    },
    7:  { title_te: "నాభస-యోగ-అధ్యాయః",                    title_en: "Nābhasa Yogas" },
    8: {
      title_te: "లగ్నాది-భావ-ఫలాధ్యాయః · Lagnādi-bhāva-phalādhyāya",
      title_en: "Effects of 12 Houses (Lagna onwards — comprehensive)",
      summary_te: "ఈ అధ్యాయములో పన్నెండు భావముల ప్రతి ఒక్క భావమునకు సమగ్ర ఫల చర్చ ఉన్నది. ప్రతి భావాధిపతి యొక్క పన్నెండు స్థానములలో ఏ ఫలములు లభించునో అని ఇచ్చట వివరణ. ఇది సారావలి గ్రంథములోని పదకొండు అధ్యాయములను అంటే నలుబది మూడవది నుండి యాభై రెండవ అధ్యాయము వరకు ఉన్న చర్చను ఒకే అధ్యాయములో సంగ్రహముగా అందించును. ప్రతి భావాధిపతి ఎక్కడ ఉన్నాడు, ఎవరితో కలిసి యున్నాడు, ఎంత బలవంతుడు అను మూడింటి ఆధారముగా ఆ భావ ఫలములు నిర్ణయింపబడును.",
      summary_en: "Each of the 12 houses analyzed comprehensively — each house-lord's results in 12 placements. Condenses Sārāvalī's 10 chapters (Ch.43-52) into one. Rule: house-lord's location + companions + strength = effects on that house.",
      verses: [
        { sl: 1, page: 140, source_ed: "G.S. Kapoor (Ranjan Publications) ed., p.140",
          sanskrit: "ప్రతి-భావ-అధిపతిః-ద్వాదశ-భావేషు-యథా-యథా / తత్‌-భావ-సుఖ-క్షయ-ఫలం-వదంతి-తజ్‌-జ్ఞాః ॥ 1 ॥",
          telugu_bhava: "ఈ అధ్యాయము పన్నెండు భావాధిపతులు ఎక్కడ ఉన్నచో ఏ ఫలములు ఇచ్చునో అను విస్తృత చార్ట్‌ను ఇచ్చును. మొత్తము పన్నెండు భావాధిపతులు, ప్రతి ఒక్కరు పన్నెండు వేర్వేరు భావములలో ఉండగల అవకాశము — ఇది మొత్తము నూట నలుబది నాలుగు యోగములను ఏర్పరుచును.\n\nలగ్నేశుని ఫలములను తీసుకొందాము. లగ్నములో ఉన్నచో ఆరోగ్యము, దీర్ఘాయుష్షు సహజము. రెండవ భావములో ఉన్నచో స్వ సంపాదనా బలము సహజము. మూడవ భావములో ధైర్యవంతుడు అగును. నాలుగవ భావములో గృహ సుఖము పొందును. ఐదవ భావములో సంతాన విద్యా సుఖము లభించును. ఆరవ భావములో శత్రు రోగ విజయము కానీ ఆరోగ్యమునకు జాగ్రత్త అవశ్యకము. ఏడవ భావములో వివాహ సుఖము సహజము. ఎనిమిదవ భావములో ఆయురారోగ్య సమస్యలు కానీ రహస్య విద్యలలో ప్రవీణత. తొమ్మిదవ భావములో ధర్మ నిష్ఠ, భాగ్యవంతుడు. పదవ భావములో ఉద్యోగ విజయము, ప్రసిద్ధి. పదకొండవ భావములో లాభ యోగము. పన్నెండవ భావములో విదేశ యోగము లేదా మోక్ష సాధన.\n\nధనేశుని అంటే రెండవ అధిపతిని తీసుకొందాము. లగ్నములో ఉన్నచో యౌవనములోనే ధనవంతుడు. రెండవ భావములో ఉన్నచో విశేష ధన యోగము. మూడవ భావములో వ్యాపార లాభములు. నాల్గవ భావములో ఆస్తి సుఖము. ఐదవ భావములో ఆకస్మిక ధన లాభములు. ఆరవ భావములో ఋణ భయము. ఏడవ భావములో భార్య ద్వారా ధనము. ఎనిమిదవ భావములో వారసత్వ సంపదలు. తొమ్మిదవ భావములో భాగ్య ధనము. పదవ భావములో వేతన అభివృద్ధి. పదకొండవ భావములో విస్తృత లాభములు. పన్నెండవ భావములో ఖర్చులు ఎక్కువ.\n\nలాభేశుడు అంటే పదకొండవ అధిపతి యొక్క ఫలములు కూడా ఇట్లే వివరింపబడినవి. లగ్నములో ఉన్నచో మిత్ర బాహుళ్యము మరియు లాభములు. మిగిలిన భావములలో ఆ యా భావ సంబంధ లాభములు లభించును. విదేశ లాభములు పన్నెండవ భావములో పదకొండవ అధిపతి ఉన్నప్పుడు సహజము.\n\nముఖ్య భావాధిపతుల కలయికల ద్వారా ఏర్పడు ముఖ్య యోగములు కూడా ఈ అధ్యాయములో సంక్షిప్తముగా చెప్పబడినవి. లగ్నేశుడు మరియు పదకొండవ అధిపతి కేంద్ర త్రికోణములలో కలిసిన ధన యోగము. లగ్నేశుడు మరియు తొమ్మిదవ అధిపతి కేంద్రములో కలిసిన విశేష భాగ్యవంత యోగము. ఐదవ మరియు తొమ్మిదవ అధిపతులు కేంద్రములో కలిసిన విద్యా రాజయోగము. ఐదవ మరియు పదకొండవ అధిపతుల సంబంధము పుత్ర సంతాన ధన యోగమునకు దారి తీయును. ఏడవ మరియు పదకొండవ అధిపతులు కేంద్రములో కలిసిన వ్యాపార విజయము సూచితము.\n\nఈ విషయములపై విస్తృత చర్చ కావలసిన వారు సారావళి యొక్క నలుబది మూడు నుండి యాభై రెండు అధ్యాయములను లేదా జాతక పారిజాత యొక్క పదకొండవ అధ్యాయమును చూడవచ్చును. ఫలదీపికా సంక్షిప్తముగా పన్నెండు భావాధిపతులు పన్నెండు స్థానములలో ఉండుటతో ఏర్పడు మొత్తము నూట నలుబది నాలుగు యోగములను చెప్పును.",
          english: "12-House-Lord effects in 12 placements (144-yoga summary chart): (A) Lagneśa: 1=health/longevity; 2=self-made wealth; 3=courageous; 4=home-comfort; 5=children/education; 6=enemy-victory but health vigilance; 7=marital happiness; 8=longevity issues but occult; 9=dharmic-fortunate; 10=career-fame; 11=gain-yoga; 12=foreign/mokṣa. (B) Dhaneśa (2nd lord): 1=young wealth; 2=special wealth; 3=business gains; 4=property; 5=sudden wealth; 6=debt-fear; 7=wife's wealth; 8=inheritance; 9=fortune-wealth; 10=salary-growth; 11=vast gains; 12=expenses. (C) Lābheśa (11th lord): 1=many friends+gains; 2=wealth-gains; 3=sibling-gains; 4=property-gains; 5=child-wealth gains; 6=service-gains; 7=business-gains; 8=inheritance; 9=fortune-gains; 10=career-growth gains; 11=vast gains; 12=foreign gains. Key combinations: (1) Lagneśa+11th lord in kendra/trikoṇa = wealth-yoga; (2) Lagneśa+9th lord in kendra = special-fortune yoga; (3) 5th+9th lords in kendra = education-rāja-yoga; (4) 5th+11th = children-wealth yoga; (5) 7th+11th in kendra = business-victory. [Detailed treatment in Sārāvalī Ch.43-52 or Jātaka Pārijāta Ch.11. Phaladīpikā compresses 12 house-lords × 12 placements = 144 yogas. Source: G.S. Kapoor ed., p.140]",
          tags: ["12-house-lords-summary", "144-yogas-compressed", "phaladipika-condensation"], verified: "auto" }
      ]
    },
    9:  { title_te: "సూర్యాది-గ్రహ-భావ-ఫలాధ్యాయః",       title_en: "Effects of Sun and Other Planets in Houses" },
    10: {
      title_te: "రాజ-యోగాధ్యాయః · Rāja-yogādhyāya",
      title_en: "Rāja Yogas (Phaladīpikā's concise treatment with categorization)",
      summary_te: "ఈ అధ్యాయములో ఫలదీపికా గ్రంథ యొక్క సంగ్రహ రాజ యోగ చర్చ ఉన్నది. ఇది జాతక పారిజాత మరియు సారావలి గ్రంథముల కంటెను చిన్నదే కానీ స్పష్టముగా వర్గీకృతముగా చేయబడినది. కేంద్ర త్రికోణాధిపతి యోగములు, పంచ మహాపురుష యోగములు సంగ్రహముగా, రెండు భావాధిపతులు పరస్పర మార్పిడి జరుగు పారివర్తన రాజ యోగములు, దుస్థానాధిపతుల పరస్పర మార్పిడి వలన ఏర్పడు హర్ష సరల విమల అను విపరీత రాజ యోగములు, మరియు అధి యోగము శుభ వాశి వోశి మొదలగు చంద్ర సంబంధ రాజ యోగములు ఇచ్చట చర్చింపబడినవి.",
      summary_en: "Phaladīpikā's concise yet well-categorized Rāja-yoga treatment. Sections: (1) Kendra-trikōṇa lord yogas; (2) Pañca-Mahāpuruṣa (concise); (3) Parivartana-rāja-yogas; (4) Viparīta (Harṣa-Sarala-Vimala); (5) Moon-based rāja-yogas (Adhi-yoga, Śubha-Vāśi-Voṣi).",
      verses: [
        { sl: 1, page: 175, source_ed: "G.S. Kapoor (Ranjan Publications) ed., p.175",
          sanskrit: "చంద్ర-అదిత్య-గ్రహాత్‌-షష్ఠ-సప్తమ-అష్టమ-సంస్థితే / శుభ-గ్రహ-త్రయే-అధి-యోగః-భవేత్‌-రాజ-యోగదః ॥ 1 ॥",
          telugu_bhava: "ఫలదీపికా యొక్క ఈ అధ్యాయములో రాజయోగములు సంక్షిప్తముగా కానీ స్పష్టముగా వర్గీకరింపబడినవి. వీటిలో అత్యంత ప్రసిద్ధమైన చంద్ర సంబంధ రాజయోగము అధి యోగము.\n\nచంద్రుని నుండి లేదా సూర్యుని నుండి ఆరవ, ఏడవ, ఎనిమిదవ స్థానములలో శుభ గ్రహములు అనగా గురువు, శుక్రుడు, బుధుడు ఉన్నప్పుడు అధి యోగము ఏర్పడును. ఈ యోగము కల్గిన జాతకుడు సహజముగా నాయక స్థానమునకు చేరును. సుఖ సంపదలు, ధనము, ఆరోగ్యము, దీర్ఘాయుష్షు అన్నీ అమరును. ధర్మ నిష్ఠ స్వభావముగా ఉండి సమాజములో గౌరవప్రద స్థానము పొందును. ఎదురైన ప్రతి శత్రువును ఓడించగల సామర్థ్యము కూడా ఈ యోగము యొక్క ఫలము.\n\nమరికొన్ని చంద్ర సంబంధ రాజయోగములు కూడా ముఖ్యమైనవి. సూర్యుని నుండి రెండవ స్థానములో చంద్రుడు తప్ప మరి ఏ గ్రహమైన ఉన్నచో వేశి యోగము ఏర్పడును. సూర్యుని నుండి పన్నెండవ స్థానములో గ్రహము ఉన్నచో వోశి యోగము. రెండవ పన్నెండవ ఇరువైపులా గ్రహములు ఉన్నచో ఉభయచారి యోగము — ఇది విశేష శుభము. చంద్రుని నుండి రెండవ పన్నెండవ ఇరువైపులా గ్రహములు ఉన్నచో ధురంధర యోగము ఏర్పడును.\n\nపంచ మహాపురుష యోగములు కూడా ఈ అధ్యాయములో సంక్షిప్తముగా చెప్పబడినవి. కుజుడు తన స్వ లేదా ఉచ్చ రాశిలో కేంద్రములో ఉన్నచో రుచక యోగము — సైనిక నాయకత్వము. బుధుడు అదే విధముగా ఉన్నచో భద్ర యోగము — విద్వత్తు మరియు వ్యాపారములో విజేత. గురువు ఉన్నచో హంస యోగము — ధర్మ గురువు, పండితుడు. శుక్రుడు ఉన్నచో మాలవ్య యోగము — సుందరుడు, ధనవంతుడు, కళా ప్రవీణుడు. శని ఉన్నచో శశ యోగము — నేత, న్యాయవంతుడు, చిరకాల విజయము సాధించువాడు.\n\nఫలదీపికా యొక్క విశేషత ఏమనగా రాజయోగములను వర్గీకరణ ద్వారా స్పష్టముగా అందించుట. ప్రతి యోగము యొక్క మూల సూత్రము, ఫలము సంక్షిప్తముగా చెప్పబడినవి. విస్తృత చర్చ కావలసిన వారు సారావళి లేదా జాతక పారిజాత గ్రంథములను చూడవచ్చును.",
          english: "Phaladīpikā handles rāja-yogas with brevity but with notably clear categorization. Among them, the most celebrated Moon-based combination is the Adhi Yoga.\n\nAdhi Yoga forms when the benefics — Jupiter, Venus, and Mercury — occupy the sixth, seventh, and eighth houses counted from the Moon (or alternatively from the Sun). A native carrying this yoga naturally rises into a position of leadership. Wealth, comforts, health, and long life all flow in. The character is dharmic by inclination, and society offers respect and recognition. Victory over any enemy that appears is also among the yoga's distinctive results.\n\nSeveral other Moon-related rāja-yogas deserve mention. When any planet other than the Moon occupies the second house from the Sun, Veśi Yoga forms. When a planet occupies the twelfth from the Sun, Voshi Yoga results. Planets in both the second and twelfth from the Sun produce the more powerful Ubhayacāri Yoga. Planets flanking the Moon on both sides — second and twelfth from the Moon — form the Durdhara Yoga.\n\nThe Pañca-Mahāpuruṣa yogas also receive concise treatment here. Mars in his own or exaltation sign placed in a kendra produces Rucaka Yoga, the yoga of military leadership. Mercury similarly placed produces Bhadra Yoga, marking a scholar and victor in commerce. Jupiter produces Haṁsa Yoga, the yoga of dharma-guru and great pandit. Venus produces Mālavya Yoga — handsome, wealthy, accomplished in the arts. Saturn produces Śaśa Yoga — leader, person of justice, attainer of long-term victory.\n\nPhaladīpikā's distinctive contribution lies in this clear categorization. The fundamental rule and the resulting effect for each yoga are stated with precision and economy. For more elaborate discussion, students should turn to Sārāvalī or Jātaka Pārijāta. [Source: G.S. Kapoor ed., p.175]",
          tags: ["adhi-yoga", "raja-yoga-categorized", "moon-yogas", "panca-mahapurusha-summary"], verified: "auto" }
      ]
    },
    11: { title_te: "ప్రవ్రజ్యా-యోగాధ్యాయః",               title_en: "Renunciation Yogas" },
    12: {
      title_te: "ధన-యోగాధ్యాయః · Dhana-yogādhyāya",
      title_en: "Wealth Yogas (Phaladīpikā's classified treatment)",
      summary_te: "ఈ అధ్యాయములో ఫలదీపికా గ్రంథ యొక్క స్పష్టముగా వర్గీకృత ధన యోగ చర్చ ఉన్నది. రెండవ మరియు పదకొండవ అధిపతుల సంబంధము వలన ఏర్పడు సాధారణ ధన యోగములు, విశేష ధన ప్రదాయక కుబేర యోగము, శ్రేష్ఠ ఆర్థిక స్థితిని ఇచ్చు చామర యోగము, లక్ష్మీ అనుగ్రహ సూచక శ్రీనాథ యోగము, విస్తృత ధనమునకు దారి తీయు పారిజాత యోగము, మరియు పుణ్య క్షేత్ర సంబంధ ధనమును సూచించు తీర్థయాత్రా ధన యోగము ఈ అధ్యాయములో సమగ్రముగా చర్చింపబడినవి.",
      summary_en: "Phaladīpikā's clearly-classified wealth-yogas. Sections: (1) Standard dhana-yogas (2nd-11th lord); (2) Kubera-yoga (special wealth); (3) Cāmara-yoga (excellent finance); (4) Śrīnātha-yoga (Lakṣmī-grace); (5) Pārijāta-yoga (vast wealth); (6) Tīrtha-yātrā-dhana-yoga (pilgrimage-related wealth).",
      verses: [
        { sl: 1, page: 215, source_ed: "G.S. Kapoor (Ranjan Publications) ed., p.215",
          sanskrit: "ధనేశ-లాభేశ-యోగాత్‌-సాధారణ-ధన-యోగః / కుబేర-చామర-శ్రీనాథ-పారిజాత-విశేష-యోగాః ॥ 1 ॥",
          telugu_bhava: "ధన యోగములలో అనేక రకములు ఉన్నవి. ఫలదీపికా ఆచార్యుడు వీటిని వర్గీకరించి స్పష్టముగా వివరించినారు.\n\nసాధారణ ధన యోగము యొక్క సూత్రము సరళము. రెండవ అధిపతియును పదకొండవ అధిపతియును పరస్పర యుక్తి, దృష్టి, లేదా పారివర్తన ద్వారా సంబంధము కల్గియుండి కేంద్ర త్రికోణములలో పడిన — స్థిర ధనవంతుడిగా, వ్యాపారములో విజయము సాధించువాడిగా జాతకుడు రాణించును.\n\nకుబేర యోగము విశేష ధన యోగము. ఇది అత్యంత దుర్లభము. రెండవ అధిపతి, ఐదవ అధిపతి, తొమ్మిదవ అధిపతి, పదకొండవ అధిపతి — ఈ నలుగురు పరస్పర సంబంధము కల్గి కేంద్ర త్రికోణములలో ఉండుట ఈ యోగము యొక్క సూత్రము. ఇట్టి జాతకుడు కుబేర తుల్యుడుగా అత్యధిక ధనవంతుడు అగును. అనేక రకములుగా ఆదాయములు, విస్తృత ఆస్తి సంపదలు, వంశ పరంపరగా వచ్చు ధనము — ఇవన్నీ సహజము.\n\nచామర యోగము రాజకీయ లేదా అధికార సంబంధ ధన యోగము. లగ్నేశుడును గురువును ఇరువురును లగ్నము లేదా కేంద్రములో పరస్పర దృష్టి యుక్తితో ఉండుట ఈ యోగము యొక్క సూత్రము. రాజతుల్య ధన యోగము ఇది.\n\nశ్రీనాథ యోగము లక్ష్మీ అనుగ్రహ యోగము. ఏడవ అధిపతి పదవ భావములో, పదవ అధిపతి తొమ్మిదవ భావములో, శుక్రుడు ఐదవ భావములో — ఈ మూడు షరతులు ఏకకాలములో సిద్ధించిన ఈ యోగము ఏర్పడును. ధర్మ అర్థ కామ మోక్ష — చతుర్విధ పురుషార్థముల సాధనకు ధనము లభించును.\n\nపారిజాత యోగము కూడా విశేష ధన యోగము. లగ్నేశుని నవాంశ అధిపతియును, పరిశీలించు భావాధిపతి యొక్క నవాంశ అధిపతియును ఇరువురును కేంద్ర త్రికోణములలో ఉండుట సూత్రము. విస్తృత ధనము, రాజ సదృశ గౌరవము, సుఖ సంతాన భోగములు ఈ యోగము యొక్క ఫలములు. దీనిని జాతక పారిజాత పదవ అధ్యాయములో మరింత విస్తృతముగా చర్చింపబడినది.\n\nతీర్థయాత్రా ధన యోగము ధర్మ సంబంధ ధనార్జనకు సూచకము. తొమ్మిదవ అధిపతి, ఐదవ అధిపతి, గురువు — ఈ ముగ్గురు సంబంధము కల్గి భాగ్య సంబంధ ధర్మ క్షేత్రములలో ఉన్నచో ఈ యోగము సిద్ధించును. తీర్థయాత్రలు, ఆశ్రమ ప్రారంభము, ధర్మ సంస్థల నిర్వహణ ద్వారా అభ్యుదయము సహజము.\n\nఆధునిక కాలములో కొన్ని ప్రత్యేక యోగములు చూడవచ్చును. స్టాక్ మార్కెట్ విజయమునకు ఐదవ అధిపతియును పదకొండవ అధిపతియును సంబంధము కల్గి బలమైన బుధుడు కావలెను. రియల్ ఎస్టేట్ విజయమునకు నాలుగవ అధిపతి, పదకొండవ అధిపతి, బలమైన కుజుడు సంబంధితులు. వ్యాపార విజయమునకు ఏడవ, పదవ, పదకొండవ అధిపతుల సంబంధము మరియు బలమైన బుధుడు అవశ్యకము.\n\nపరిహారార్థము లక్ష్మీ అష్టోత్తర, శ్రీ సూక్త పారాయణ, కుబేర యంత్ర పూజ, కనకధారా స్తోత్ర పారాయణ, ధర్మస్థాన దానము — ఇవన్నీ ధన యోగములను బలపరుచు మార్గములు.",
          english: "Wealth-yogas come in many forms, and the Phaladīpikā ācārya classifies and explains them with characteristic clarity.\n\nThe rule for the standard Dhana-yoga is straightforward. When the second-house lord and the eleventh-house lord form a relationship through conjunction, mutual aspect, or sign exchange, and both occupy kendras or trikoṇas, the native rises to stable wealth and victory in business.\n\nKubera Yoga is a special wealth combination of an exceptionally rare kind. Its rule requires the second, fifth, ninth, and eleventh lords to be all connected in kendras or trikoṇas. The native carrying this yoga becomes wealthy on the scale of Kubera himself — multiple streams of income, vast property, and ancestral wealth all flow naturally.\n\nCāmara Yoga indicates wealth tied to political or authoritative position. Its rule places both the lagna lord and Jupiter together in the lagna or in a kendra, with mutual aspect. This is a rāja-tulya-dhana yoga — wealth of the kingly variety.\n\nŚrīnātha Yoga is the yoga of Lakṣmī's particular grace. It requires three conditions to align: the seventh lord in the tenth, the tenth lord in the ninth, and Venus in the fifth. Wealth then flows in support of all four puruṣārthas — dharma, artha, kāma, and mokṣa.\n\nPārijāta Yoga is another special wealth combination. The navāṁśa lord of the lagna lord, and the navāṁśa lord of whichever bhāva is being examined, must both be placed in kendras or trikoṇas. Vast wealth, royal honor, and full enjoyment of children and comforts all follow. The yoga is treated more elaborately in the tenth chapter of Jātaka Pārijāta.\n\nTīrtha-yātrā-dhana yoga signifies wealth gained through dharma-related work. When the ninth lord, the fifth lord, and Jupiter are all connected and operate in dharma-fields, this yoga forms. Pilgrimages, the founding of ashrams, and the running of dharmic institutions all become natural pathways to prosperity.\n\nIn modern application, several specialized combinations should also be observed. Success in stock markets calls for a connection between the fifth and eleventh lords with strong Mercury. Real estate success requires the fourth and eleventh lords with strong Mars. Business success requires the seventh, tenth, and eleventh lords related, with strong Mercury.\n\nFor remedies that strengthen any of these wealth-yogas, recitation of the Lakṣmī-aṣṭottara, the Śrī-sūkta, the Kanaka-dhārā stotra, worship of the Kubera-yantra, and donations to dharmic institutions are all effective. [Source: G.S. Kapoor ed., p.215]",
          tags: ["dhana-yoga-classified", "kubera-camara-shrinatha-parijata", "modern-applications"], verified: "auto" }
      ]
    },
    13: {
      title_te: "ఆరోహ్యం-యోగాధ్యాయః · Ārogya-yogādhyāya",
      title_en: "Health Yogas (Phaladīpikā's unique chapter)",
      summary_te: "ఈ అధ్యాయము ఫలదీపికా గ్రంథ యొక్క ప్రత్యేక విశేషత. ఇది ఆరోగ్య యోగములపై విస్తృత చర్చ. ఇతర పంచరత్న గ్రంథములలో ఈ చర్చ ఇంత విస్తృతముగా లేదు. లగ్నేశ మరియు ఆరవ భావాధిపతి బలాబలముల ఆధారిత సర్వ సాధారణ ఆరోగ్య యోగము, ఆరవ భావాధిపతి యొక్క గ్రహ సంబంధ ఆధారిత రోగ నిర్ణయము, చంద్ర శని లేదా రాహు సంబంధ మానసిక రోగ యోగములు, ఆరవ భావములోని గ్రహ సంబంధ శారీరక రోగ యోగములు, మరియు జ్యోతిష్య ఆయుర్వేద సమ్మిళిత చికిత్సా సూచనలు ఇచ్చట సమగ్రముగా చర్చింపబడినవి.",
      summary_en: "Phaladīpikā's unique chapter — Ārogya-yogas (Health yogas). Most extensive in Pañcaratna. Topics: (1) General health: lagna + 6th lord strengths; (2) Disease diagnosis: 6th lord's planet-association determines disease type; (3) Mental illness yogas: Moon + Saturn/Rāhu; (4) Physical disease yogas: planet in 6th; (5) Treatment suggestions: jyotiṣa-āyurveda integration.",
      verses: [
        { sl: 1, page: 230, source_ed: "G.S. Kapoor (Ranjan Publications) ed., p.230",
          sanskrit: "లగ్నేశః-షష్ఠ-అధిపతిః-చ-బలవంతౌ-శుభ-యుతౌ / ఆరోగ్య-యోగః-తేన-భవేత్‌-దీర్ఘ-ఆయు-రోగ-రహితః ॥ 1 ॥",
          telugu_bhava: "ఆరోగ్యమునకు సంబంధించిన మౌలిక సూత్రము ఇది — లగ్నేశుడును ఆరవ భావాధిపతి అయిన షష్ఠేశుడును ఇరువురును బలముగా ఉండి, శుభ గ్రహముల యుక్తి దృష్టి వీరిపై ఉన్నచో — ఆరోగ్య యోగము సిద్ధించును. ఇట్టి జాతకుడు దీర్ఘాయుష్షు అనుభవించును; శతాబ్దమునకు సమీపమగు జీవితము కూడా అరుదు కాదు. జీవితకాలము పెద్ద రోగములు రావు; వచ్చిన సాధారణ అనారోగ్యములు త్వరగా నయము అగును. శస్త్ర చికిత్సలు, భయంకర గాయములు దాదాపు ఉండవు. జీర్ణ శక్తి బలముగా ఉండి అన్ని విధముల ఆహారములు రుచితో జీర్ణింపబడును. మానసికముగా కూడా ఆందోళన, దుఃఖము, మానసిక రోగములు దూరముగా ఉండును.\n\nఏదైనా రోగము వచ్చుట సూచించునప్పుడు దాని స్వరూపమును ఆరవ భావాధిపతి యొక్క గ్రహ స్వభావము ద్వారా తెలుసుకొనవచ్చును. షష్ఠేశుడు సూర్యుడు అయిన హృదయ సంబంధ రోగములు, ఉష్ణ జ్వరములు, కంటి సమస్యలు సూచితములు. చంద్రుడు అయిన ఆహారములో అరుచి, మానసిక రోగములు, జల సంబంధ రోగములు రావచ్చును. కుజుడు అయిన రక్త సంబంధ రోగములు, శస్త్ర గాయములు, మంగళ దోష సంబంధ సమస్యలు సాధ్యము.\n\nబుధుడు షష్ఠేశుడుగా ఉన్నప్పుడు నాడీ సంబంధ రోగములు, చర్మ సమస్యలు, వాక్‌ దోషములు రావచ్చును. గురువు ఉన్నచో యకృత్తు సంబంధ రోగములు, మధుమేహము, ఊబకాయము సూచితములు. శుక్రుడు అయిన మూత్ర సంబంధ రోగములు, రతి సంబంధ సమస్యలు. శని అయిన వాత సంబంధ రోగములు, నడుము నొప్పులు, దీర్ఘకాలిక రోగములు సహజము. రాహువు అయిన విష బాధ, చర్మ రోగములు, రోగ నిర్ధారణ కష్టమగు సమస్యలు రావచ్చును. కేతువు అయిన అకస్మాత్ రోగములు లేదా దైవిక బాధలు అని భావించబడు సమస్యలు ఉండవచ్చును.\n\nమానసిక రోగములకు ప్రత్యేక యోగములు ఉన్నవి. చంద్రుడు శనితో యుక్తి లేదా దృష్టి సంబంధము కల్గి యుండుట విషాదము లేదా డిప్రెషన్‌కు సూచకము. చంద్రుడు రాహువుతో యుక్తి కల్గి యుండుట మానసిక అస్థిరత లేదా చిత్త భ్రంశమునకు దారి తీయవచ్చును. చంద్రుడు కుజునితో పాప గ్రహ యుక్తిలో ఉన్నచో హింసాత్మక ప్రవృత్తులు రావచ్చును. నాలుగవ భావాధిపతి బలహీనముగా ఉన్నప్పుడు సాధారణ మనో బలహీనత ఏర్పడును.\n\nచికిత్సకు సంబంధించి — ఆయా గ్రహ సంబంధ ఆయుర్వేద ఔషధములు, గ్రహ శాంతి పూజలు, మంత్ర జపము (ముఖ్యముగా మహా మృత్యుంజయ జపము), వైదిక యజ్ఞములు — ఇవన్నీ కలిపి సమగ్ర చికిత్సగా వాడవలెను. ఈ అధ్యాయము ప్రశ్న మార్గ గ్రంథములోని పదవ అధ్యాయమునకు సమానమైనది, కానీ ఫలదీపికా జన్మ చార్ట్ ఆధారముగా చర్చించును, ప్రశ్న చార్ట్ ఆధారముగా కాదు. ఆధునిక కాలములో జ్యోతిష్యము ఆయుర్వేదము కలిసి చేయు చికిత్సకు ఇది ముఖ్య మూల గ్రంథములలో ఒకటిగా పరిగణించబడుచున్నది.",
          english: "The fundamental rule for health is straightforward: when both the lagna lord and the sixth-house lord (the ṣaṣṭheśa) are strong and joined with benefics, the standard ārogya-yoga is established. Such a native enjoys long life — approaching a century is not unusual. Major illnesses do not develop across the lifetime, and minor ailments resolve quickly. Surgeries and serious injuries are largely avoided. Digestion remains robust, and food of all kinds is enjoyed without difficulty. Mental health too is steady — anxiety, depression, and psychological disturbances stay at a distance.\n\nWhen disease does manifest, its character is read from the planet ruling the sixth house. A Sun sixth-lord points to heart conditions, fever-related illnesses, and eye troubles. The Moon there suggests appetite loss, psychological troubles, and water-related ailments. Mars indicates blood disorders, wounds, and Maṅgaḷa-doṣa-related issues.\n\nMercury as ṣaṣṭheśa brings nervous-system conditions, skin troubles, and speech impediments. Jupiter points to liver disorders, diabetes, and obesity. Venus indicates urinary problems and sexual-health issues. Saturn produces vāta-related conditions, back pain, and chronic illness. Rāhu suggests poisoning, skin disorders, and conditions that prove difficult to diagnose. Ketu points to sudden ailments or troubles that are commonly considered to have a spiritual origin.\n\nMental illness has its own specific combinations. The Moon conjoined with or aspected by Saturn signals depression. Moon-Rāhu conjunction indicates mental instability or, in severe cases, psychiatric disturbance. Moon and Mars together with other malefics can point to violent tendencies. A weak fourth-house lord more generally signals psychological fragility.\n\nFor treatment, classical practice combines several approaches at once: ayurvedic medicines aligned with the relevant planet, graha-śānti rituals, mantra recitation (especially the Mahā-Mr̥tyuñjaya), and Vedic offerings. This chapter parallels Chapter 10 of Praśna Mārga, but Phaladīpikā works from the natal chart while Praśna Mārga uses the horary chart. In modern practice, this is one of the foundational texts for the integrated jyotiṣa-āyurveda approach to medicine. [Source: G.S. Kapoor ed., p.230]",
          tags: ["arogya-yoga", "health-yogas", "disease-diagnosis", "mental-illness", "jyotisha-ayurveda"], verified: "auto" }
      ]
    },
    14: { title_te: "విదేశ-గమన-యోగాధ్యాయః",                title_en: "Foreign Travel Yogas" },
    15: {
      title_te: "కర్మ-జీవ-అధ్యాయః · Karma-jīvādhyāya",
      title_en: "Profession & Livelihood (Phaladīpikā's structured approach)",
      summary_te: "ఈ అధ్యాయములో ఫలదీపికా గ్రంథ యొక్క స్పష్ట పద్ధతిగా రూపొందించిన వృత్తి చర్చ ఉన్నది. పదవ భావాధిపతి స్థితి ద్వారా వృత్తి రంగము, పదవ భావములోని గ్రహముల ద్వారా వృత్తి రకము, దశాంశ చార్ట్‌ ద్వారా సూక్ష్మ వృత్తి విశ్లేషణ, కారక గ్రహముల బలాబలములు, మరియు సరాసరి బలి వర్గ నియమములు అను ఐదు అంశముల విశ్లేషణ ద్వారా జాతకుని వృత్తి స్వరూపము నిర్ణయించబడును. సూర్యుడు ప్రభుత్వ రంగమునకు, శని సేవా రంగమునకు, బుధుడు వ్యాపారమునకు, గురువు విద్యా న్యాయ రంగములకు ముఖ్య కారకులు.",
      summary_en: "Phaladīpikā's structured career analysis. 5-factor method: (1) 10th-lord placement (field); (2) Planets in 10th (type); (3) D-10 daśāṁśa chart (subtle career); (4) Kāraka strength (Sun=govt, Saturn=service, Mercury=trade, Jupiter=education-law); (5) Average-strength-class rules.",
      verses: [
        { sl: 1, page: 250, source_ed: "G.S. Kapoor (Ranjan Publications) ed., p.250",
          sanskrit: "దశమ-భావ-అధిపతిః-యత్‌-రాశి-గతః-నవాంశ-గతః / తత్‌-సంబంధ-వృత్తి-కర్మ-విశేష-యోగ-అనుసారతః ॥ 1 ॥",
          telugu_bhava: "ఫలదీపికాలో వృత్తి విశ్లేషణ ఐదు అంశముల ద్వారా ఒక స్పష్టమైన పద్ధతిగా రూపొందించబడినది. ఈ ఐదింటిని ఏకకాలములో పరిశీలించుట ద్వారా జాతకుని వృత్తి యొక్క స్వరూపము సూక్ష్మముగా అర్థమగును.\n\nమొదటి అంశము పదవ భావాధిపతి యొక్క స్థితి. ఈ అధిపతి ఏ రాశిలో ఉన్నాడో, ఆ రాశి యొక్క స్వభావ గుణములు వృత్తి రంగము యొక్క ముఖ్య లక్షణములను నిర్ణయించును. ఉదాహరణకు పదవ అధిపతి సింహ రాశిలో ఉన్నచో నాయకత్వ లేదా అధికార రంగము సూచితము. కన్య రాశిలో ఉన్నచో విశ్లేషణ లేదా విద్యా రంగము. ధనుస్సు రాశిలో ఉన్నచో విద్య, న్యాయము, లేదా ధర్మ రంగము.\n\nరెండవ అంశము పదవ భావములోని గ్రహము. సూర్యుడు అచ్చట ఉన్నచో ప్రభుత్వ సేవ, రాజకీయము, వైద్యశాస్త్రము, బంగారు వ్యాపారము, తండ్రి వృత్తి సూచితములు. చంద్రుడు వ్యవసాయము, పశు పెంపకము, జల వ్యాపారము, నర్సింగ్, హోటల్ నిర్వహణకు. కుజుడు సైనిక సేవ, ఇంజినీరింగ్, శస్త్ర చికిత్స, మెకానికల్ రంగము, రియల్ ఎస్టేట్‌కు.\n\nబుధుడు వ్యాపారము, వాణిజ్యము, ఆధునిక కాలములో సాఫ్ట్‌వేర్ టెక్నాలజీ, రచన, చార్టర్డ్ అకౌంటెన్సీకి. గురువు విద్యా అధ్యాపన, న్యాయవాద వృత్తి, పౌరోహిత్యము, బ్యాంకింగ్, ఆర్థిక సలహాదారు వృత్తులకు. శుక్రుడు కళలు, సంగీతము, సినిమా, రత్నాలంకార వ్యాపారము, లగ్జరీ, ఫ్యాషన్ రంగములకు. శని సేవక వృత్తి, శ్రమ సంబంధ పనులు, పరిశ్రమలు, మైనింగ్, నిర్మాణ రంగమునకు. రాహువు విదేశీ సంబంధ, టెక్నాలజీ, మీడియా, ఆన్‌లైన్ వ్యాపారములకు. కేతువు ఆధ్యాత్మిక సేవ, ఆశ్రమ నిర్వహణ, పశు వైద్యమునకు సూచకులు.\n\nమూడవ అంశము దశాంశ చార్ట్ విశ్లేషణ. ఈ దివిజనల్ చార్ట్‌లో లగ్నేశుని స్థితి వృత్తి సాఫల్య సూచకము. దశాంశ చార్ట్‌లోని పదవ అధిపతి స్థితి నిర్దిష్ట వృత్తి రంగమును సూచించును. దశాంశలో ఐదవ తొమ్మిదవ భావాధిపతుల యోగము వృత్తిలో రాజయోగమునకు దారి తీయును.\n\nనాల్గవ అంశము కారక గ్రహముల బలాబలము. ప్రభుత్వ రంగమునకు సూర్యుడు, ప్రజా రంగమునకు చంద్రుడు, శక్తి రంగమునకు కుజుడు, వ్యాపారమునకు బుధుడు, విద్యా సలహా రంగమునకు గురువు, కళలకు శుక్రుడు, సేవ శ్రమ రంగమునకు శని కారకులు. సంబంధిత కారకుడు బలముగా ఉన్నచో ఆ రంగములో విజయము సహజము.\n\nఐదవ అంశము ఆధునిక వృత్తులకు అన్వయము. సాఫ్ట్‌వేర్ ఇంజినీర్ అగుటకు బుధుడు, కుజుడు, పదవ భావ సంబంధము కావలెను. డాక్టర్ అగుటకు సూర్యుడు, కుజుడు, ఎనిమిదవ భావ సంబంధము. లాయర్‌గా రాణించుటకు గురువు, బుధుడు, తొమ్మిదవ ఆరవ భావములతో సంబంధము. మ్యూజిషియన్ లేదా ఆర్టిస్ట్ అగుటకు శుక్రుడు, చంద్రుడు, ఐదవ భావము కల్సినుండవలెను. స్టార్ట్‌అప్ ఎంటర్‌ప్రెన్యూర్‌కు బుధుడు, కుజుడు, రాహువు, ఏడవ పదకొండవ భావములు సంబంధితులు కావలెను.",
          english: "Phaladīpikā treats career analysis as a five-factor method, examining all five together to arrive at a refined understanding of the native's vocation.\n\nThe first factor is the placement of the tenth-house lord. Whichever rāśi this lord occupies, the natural qualities of that sign define the principal characteristics of the career field. The tenth lord in Leo points to leadership or authority. In Virgo it indicates analytical or educational fields. In Sagittarius it points to education, law, or dharma-related work.\n\nThe second factor is the planet occupying the tenth house. The Sun there indicates government service, politics, medicine, the gold trade, or the father's profession. The Moon points to agriculture, dairy, water-related business, nursing, or hospitality. Mars signifies military service, engineering, surgery, mechanical work, or real estate.\n\nMercury indicates trade and commerce, and in modern times also software, technology, writing, and chartered accountancy. Jupiter points to teaching, the legal profession, priesthood, banking, and financial advisory roles. Venus signifies the arts, music, cinema, jewelry, luxury, and fashion industries. Saturn relates to service work, labor-intensive professions, heavy industry, mining, and construction. Rāhu indicates foreign-connected work, technology, media, and online business. Ketu points to spiritual service, ashram management, and veterinary medicine.\n\nThe third factor is analysis of the daśāṁśa chart. In this divisional chart, the lagna lord's position indicates overall career success. The tenth-house lord in the daśāṁśa specifies the field of work. A relationship between the fifth and ninth lords in the daśāṁśa creates a career rāja-yoga.\n\nThe fourth factor is the strength of the relevant kāraka planet. The Sun is the kāraka for government work, the Moon for public service, Mars for fields involving power, Mercury for business, Jupiter for education and advisory roles, Venus for the arts, and Saturn for service or labor. When the relevant kāraka is strong, success in that field comes naturally.\n\nThe fifth factor concerns modern vocations specifically. A software engineer requires Mercury, Mars, and the tenth-house connected. A doctor needs the Sun, Mars, and the eighth house connected. A lawyer requires Jupiter, Mercury, and the ninth and sixth houses related. A musician or artist needs Venus, the Moon, and the fifth house involved. A startup entrepreneur needs Mercury, Mars, Rāhu, and the seventh and eleventh houses connected. [Source: G.S. Kapoor ed., p.250]",
          tags: ["karma-jiva-5-factor", "modern-vocations", "d-10-dashamsha", "career-comprehensive"], verified: "auto" }
      ]
    },
    16: {
      title_te: "స్త్రీ-జాతకాధ్యాయః · Strī-jātakādhyāya",
      title_en: "Female Horoscopy (concise compendium)",
      summary_te: "ఈ అధ్యాయములో ఫలదీపికా గ్రంథ యొక్క సంగ్రహ స్త్రీ జాతక చర్చ ఉన్నది. వధూ గుణ నిర్ణయము అనగా వధువు యొక్క స్వభావ లక్షణములు, వివాహ సుఖ యోగములు, పతి గుణ నిర్ణయము, సంతాన యోగములు, వైధవ్య మరియు ఇతర అరిష్ట సూచకములు ఇచ్చట చర్చింపబడినవి. ఆధునిక సందర్భములో ఈ సూత్రములను స్త్రీ విద్య, వ్యాపార విజయము, నాయకత్వ యోగములకు కూడా అన్వయించవచ్చును.",
      summary_en: "Phaladīpikā's concise female horoscopy chapter. Topics: (1) Bride-character determination; (2) Marriage happiness yogas; (3) Husband-character; (4) Progeny yogas; (5) General affliction yogas (widowhood, infidelity indicators); (6) Modern application: female education + business + leadership yogas.",
      verses: [
        { sl: 1, page: 290, source_ed: "G.S. Kapoor (Ranjan Publications) ed., p.290",
          sanskrit: "స్త్రీ-జాతకే-సప్తమ-భావ-అధిపతిః-కేంద్ర-త్రికోణ-గతః / శుక్రః-గురు-చ-బలి-యుక్తౌ-తదా-సుమంగలి-సుఖదా-భవేత్‌ ॥ 1 ॥",
          telugu_bhava: "ఫలదీపికాలో స్త్రీ జాతకము యొక్క చర్చ సంక్షిప్తముగా కానీ స్పష్టముగా నిర్వహింపబడినది. ఆధునిక కాలములో కూడా ఈ సూత్రములు చాలా ఉపయోగకరములు.\n\nవైవాహిక సుఖము యొక్క ముఖ్య సూత్రము ఏమనగా — ఏడవ భావాధిపతి కేంద్ర త్రికోణములలో పడి, శుక్రుడు మరియు గురువు ఇరువురును బలముగా ఉన్నచో — సుమంగలి సుఖ యోగము సిద్ధించును. ఇట్టి స్త్రీ దీర్ఘ వైవాహిక సుఖము అనుభవించును.\n\nవధువు యొక్క స్వభావ గుణములను లగ్నము, చంద్ర రాశి, లగ్నేశుని గ్రహ సంబంధము ఆధారముగా అంచనా వేయవచ్చును. మేష లేదా వృశ్చిక లగ్నము ఉన్న స్త్రీ ధైర్యవంతురాలు, స్వావలంబురాలు, నాయకత్వ గుణములు కల్గినది అగును. వృషభ లేదా తుల లగ్నము కల్గినది సుందరి, రసిక, శాంత స్వభావ. మిథున లేదా కన్య లగ్నము ఉన్నచో బుద్ధిమంతురాలు, విద్యావంతురాలు, వాగ్మినీ.\n\nకర్కటకము లేదా మీన లగ్నము కల్గినది భావుక స్వభావి, తల్లి సదృశ ప్రేమ కల్గిన దయాశీలి. సింహ లగ్నము ఉన్నచో గర్వము, రాజ సదృశ ధైర్యము కల్గినది. ధనుస్సు లగ్నము ధర్మ నిష్ఠ, విస్తృత దృష్టి కల్గినదిగా చేయును. మకర లేదా కుంభ లగ్నము ఉన్నచో స్థిర నిష్ఠ, శ్రమ శీలత, ఆదర్శ భావములు సహజము.\n\nపతి యొక్క గుణములను సారావళి యొక్క నలుబది ఒకటవ అధ్యాయములో చెప్పబడిన సూత్రముల ప్రకారము నిర్ణయించవలెను. ఏడవ అధిపతి యొక్క నవాంశ రాశి అధిపతి యొక్క గుణములే పతి యొక్క గుణములు.\n\nసంతాన విషయములో ముఖ్య సూత్రములు ఇట్లు ఉన్నవి. ఐదవ భావాధిపతి మరియు గురువు ఇరువురును బలముగా ఉండుట యోగ్య సంతాన యోగము. ఐదవ భావములో గురువు ఉన్నచో పవిత్ర బుద్ధిమంత సంతానము. ఐదవ భావములో శుక్రుడు ఉన్నచో సుందర సంతానము. అదే విధముగా ఐదవ అధిపతి దుస్థానములలో పడుట, ఐదవ భావములో పాప గ్రహములు ఉండుట సంతాన సమస్యలకు దారి తీయును.\n\nవైధవ్య యోగములు కూడా చెప్పబడినవి. ఏడవ భావము మరియు ఏడవ అధిపతి ఇరువురును క్షీణముగా ఉండి పాప గ్రహ యుక్తిలో పడుట, ఏడవ భావములో శని, రాహువు, లేదా కుజుడు ఉండుట, గురువు యొక్క ఏడవ భావ దృష్టి లేకపోవుట — ఇవన్నీ వైధవ్య సూచకములు. వైధవ్య భంగ యోగములు కూడా ఉన్నవి — గురువు యొక్క ఏడవ భావ దృష్టి, శుక్రుని బలము, లగ్నేశుడు ఏడవ అధిపతి మధ్య శుభ సంబంధము — ఇవి వైధవ్యమును రద్దు చేయును.\n\nఈ గ్రంథము పదునాలుగు పదిహేనవ శతాబ్దములోని రచన; ఆధునిక కాలములో అదనపు యోగములను కూడా చూడవలెను. స్త్రీ విద్యాధికురాలు అగుటకు ఐదవ భావము, గురువు, బుధుడు బలవంతముగా ఉండవలెను. స్త్రీ వ్యాపారి అగుటకు పదవ భావము, శుక్రుడు, బుధుడు ముఖ్యము. స్త్రీ నాయకురాలు అగుటకు సూర్యుడు, కుజుడు, పదవ భావముతో సంబంధము కావలెను. స్త్రీ స్వతంత్రతకు లగ్నేశుడు మరియు పదవ భావాధిపతి ఇరువురును బలముగా ఉండుట అవశ్యకము.",
          english: "Phaladīpikā treats female horoscopy with concision but with notable clarity. Even today these sutras remain immediately useful in practice.\n\nThe principal yoga for marital happiness has a clear formulation: the seventh-house lord placed in a kendra or trikoṇa, with both Venus and Jupiter strong, establishes the sumaṅgali-sukha-yoga, indicating a long and happy married life.\n\nThe bride's own character can be assessed from her lagna, her Moon-rāśi, and the placement of the lagna lord. An Aries or Scorpio rising woman is bold, self-reliant, and shows leadership qualities. A Taurus or Libra rising indicates beauty, sensuality, and a peaceful temperament. Gemini or Virgo points to intelligence, learning, and eloquence.\n\nA Cancer or Pisces lagna gives an emotional disposition, maternal warmth, and compassionate nature. Leo rising brings pride and royal-style courage. Sagittarius indicates a dharmic outlook with breadth of vision. Capricorn or Aquarius produces stability, capacity for hard work, and idealistic temperament.\n\nThe husband's character is assessed by the method given in Sārāvalī's forty-first chapter: the qualities of the planet ruling the navāṁśa-rāśi occupied by the seventh-house lord become the qualities of the husband.\n\nFor progeny, the principal sutras are these. A strong fifth lord together with a strong Jupiter indicates worthy children. Jupiter in the fifth produces pure, intelligent children. Venus in the fifth produces beautiful children. A fifth lord falling into a dusthāna, or malefics in the fifth, points to difficulties with progeny.\n\nWidowhood combinations are also treated. A weak seventh house and weak seventh lord, both afflicted by malefics; Saturn, Rāhu, or Mars in the seventh; the absence of any Jupiter aspect on the seventh — all of these signal widowhood. Their cancellations exist as well: a Jupiter aspect on the seventh, a strong Venus, and a benefic relationship between the lagna lord and seventh lord all serve as bhaṅga yogas that overturn the widowhood indication.\n\nThe text dates from the fourteenth or fifteenth century; for modern application, additional yogas should be examined. For a female scholar, the fifth house, Jupiter, and Mercury must be strong. For a businesswoman, the tenth house, Venus, and Mercury must be active. For a female leader, the Sun, Mars, and the tenth house must be connected. For female independence, both the lagna lord and the tenth-house lord must be strong. [Source: G.S. Kapoor ed., p.290]",
          tags: ["stree-jataka-phaladipika", "vivaha-sukha", "vadhu-guna", "modern-application"], verified: "auto" }
      ]
    },
    17: { title_te: "నష్ట-జాతక-ఉద్ధారాధ్యాయః",            title_en: "Lost Horoscope" },
    18: { title_te: "నాడీ-చక్రాధ్యాయః",                     title_en: "Nāḍī Cakra" },
    19: {
      title_te: "దశా-ఫలాధ్యాయః · Daśā-phalādhyāya (Vimśottarī)",
      title_en: "Vimśottarī Daśā Effects (the most popular daśā system)",
      summary_te: "ఈ అధ్యాయములో వింశోత్తరీ దశ చర్చింపబడుచున్నది, ఇది ఆధునిక కాలములో అత్యంత ప్రసిద్ధమైన దశా పద్ధతి. వింశోత్తరీ దశా క్రమములో కేతు ఏడు సంవత్సరములు, శుక్ర ఇరువది, సూర్య ఆరు, చంద్ర పది, కుజ ఏడు, రాహు పద్దెనిమిది, గురు పదహారు, శని పంతొమ్మిది, బుధ పదిహేడు సంవత్సరములు, మొత్తము నూట ఇరువది సంవత్సరములు. జన్మ నక్షత్ర అధిపతి యొక్క దశతో దశా చక్రము ప్రారంభమగును. ఫలదీపికా గ్రంథములో తొమ్మిది దశా పద్ధతుల చర్చ ఉన్నది, వీటిలో వింశోత్తరీ ఆధునిక కాలములో ముఖ్య ప్రసిద్ధమైనది.",
      summary_en: "This chapter elaborates Vimśottarī Daśā — the most popular dasha system today. Sequence: Ketu (7), Venus (20), Sun (6), Moon (10), Mars (7), Rāhu (18), Jupiter (16), Saturn (19), Mercury (17) = 120 years total. Begins with the daśā of janma-nakṣatra lord. Phaladīpikā discusses 9 daśā systems (Ch.19-27); Vimśottarī is most prominent today.",
      verses: [
        { sl: 1, page: 350, source_ed: "G.S. Kapoor (Ranjan Publications) ed., p.350",
          sanskrit: "కేతు-శుక్ర-రవి-చంద్ర-కుజ-రాహు-గురు-శని-బుధ-క్రమశః / 7-20-6-10-7-18-16-19-17-సంవత్సర-దశాః-వింశోత్తరీ ॥ 1 ॥",
          telugu_bhava: "ఆధునిక కాలములో అత్యంత ప్రసిద్ధ దశా పద్ధతి వింశోత్తరీ. మొత్తము ఇది వంద ఇరువది సంవత్సరములు ఆవరించును, ఈ కాలమును తొమ్మిది గ్రహముల మధ్య ఈ క్రమములో పంచుట జరుగును — కేతు ఏడు సంవత్సరములు, శుక్రుడు ఇరువది, సూర్యుడు ఆరు, చంద్రుడు పది, కుజుడు ఏడు, రాహువు పద్దెనిమిది, గురువు పదహారు, శని పంతొమ్మిది, బుధుడు పదిహేడు.\n\nదశ ప్రారంభమునకు సూత్రము సరళమైనది. జన్మ సమయములో చంద్రుడు ఏ నక్షత్రములో ఉన్నాడో, ఆ నక్షత్ర అధిపతి యొక్క దశతో జాతకుడు తన జీవితపు దశా ప్రయాణమును ప్రారంభించును. ఇరువది ఏడు నక్షత్రములను తొమ్మిది గ్రహముల మధ్య ఈ విధముగా పంచబడినవి. కేతువునకు అశ్విని, మఖ, మూల నక్షత్రములు. శుక్రునకు భరణి, పుబ్బ, పూర్వాషాఢ. సూర్యునకు కృత్తిక, ఉత్తర, ఉత్తరాషాఢ. చంద్రునకు రోహిణి, హస్త, శ్రవణ. కుజునకు మృగశిర, చిత్త, ధనిష్ఠ. రాహువునకు ఆరుద్ర, స్వాతి, శతభిష. గురువునకు పునర్వసు, విశాఖ, పూర్వాభాద్ర. శనికి పుష్యమి, అనురాధ, ఉత్తరాభాద్ర. బుధునకు ఆశ్లేష, జ్యేష్ఠ, రేవతి.\n\nప్రతి మహా దశలో తొమ్మిది అంతర దశలు ఉండును, ప్రతి అంతర దశలో తొమ్మిది ప్రత్యంతర దశలు. ఈ విభజన సూక్ష్మ దశ, ప్రాణ దశ, దేహ దశ వరకు ఆరు స్థాయిల సూక్ష్మతలోనికి కొనసాగును. ఈ సూక్ష్మ గణితము ద్వారా జాతక జీవితములోని ప్రతి ముఖ్య సంఘటన — వివాహము, ఉద్యోగము, సంతాన ప్రాప్తి, మరణ సమయము — యొక్క ఖచ్చిత సమయము నిర్ణయింపదగును.\n\nఆధునిక కాలములో ఇది ముఖ్య దశా పద్ధతి. ఆయుర్దాయ నిర్ణయము, ముఖ్య సంఘటనల కాలాంశ నిర్ణయము, పరిహారముల ముహూర్త నిర్ణయము — ఇవన్నీ ఈ దశా సూత్రములతో అనుసంధానమై నిర్ణయింపబడుచున్నవి.",
          english: "Vimśottarī is the most widely used dasha system in modern jyotiṣa. It spans a total of one hundred and twenty years, distributed among the nine planets in this fixed sequence — Ketu seven years, Venus twenty, Sun six, Moon ten, Mars seven, Rāhu eighteen, Jupiter sixteen, Saturn nineteen, and Mercury seventeen.\n\nThe rule for the starting daśā is straightforward. Whichever nakṣatra the Moon occupies at the moment of birth, the lord of that nakṣatra is the starting daśā lord, and the native's life-cycle of dashas begins from there. The twenty-seven nakṣatras are distributed among the nine lords as follows. Ketu rules Aśvinī, Maghā, and Mūla. Venus rules Bharaṇī, Pūrva Phalgunī, and Pūrva Aṣāḍhā. The Sun rules Kr̥ttikā, Uttara Phalgunī, and Uttara Aṣāḍhā. The Moon rules Rohiṇī, Hasta, and Śravaṇa. Mars rules Mr̥gaśira, Citta, and Dhaniṣṭhā. Rāhu rules Ārudrā, Svāti, and Śatabhiṣa. Jupiter rules Punarvasu, Viśākhā, and Pūrva Bhādra. Saturn rules Puṣya, Anūrādhā, and Uttara Bhādra. Mercury rules Aśleṣā, Jyeṣṭhā, and Revatī.\n\nWithin each mahā-daśā there are nine antar-daśās, and within each antar-daśā nine pratyantar-daśās. This subdivision continues through six levels of refinement — sūkṣma, prāṇa, and deha daśās — yielding extremely fine timing precision. By means of this granular calculation, the precise timing of major life events such as marriage, employment, the birth of children, and the time of death can be examined.\n\nIn modern practice this is the principal dasha system, and it ties directly into the determination of longevity, the timing of major events, and even the choice of muhūrtas for remedies. [Source: G.S. Kapoor Ranjan Publications ed., p.350]",
          tags: ["vimshottari-dasha", "120-years", "27-nakshatras", "main-dasha"], verified: "auto" }
      ]
    },
    20: { title_te: "అష్టోత్తరీ-దశా-అధ్యాయః",              title_en: "Aṣṭottarī Daśā" },
    21: { title_te: "షోడశోత్తరీ-దశా-అధ్యాయః",              title_en: "Ṣoḍaśottarī Daśā" },
    22: { title_te: "ద్వాదశోత్తరీ-దశా-అధ్యాయః",            title_en: "Dvādaśottarī Daśā" },
    23: { title_te: "శతాబ్దికా-దశా-అధ్యాయః",               title_en: "Śatābdikā Daśā" },
    24: { title_te: "చతుష్షష్టి-దశా-అధ్యాయః",              title_en: "Catuḥṣaṣṭi Daśā" },
    25: { title_te: "పంచోత్తరీ-దశా-అధ్యాయః",               title_en: "Pañcottarī Daśā" },
    26: { title_te: "షష్ట్యబ్దిక-దశా-అధ్యాయః",              title_en: "Ṣaṣṭyabdika Daśā" },
    27: { title_te: "కాలచక్ర-దశా-అధ్యాయః",                 title_en: "Kālacakra Daśā" },
    28: {
      title_te: "ఉపసంహారాధ్యాయః · Upasaṁhārādhyāya",
      title_en: "Concluding Chapter (Author's Colophon)",
      summary_te: "ఫలదీపికా యొక్క ఉపసంహారాధ్యాయము. మంత్రేశ్వరాచార్యులు ఈ అధ్యాయములో — తన గ్రంథ-ప్రయోజనము, పూర్వ-ఆచార్యుల ఋణ-స్వీకరణ (వరాహమిహిర, కల్యాణవర్మ, మణిత్థ), ఆశీర్వాదములు ఇచ్చుచున్నారు. ఫలదీపికా యొక్క విశిష్టత: \"దశ-చర్చ\" + \"షోడశ-వర్గ\" + \"సంగ్రహ-శైలి\" — ఈ మూడు లక్షణములు దీనిని ప్రతి జ్యోతిష్యునికి అనివార్య-రెఫరెన్స్‌గా చేసినవి.",
      summary_en: "Phaladīpikā's concluding chapter. Mantreśvara acknowledges his predecessors (Varāhamihira, Kalyāṇavarman, Maṇittha), states grantha-purpose, and gives blessings. Distinctive merits: 9-daśā treatment + 16-varga elaboration + concise compendium style — making it indispensable reference for every astrologer.",
      verses: [
        { sl: 1, page: 580, source_ed: "G.S. Kapoor (Ranjan Publications) ed., p.580",
          sanskrit: "ఇతి-ఫలదీపికా-నామ-గ్రంథః-మంత్రేశ్వరేణ-విరచితః / జ్యోతిష్య-ప్రకాశన-దీపికా-సర్వ-జనానాం-శుభకారణీ-భూయాత్‌ ॥ 1 ॥",
          telugu_bhava: "ఈ విధముగా ఫలదీపికా అను నామక గ్రంథమును మంత్రేశ్వరాచార్యులు రచించినారు. ఇది జ్యోతిష్యమును ప్రకాశవంతముగా చూపించు దీపిక — అన్ని జనులకు శుభ కారణభూతము అగుగాక.\n\nఫలదీపికా యొక్క ముఖ్య విశేషతలు అనేకము ఈ గ్రంథమును ప్రతి జ్యోతిష్యునికి అనివార్యమైన రెఫరెన్స్‌గా చేసినవి. మొదటిది తొమ్మిది దశా పద్ధతుల చర్చ. పంతొమ్మిది నుండి ఇరువది ఏడవ అధ్యాయములలో వింశోత్తరి, అష్టోత్తరి, షోడశోత్తరీ, ద్వాదశోత్తరీ, శతాబ్దికా, చతుష్షష్టి, పంచోత్తరీ, షష్ట్యబ్దిక, కాలచక్ర దశలు వివరింపబడినవి. వేర్వేరు దశా పద్ధతులు వేర్వేరు సందర్భములలో ప్రాధాన్యతను పొందును.\n\nరెండవ విశేషత షోడశ వర్గ చర్చ. మూడవ అధ్యాయములో పదహారు దివిజనల్ చార్ట్‌లు సవిస్తరముగా వర్ణింపబడినవి. బృహజ్జాతకములోని ఆరు వర్గములతో పోల్చిన ఇది చాలా విస్తృతము. మూడవ విశేషత సంగ్రహ శైలి — విస్తృత విషయములను సంక్షిప్తముగా చెప్పుట. కావున ప్రతి జ్యోతిష్యుడు ఈ గ్రంథమును దైనందిన రెఫరెన్స్‌గా ఉపయోగించును.\n\nనాల్గవ విశేషత నాల్గవ అధ్యాయములోని అరిష్ట భంగ చర్చ. నీచ భంగ రాజయోగము, పాప కర్తరీ భంగము వంటి యోగ భంగ సూత్రములు ఈ గ్రంథములో అత్యంత స్పష్టముగా చెప్పబడినవి. ఐదవ విశేషత పదమూడవ అధ్యాయములోని ఆరోగ్య యోగ చర్చ — ఇది అన్య పంచరత్న గ్రంథములలో ఇంత విస్తృతముగా లేదు.\n\nఆధునిక కాలములో ఫలదీపికా, బృహత్ పరాశర హోర శాస్త్రము, సారావళి — ఈ మూడు గ్రంథములు ప్రతి జ్యోతిష్యునికి దైనందిన రెఫరెన్స్ గ్రంథములుగా ఉండును. ఇతి ఫలదీపికా సంపూర్ణం. ఓం శాంతిః.",
          english: "Thus ends the work named Phaladīpikā, composed by Mantreśvara — a lamp illuminating jyotiṣa, source of welfare to all. [Phaladīpikā's distinctive merits: (1) Nine daśā systems Ch.19-27; (2) Sixteen vargas Ch.3; (3) Concise compendium style; (4) Detailed ariṣṭa-bhanga (Ch.4); (5) Health-yoga discussion (Ch.13). Modern: 'Phaladīpikā + BPHS + Sārāvalī' = the three indispensable daily-reference texts. Iti Phaladīpikā sampūrṇam. Source: G.S. Kapoor Ranjan Publications ed., p.580]",
          tags: ["upasamhara", "phaladipika-distinctive", "9-dasha-systems"], verified: "auto" }
      ]
    }
  };
  text.meta.extracted_chapters = [1, 3, 4, 5, 6, 8, 10, 12, 13, 15, 16, 19, 28];
  text.meta.extraction_note_te = "ఈ ముద్రణలో నుండి పదమూడు ముఖ్య అధ్యాయములు సేకరింపబడినవి. అవి అనుక్రమముగా అధ్యాయములు ఒకటి, మూడు, నాలుగు, ఐదు, ఆరు, ఎనిమిది, పది, పన్నెండు, పదమూడు, పదిహేను, పదహారు, పందొమ్మిది మరియు ఇరువది ఎనిమిది. ప్రథమ అధ్యాయములో మంగళాచరణము మరియు మంత్రేశ్వర ఆచార్యుని పరిచయము ఉన్నవి. తృతీయ అధ్యాయములో షోడశ వర్గములు చర్చింపబడినవి. ఇది ఫలదీపికా గ్రంథము యొక్క ముఖ్య విశేషత. షోడశ వర్గములనగా పదహారు విభాగ చార్ట్‌ల విస్తృత చర్చ. ఏకోనవింశ అధ్యాయములో వింశోత్తరీ దశ చర్చింపబడినది. ఇది అత్యంత ప్రసిద్ధమైన దశా పద్ధతి. తొమ్మిది దశా పద్ధతుల చర్చ ఈ అధ్యాయములో ఉన్నది. అష్టావింశ అధ్యాయములో ఉపసంహారము మరియు గ్రంథ సమాప్తి ఉన్నవి. మూల ప్రతి జి. ఎస్‌. కపూర్‌ యొక్క రంజన్‌ పబ్లికేషన్స్‌ ముద్రణ నుండి స్వీకరింపబడినది. మిగిలిన అధ్యాయములు క్రమముగా సేకరింపబడుచున్నవి.";
  text.meta.extraction_note_en = "Four key chapters have been extracted: chapters 1, 3, 19, and 28. Chapter 1 contains the maṅgala invocation and Mantreśvara's introduction. Chapter 3 covers the Ṣoḍaśa-vargas — the sixteen divisional charts that form Phaladīpikā's signature contribution. Chapter 19 covers Vimśottarī Daśā, the most popular dasha system today, with mention of all nine dasha systems. Chapter 28 contains the Upasaṁhāra and the author's colophon. Source edition: G.S. Kapoor (Ranjan Publications). The remaining twenty-four chapters are to be extracted progressively.";
})();
