/* ============================================================
   SĀRĀVALĪ · కల్యాణవర్మ · c. 7th–8th century CE
   55 chapters

   Primary edition reference:
     R. Santhanam (Ranjan Publications, 2 volumes)
     Original Sanskrit + English translation
     Also: Pt. Sitaram Jha Hindi commentary

   Manuscript source:
     Pre-medieval Indian library manuscripts;
     Modern critical editions exist
   ============================================================ */
"use strict";

(function(){
  if (!window.GRANTHAS) { console.warn('granthas.js must load before saravali-data.js'); return; }
  const text = window.GRANTHAS.texts["saravali"];
  if (!text) { console.warn('saravali not in GRANTHAS catalog'); return; }

  // === Sārāvalī 55-chapter authoritative list ===
  text.chapters = {
    1: {
      title_te: "మంగళాచరణ-గ్రంథ-ప్రయోజన-అధ్యాయః · Maṅgala-ācaraṇādhyāya",
      title_en: "Maṅgala-ācaraṇa & Purpose of the Treatise",
      summary_te: "ఈ ప్రథమ అధ్యాయములో — కల్యాణవర్మాచార్యులు ఇష్టదేవతా-స్తుతి, పూర్వ-ఆచార్యుల (వరాహమిహిర, పరాశర, యవనాచార్య) ప్రశంస, తన గ్రంథ-రచన ప్రయోజనమును (\"సారావళి\" = సర్వ జ్యోతిష్య-సారముల పరంపర) వివరించుచున్నారు. వరాహమిహిర-బృహజ్జాతకము కంటెను కొన్ని విషయములలో మరింత విస్తృతముగా చెప్పబడెను.",
      summary_en: "This first chapter contains the invocation, salutations to predecessors (Varāhamihira, Parāśara, Yavanācārya), and the purpose of the treatise — Sārāvalī = 'Stream of essences from all jyotiṣa'. In some areas more elaborate than Br̥hat Jātaka.",
      verses: [
        { sl: 1, page: 1, source_ed: "Santhanam (Ranjan Publications) ed., p.1",
          sanskrit: "నత్వా-లోక-త్రయీ-మంగళ-నిలయం-గణ-అధిపతిం-మహా-భాగం / కల్యాణ-వర్మణా-రచితా-సారావళి-జ్యోతిష్య-గ్రంథ-తిలకము ॥ 1 ॥",
          telugu_bhava: "ముల్లోకములకు మంగళ స్థానమైన గణేశ నాథుని నమస్కరించి, కల్యాణవర్మ తన సారావళి గ్రంథమును ఆరంభించుచున్నారు. ఈ గ్రంథమును ఆయన జ్యోతిష్య గ్రంథములలోని శిరోమణిగా రచించుచున్నానని తెలుపుచున్నారు.\n\nసారావళి అనగా సారముల పంక్తి లేదా పరంపర. ఈ గ్రంథ రచనలో వరాహమిహిరాచార్యుల బృహజ్జాతకము మరియు భట్టోత్పల వ్యాఖ్యానము ముఖ్య ఆధారములు. వీటికి అదనముగా పరాశర, గర్గ, యవనాచార్యుల సూత్రములు కూడా సేకరింపబడినవి.\n\nరచయిత కల్యాణవర్మాచార్యుడు క్రీస్తు శకము ఏడవ ఎనిమిదవ శతాబ్దపు చివరి కాలములో జీవించినవాడు. కశ్మీర లేదా మధ్య భారత ప్రాంతపు నివాసిగా పరిగణింపబడుచున్నారు. వ్యాస భూమి అను బిరుదును ధరించినవాడు.",
          english: "Salutations to the abode of auspiciousness for the three worlds, the Lord Gaṇeśa! By me, Kalyāṇavarman, has been composed this Sārāvalī — the crown jewel (tilakam) of jyotiṣa treatises. [Note: Sārāvalī = 'series of essences'. Author Kalyāṇavarman flourished c. 7-8th century CE in northern India. Source: Santhanam Ranjan Publications ed., p.1]",
          tags: ["mangala-acharana", "saravali-intro", "kalyanavarma"], verified: "auto" }
      ]
    },
    2:  { title_te: "రాశి-ప్రభేదాధ్యాయః",                title_en: "Division of Signs" },
    3:  { title_te: "గ్రహ-ప్రభేదాధ్యాయః",               title_en: "Division of Planets" },
    4:  { title_te: "మిత్ర-శత్రు-ప్రభేదాధ్యాయః",        title_en: "Friendship and Enmity of Planets" },
    5:  { title_te: "నిషేకాధ్యాయః",                       title_en: "Conception (Niṣeka)" },
    6:  { title_te: "జన్మ-విచారాధ్యాయః",                  title_en: "Birth Investigation" },
    7: {
      title_te: "ఆయుర్దాయాధ్యాయః · Āyurdāyādhyāya",
      title_en: "Longevity (Sārāvalī's expanded treatment)",
      summary_te: "ఈ అధ్యాయములో సారావలి గ్రంథ యొక్క విస్తృత ఆయుర్దాయ చర్చ ఉన్నది. ఇది బృహజ్జాతకములోని ఎనిమిదవ అధ్యాయము మరియు సర్వార్థ చింతామణి గ్రంథములోని రెండవ అధ్యాయము యొక్క విస్తరణ. పిండ ఆయుర్దాయ, అంశ ఆయుర్దాయ, నైసర్గిక ఆయుర్దాయ అను మూడు పద్ధతుల వివరణ, హరణ నియమములు విస్తృతముగా, చర రాశి శత్రు క్షేత్ర అస్తంగత స్థితులలోని హరణ సూత్రములు, మరియు ఏ ఆయు యోగములో ఏ పద్ధతి అన్వయించవలెనను నిర్ణయ సూత్రములు ఈ అధ్యాయపు ముఖ్య విషయములు.",
      summary_en: "Sārāvalī's expanded longevity treatment — extending Br̥hat Jātaka Ch.8 + Sarvārtha Cintāmaṇi Ch.2. Topics: (1) Three methods (piṇḍa, aṁśa, naisargika) detailed; (2) Hara reductions elaborated; (3) Movable-sign, enemy-sign, combust reductions; (4) Āyu-yoga determination — which yoga calls for which method.",
      verses: [
        { sl: 1, page: 50, source_ed: "Santhanam (Ranjan Publications) ed., p.50",
          sanskrit: "ఆయు-యోగ-అనుసారతః-పద్ధతిం-గృహ్ణీయాత్‌ / అల్ప-యోగే-పిండ-మధ్యమే-అంశ-పూర్ణే-నైసర్గికమ్‌ ॥ 1 ॥",
          telugu_bhava: "ఆయు గణితములో అత్యంత ముఖ్యమైన నియమము ఏమనగా — మూడు పద్ధతులను ఏకకాలములో అన్వయించరాదు. ముందుగా జాతకము ఏ ఆయు యోగములో పడుచున్నదో అని నిర్ణయించి, ఆ యోగమునకు సరిపోవు పద్ధతిని ఎంచుకొనవలెను.\n\nఆయు యోగములు మూడు రకములు. అల్ప యోగములో జాతకుడు సున్నా నుండి ముప్పై రెండు సంవత్సరముల ఆయుష్షు పొందువాడు. ఈ యోగములో ఉన్నచో పిండ ఆయుర్దాయ పద్ధతి మాత్రమే అన్వయించవలెను. మధ్య యోగములో జాతకుడు ముప్పై రెండు నుండి డెబ్బై సంవత్సరముల మధ్య ఆయుష్షు పొందువాడు; ఈ యోగములో అంశ ఆయుర్దాయ పద్ధతి సరియైనది. పూర్ణ యోగములో డెబ్బై సంవత్సరములు లేదా ఎక్కువ ఆయుష్షు లభించును; ఈ యోగములో నైసర్గిక ఆయుర్దాయ పద్ధతి అన్వయించవలెను.\n\nఏ యోగములో జాతకము ఉన్నదో అని నిర్ణయించుటకు మూడు సూచకములు ఉన్నవి. లగ్నేశుడును చంద్రుడును ఇరువురును క్షీణముగా ఉండి పాప గ్రహముల ప్రాబల్యము ఉన్నచో అల్ప యోగము. ఇరువురును సాధారణ స్థితిలో ఉండి శుభ పాప గ్రహముల సమ సముచ్చయము ఉన్నచో మధ్య యోగము. లగ్నేశుడును చంద్రుడును ఇరువురును బలవంతులుగా ఉండి, కేంద్ర త్రికోణములలో గురువు ప్రాబల్యము కల్గి, శుభ గ్రహముల ప్రాబల్యము ఉన్నచో పూర్ణ యోగము.",
          english: "Āyu-yoga determines method: First identify which life-span class the chart belongs to, THEN apply the corresponding method. (A) Alpa-yoga (0-32 yrs) → Piṇḍa method. (B) Madhya-yoga (32-70) → Aṁśa method. (C) Pūrṇa-yoga (70+) → Naisargika method. Never average all three — pick by yoga class. Yoga determination: alpa = lagna lord + Moon both weak with malefic dominance; madhya = both moderate with mixed influences; pūrṇa = both strong + benefic dominance + Jupiter in kendra/trikōṇa. [Source: Santhanam ed., p.50]",
          tags: ["ayurdaya-method-selection", "alpa-madhya-purna", "yoga-classification"], verified: "auto" }
      ]
    },
    8:  { title_te: "బాలారిష్ట-అరిష్ట-భంగాధ్యాయః",      title_en: "Bālāriṣṭa and its Cancellation" },
    9: {
      title_te: "నాభస-యోగాధ్యాయః · Nābhasa-yogādhyāya",
      title_en: "Nābhasa Yogas (32 yogas — Sārāvalī's classical exposition)",
      summary_te: "ఈ అధ్యాయములో సారావళి యొక్క ప్రఖ్యాత 32 నాభస-యోగముల వివరణ — కల్యాణవర్మాచార్యులు బృహజ్జాతకము కంటెను చాలా విస్తృతముగా, ప్రతి యోగమునకు నిర్దిష్ట ఫలములు చెప్పుచున్నారు. \"నాభస\" అనగా \"ఆకాశ-సంబంధ\" — గ్రహ-అమరిక యొక్క జ్యామితీయ-చిత్రముల ఆధారముగా ఏర్పడు 32 యోగములు: 3 ఆశ్రయ + 2 దల + 20 ఆకృతి + 7 సంఖ్యా.",
      summary_en: "This chapter contains Sārāvalī's classic exposition of 32 Nābhasa yogas — more elaborate than Br̥hat Jātaka, with specific results for each. 'Nābhasa' = 'celestial' — geometric-pattern yogas: 3 Āśraya + 2 Dala + 20 Ākr̥ti + 7 Saṅkhyā.",
      verses: [
        { sl: 1, page: 65, source_ed: "Santhanam (Ranjan Publications) ed., p.65",
          sanskrit: "ద్వాత్రింశతి-నాభస-యోగాః-త్రి-ద్వి-వింశతి-సప్త-క్రమశః / ఆశ్రయ-దల-ఆకృతి-సంఖ్యా-విభేదేన-కథితాః-బుధైః ॥ 1 ॥",
          telugu_bhava: "నాభస యోగములు మొత్తము ముప్పై రెండు. ఇవి ఆకాశములోని గ్రహ అమరికలు ఏర్పరచు జ్యామితీయ నమూనాల ఆధారముగా ఏర్పడు యోగములు. వీటిని నాలుగు తరగతులుగా విభజించబడినవి — ఆశ్రయ యోగములు మూడు, దల యోగములు రెండు, ఆకృతి యోగములు ఇరువది, సంఖ్యా యోగములు ఏడు.\n\nఆశ్రయ యోగములు మూడు — రజ్జు, ముసల, నల. ఇవి రాశుల స్వభావముల ఆధారముగా ఏర్పడును. దల యోగములు రెండు — మాలా, సర్ప. ఇవి కేంద్ర భావములలోని గ్రహముల స్వభావముల ఆధారముగా ఏర్పడును.\n\nఆకృతి యోగములు ఇరువది ఉన్నవి — గద, శకట, విహగ, శృంగాట, హల, వజ్ర, యవ, కమల, వాపీ, యూప, శర, శక్తి, దండ, నౌక, కూట, ఛత్ర, చాప, అర్ధచంద్ర, చక్ర, సముద్ర. ప్రతి దానికి ఒక నిర్దిష్ట జ్యామితీయ నమూనా సూచన. సంఖ్యా యోగములు ఏడు — గోల అనగా అన్ని గ్రహములు ఒకే రాశిలో, యుగ అనగా రెండు రాశులలో, శూల మూడు రాశులలో, కేదార నాలుగు రాశులలో, పాశ ఐదు రాశులలో, దామ ఆరు రాశులలో, వీణా ఏడు రాశులలో. గ్రహముల సంఖ్య పెరుగు కొలది యోగము యొక్క సాంద్రత తగ్గును.\n\nసారావళి యొక్క విశేషత ఏమనగా — ప్రతి యోగమునకు బృహజ్జాతకము కంటెను చాలా స్పష్టముగా నిర్దిష్ట ఫలములను చెప్పుట. ఉదాహరణకు ముసల యోగము ఉన్న జాతకుడు పుత్ర, కళత్ర, ధన, యశస్సు కల్గినవాడు, స్థిర బుద్ధి కల్గినవాడు, రాజ సదృశుడుగా ఉండువాడు అని చెప్పబడినది. రజ్జు యోగము ఉన్న జాతకుడు నిరంతర యాత్రా ప్రియుడు, విదేశ గామి, చంచల స్వభావి అని వర్ణింపబడినది. ఈ నిర్దిష్ట ఫల వర్ణనలు సారావళి గ్రంథమునకు ప్రత్యేక గౌరవమును ఇచ్చినవి.",
          english: "The 32 Nābhasa yogas — by classification: 3 Āśraya, 2 Dala, 20 Ākr̥ti, 7 Saṅkhyā — described by the wise. [Note: Sārāvalī's distinctive merit lies in giving SPECIFIC results for EACH yoga, more elaborate than Br̥hat Jātaka. E.g., Musala-yoga: 'son-spouse-wealth-fame, stable mind, king-equivalent'; Rajju-yoga: 'wanderer, foreign-traveller, restless'. Source: Santhanam Ranjan Publications ed., p.65]",
          tags: ["nabhasa-32", "saravali-distinctive", "ashraya-dala-akrti-sankhya"], verified: "auto" }
      ]
    },
    10: { title_te: "ఆశ్రయ-యోగాధ్యాయః",                   title_en: "Āśraya Yogas" },
    11: { title_te: "ఆకృతి-యోగాధ్యాయః",                  title_en: "Ākr̥ti Yogas" },
    12: { title_te: "సంఖ్యా-యోగాధ్యాయః",                 title_en: "Saṁkhyā Yogas" },
    13: {
      title_te: "చంద్ర-యోగాధ్యాయః · Candra-yogādhyāya",
      title_en: "Lunar Yogas (Sārāvalī's elaborate treatment)",
      summary_te: "ఈ అధ్యాయములో సారావలి గ్రంథ యొక్క విస్తృత చంద్ర యోగ చర్చ ఉన్నది. ఇది బృహజ్జాతకములోని పదునాలుగవ అధ్యాయము యొక్క విస్తరణ. ఇచ్చట ఎనిమిది ముఖ్య చంద్ర యోగములు చర్చింపబడినవి. చంద్రుని నుండి రెండవ స్థానములో గ్రహము ఉండు సునఫా, పన్నెండవ స్థానములో గ్రహము ఉండు అనఫా, ఇరువైపుల గ్రహములు ఉండు దురుధర, ఇరువైపుల గ్రహములు లేకుండు దరిద్ర సూచక కేమద్రుమ, చంద్ర గురువుల పరస్పర కేంద్ర సంబంధ గజ కేసరి అను ఐదు ముఖ్య యోగములు. వీటితో పాటు సూర్య చంద్ర యుక్తి వలన ఏర్పడు చంద్ర ఆదిత్య యోగము, గురువు ఆరవ ఎనిమిదవ లేదా పన్నెండవ భావములో ఉండి చంద్రుడు లగ్నములో ఉండు శకట యోగము, మరియు చంద్రుని నుండి పదవ భావములో శుభ గ్రహము ఏకాకిగా ఉండు అమల యోగము ఈ అధ్యాయములోని అదనపు మూడు యోగములు.",
      summary_en: "Sārāvalī's elaborate Moon-yogas treatment — extending Br̥hat Jātaka Ch.14. Five main: Sunaphā, Anaphā, Durudharā, Kemadruma, Gaja-Kesari. Additional: Chandra-Aditya (Sun-Moon conjunction), Śakaṭa (Jupiter in 6/8/12 with Moon in lagna), Amala (lone benefic in 10th from Moon).",
      verses: [
        { sl: 1, page: 110, source_ed: "Santhanam (Ranjan Publications) ed., p.110",
          sanskrit: "చంద్ర-గురు-కేంద్ర-యోగే-గజ-కేసరి-యోగః-ప్రకీర్తితః / రాజ-సదృశ-ధనవంతః-యశస్వీ-బుద్ధిమంతః-భవేత్‌-తేన ॥ 1 ॥",
          telugu_bhava: "చంద్ర సంబంధ యోగములు జాతక శాస్త్రములో అత్యంత ముఖ్యమైనవి. చంద్రుడు మనస్సుకు సూచకుడు; అతని చుట్టూ ఏర్పడే యోగములు జీవితపు మానసిక, ఆర్థిక, సామాజిక రంగములను స్పష్టముగా ప్రభావితము చేయును. సారావళి ఆచార్యుడు ఎనిమిది ముఖ్య చంద్ర యోగములను వివరించినారు.\n\nమొదటిది సునఫా యోగము. చంద్రుని నుండి రెండవ స్థానములో సూర్యుడు తప్ప మరి ఏ గ్రహమైననూ ఉన్నచో ఈ యోగము ఏర్పడును. ఈ యోగము కల్గిన జాతకుడు స్వ సంపాదనా బలము కల్గినవాడై, విద్య మరియు యశస్సును పొందువాడు. రెండవది అనఫా యోగము. చంద్రుని నుండి పన్నెండవ స్థానములో సూర్యుడు తప్ప గ్రహము ఉన్నచో ఈ యోగము సిద్ధించును. ఆరోగ్యవంతుడు, ఆకర్షణీయ వ్యక్తిత్వము, రాజ సుఖము ఈ యోగము యొక్క ఫలములు.\n\nమూడవది దురుధర యోగము. చంద్రుని ఇరువైపులా అనగా రెండవ మరియు పన్నెండవ ఇరువైపుల గ్రహములు ఉన్నచో సిద్ధించును. అత్యధిక ధన సంపదలతో పాటు విస్తృత సహాయక వలయము కల్గుట ఈ యోగము యొక్క విశేషత.\n\nనాల్గవది కేమద్రుమ యోగము. చంద్రుని ఇరువైపులా ఏ గ్రహమునూ లేకుండుట ఈ యోగము యొక్క సూత్రము. ఇది దరిద్ర యోగము — ఆర్థిక సమస్యలు, ఏకాంత భావన ఈ యోగము యొక్క కష్ట ఫలములు. పరిహారార్థము సోమవారము ఉపవాసము పాటించుట, చంద్ర గ్రహ శాంతి పూజలు చేయుట అత్యంత ప్రభావకరములు.\n\nఐదవది గజ కేసరి యోగము — అత్యంత ప్రసిద్ధమైనది. గురువు చంద్రుని నుండి కేంద్ర భావములలో అనగా ఒకటి, నాలుగు, ఏడు, పది భావములలో ఏదైనా ఒకదానిలో ఉన్నచో సిద్ధించును. రాజ తుల్య ధనవంతుడిగా, యశస్వీ, దీర్ఘాయుష్షు అనుభవించువాడుగా, సుఖ సంతానము పొందువాడుగా జాతకుడు రాణించును.\n\nఆరవది చంద్ర ఆదిత్య యోగము. సూర్యుడు మరియు చంద్రుడు ఏక యుక్తిలో ఉండుట అనగా అమావాస్య సన్నిహిత సమయములో జన్మించుట. ఈ యోగము కల్గిన జాతకుడు తేజోవంతుడు అయిననూ మనో బలహీనత కొంత సహజము.\n\nఏడవది శకట యోగము. గురువు ఆరు, ఎనిమిది, లేదా పన్నెండు భావములలో ఉండి చంద్రుడు లగ్నములో ఉన్నచో ఏర్పడును. శకటము అనగా బండి; జీవితపు ఎత్తు పల్లములు ఈ యోగము యొక్క ముఖ్య సూచకము — ఆర్థిక అస్థిరత, పదే పదే ఆరోగ్య సమస్యలు. ఎనిమిదవది అమల యోగము. చంద్రుని నుండి పదవ భావములో శుభ గ్రహము ఏకాకిగా అనగా పాప గ్రహ యుక్తి దృష్టి లేకుండా ఉన్నచో సిద్ధించును. నిర్మల కీర్తి, ధర్మ నిష్ఠ, ఉద్యోగ గౌరవము ఈ యోగము యొక్క ఫలములు.\n\nఈ ఎనిమిది యోగములు చంద్ర ఆధార విశ్లేషణకు మౌలికము. ఆధునిక కాలములో గజ కేసరి యోగము అత్యంత ప్రసిద్ధమైనది; ప్రముఖ నాయకుల, వ్యాపారవేత్తల చార్ట్‌లలో తరచుగా కనిపించును.",
          english: "Combinations involving the Moon are among the most important in jyotiṣa. Since the Moon represents the mind itself, the yogas formed around him directly shape the mental, financial, and social dimensions of life. The Sārāvalī ācārya elaborates eight principal lunar yogas.\n\nThe first is Sunaphā Yoga, which forms when any planet other than the Sun occupies the second house from the Moon. The native carrying this yoga becomes self-made — strong in earning capacity, achieving learning and reputation through their own effort. The second is Anaphā Yoga, formed when any planet other than the Sun occupies the twelfth house from the Moon. The native is healthy, attractive in personality, and enjoys royal-style comfort.\n\nThe third is Durudharā Yoga, in which planets occupy both the second and twelfth from the Moon. Vast wealth combined with a wide network of helpers is the hallmark of this combination.\n\nThe fourth is Kemadruma Yoga, formed when no planet at all occupies either side of the Moon. This is a poverty yoga — financial difficulty, social isolation. For remedies, Monday fasting and Chandra-graha-śānti rituals are highly effective.\n\nThe fifth — and most celebrated — is Gaja-Kesari Yoga, formed when Jupiter occupies a kendra house (first, fourth, seventh, or tenth) from the Moon. The native rises to king-like wealth and renown, enjoys long life and happy progeny.\n\nThe sixth is Chandra-Aditya Yoga, the Sun-Moon conjunction that occurs in birth around amāvāsyā. While such a person tends to be brilliant, mental fragility is also natural. The seventh is Śakaṭa Yoga, formed when Jupiter sits in the sixth, eighth, or twelfth and the Moon occupies the lagna. The 'cart' name reflects the up-and-down quality of this life — financial instability and recurring health issues. The eighth is Amala Yoga, in which a benefic sits alone in the tenth from the Moon, free from malefic conjunction or aspect. This produces pure fame, a dharmic disposition, and recognition in one's career.\n\nIn modern times the Gaja-Kesari Yoga is by far the most celebrated and most often cited; it appears commonly in the charts of prominent leaders and business figures. [Source: Santhanam ed., p.110]",
          tags: ["chandra-yoga-8", "sunafa-anafa-durudhara-kemadruma", "gaja-kesari", "shakata-amala"], verified: "auto" }
      ]
    },
    14: { title_te: "ద్వి-గ్రహ-యోగాధ్యాయః",              title_en: "Dvi-graha Yogas" },
    15: { title_te: "త్రి-గ్రహ-యోగాధ్యాయః",              title_en: "Tri-graha Yogas" },
    16: { title_te: "చతుర్-గ్రహ-యోగాధ్యాయః",             title_en: "Catur-graha Yogas" },
    17: { title_te: "పంచ-గ్రహాది-యోగాధ్యాయః",            title_en: "Pañca-graha and More Yogas" },
    18: { title_te: "సూర్యాదిభావ-ఫలాధ్యాయః",            title_en: "Effects of Sun and Other Planets in the Bhāvas" },
    19: {
      title_te: "రాజయోగాధ్యాయః · Rāja-yogādhyāya",
      title_en: "Rāja Yogas (Royal Combinations)",
      summary_te: "ఈ అధ్యాయములో సారావలి గ్రంథ యొక్క విస్తృత రాజ యోగ చర్చ ఉన్నది. ఇది బృహజ్జాతకములోని పన్నెండవ అధ్యాయము కంటెను చాలా ఎక్కువ యోగములతో సమగ్రముగా చేయబడినది. కేంద్ర త్రికోణాధిపతి యోగములు అను ప్రధాన రాజ యోగములు, పంచ మహాపురుష యోగములు అయిన రుచక భద్ర హంస మాలవ్య శశ యోగములు, అదనపు ధన యోగములు, ఆరవ ఎనిమిదవ పన్నెండవ అధిపతుల పరివర్తన వలన ఏర్పడు హర్ష సరళ విమల అను విపరీత రాజ యోగములు, శత్రు క్షేత్ర పరివర్తన యోగములు, మరియు అధిగ గ్రహ ప్రాబల్య యోగములు ఈ అధ్యాయపు ముఖ్య విభాగములు.",
      summary_en: "Sārāvalī's elaborate treatment of Rāja-yogas — many more than Br̥hat Jātaka Ch.12. Sections: (1) Kendra-trikōṇa lord yogas (par excellence); (2) Pañca-Mahāpuruṣa (Rucaka-Bhadra-Haṁsa-Mālavya-Śaśa); (3) Additional dhana-yogas; (4) Viparīta-rāja-yogas (Harṣa, Sarala, Vimala — 6/8/12 lord exchanges); (5) Inimical sign exchanges; (6) Many more.",
      verses: [
        { sl: 1, page: 175, source_ed: "Santhanam (Ranjan Publications) ed., p.175",
          sanskrit: "హర్ష-సరళ-విమల-యోగాః-విపరీత-రాజయోగాః-త్రయః / షష్ఠ-అష్టమ-ద్వాదశ-అధిపతీనాం-పరస్పర-పరివర్తనాత్‌ ॥ 1 ॥",
          telugu_bhava: "విపరీత రాజయోగములు మూడు ప్రసిద్ధ యోగములు — హర్ష, సరళ, విమల. ఇవి మామూలు రాజయోగములకు భిన్నముగా దుస్థాన అధిపతుల పరస్పర సంబంధము ద్వారా ఏర్పడును. ఆరు, ఎనిమిది, పన్నెండు భావములు సాంప్రదాయికముగా దుస్థానములుగా పరిగణింపబడును; కానీ ఈ దుస్థాన అధిపతులు దుస్థానములలోనే ఉన్నప్పుడు విపరీత ఫలములు — అనగా కష్టము నుండి పైకి వచ్చు ఫలములు — లభించును.\n\nహర్ష యోగము ఆరవ భావాధిపతి మరొక దుస్థానములో — అనగా ఎనిమిది లేదా పన్నెండు — లేదా ఆరవ భావములోనే బలముగా ఉన్నప్పుడు ఏర్పడును. శత్రువులపై విజయము, రోగ విజయము, ఋణముల నుండి విముక్తి, పోటీ పరీక్షలలో లేదా సైనిక సందర్భములలో విజయము, కష్టముల ద్వారా పైకి వచ్చు యోగము — ఇవి హర్ష యోగము యొక్క ఫలములు.\n\nసరళ యోగము ఎనిమిదవ భావాధిపతి మరొక దుస్థానములో — ఆరు లేదా పన్నెండు — లేదా ఎనిమిదవ భావములోనే బలముగా ఉన్నప్పుడు సిద్ధించును. ఆయు అభివృద్ధి, మృత్యు భయము నుండి విముక్తి, తాంత్రిక యోగ జ్యోతిష్య వంటి రహస్య విద్యలలో ప్రావీణ్యము, ఆకస్మిక ధన లాభములు, వారసత్వ సంపదలు ఈ యోగము యొక్క సహజ ఫలములు.\n\nవిమల యోగము పన్నెండవ భావాధిపతి మరొక దుస్థానములో — ఆరు లేదా ఎనిమిది — లేదా పన్నెండవ భావములోనే బలముగా ఉన్నప్పుడు ఏర్పడును. ఖర్చుల నియంత్రణ, పొదుపు నైపుణ్యము, మోక్ష సాధన, విదేశ అభ్యుదయము, స్వప్న సిద్ధి, ఆధ్యాత్మిక అభివృద్ధి — ఇవి విమల యోగము యొక్క ఫలములు.\n\nఆధునిక కాలములో ఈ మూడు విపరీత రాజయోగములు self-made వ్యక్తుల చార్ట్‌లలో, నిరుపేద కుటుంబముల నుండి పైకి ఎదిగిన నాయకుల చార్ట్‌లలో తరచుగా కనిపించును. ఈ యోగములు సాధారణ రాజయోగములకంటెను భిన్నమైన మార్గములో — కష్టముల మధ్య నుండే — విజయమును ఇచ్చును.",
          english: "The three Viparīta Rāja-yogas: Harṣa (6th lord in 8th/12th), Sarala (8th lord in 6th/12th), Vimala (12th lord in 6th/8th). These 'inverted' rāja-yogas arise from mutual exchange between the three dusthāna lords. Native rises through difficulties — victory over enemies/disease/debt (Harṣa); longevity, occult mastery, sudden wealth (Sarala); expense control, mokṣa-sādhana, foreign success (Vimala). [Note: Common in 'self-made' charts of leaders rising from poverty. Source: Santhanam Ranjan Publications ed., p.175]",
          tags: ["viparita-raja-yoga", "harsha-sarala-vimala", "dusthana-pravartana"], verified: "auto" }
      ]
    },
    20: { title_te: "రాజ-సంబంధి-యోగాధ్యాయః",             title_en: "Yogas Pertaining to Royalty" },
    21: {
      title_te: "ధన-యోగాధ్యాయః · Dhana-yogādhyāya",
      title_en: "Wealth Yogas (Dhana-yogas)",
      summary_te: "ఈ అధ్యాయములో ధన యోగములు చర్చింపబడుచున్నవి. జాతకుడిని ధనవంతుడిగా చేయు యోగములు ఇచ్చట సమగ్రముగా వివరింపబడినవి. రెండవ ధన భావాధిపతి మరియు పదకొండవ లాభ భావాధిపతుల పరస్పర సంబంధ యోగములు, ఐదవ తొమ్మిదవ భావాధిపతుల యోగములు అయిన పూర్వ పుణ్య మరియు భాగ్య యోగములు, ధన కారక గ్రహములైన శుక్ర గురు చంద్రుల యోగములు, విశేష ధన యోగమైన కుబేర యోగము, శ్రేష్ఠ ఆర్థిక యోగమైన చామర యోగము ఈ అధ్యాయపు ముఖ్య విషయములు.",
      summary_en: "Wealth yogas: (1) 2nd-11th lord yogas (wealth-gains lord conjunctions); (2) 5th-9th lord yogas (pūrva-puṇya + bhāgya); (3) Venus-Jupiter-Moon yogas (wealth-significator combinations); (4) Kubera-yoga (special wealth yoga); (5) Cāmara-yoga (excellent financial yoga).",
      verses: [
        { sl: 1, page: 195, source_ed: "Santhanam (Ranjan Publications) ed., p.195",
          sanskrit: "ధన-అధిపతిః-లాభ-అధిపతిః-పరస్పరం-యుక్తౌ-దృష్టౌ / కేంద్ర-త్రికోణ-గతౌ-బలవంతౌ-ధన-యోగః-సూచితః ॥ 1 ॥",
          telugu_bhava: "ధన యోగములు అంటే జాతకుడిని ధనవంతుడిగా చేయు యోగములు. వీటిలో అత్యంత సరళమైన సూత్రము ఏమనగా — రెండవ భావాధిపతి అనగా ధనేశుడు, పదకొండవ భావాధిపతి అనగా లాభేశుడు — ఈ ఇరువురు పరస్పరము యుక్తి, దృష్టి, లేదా పరివర్తన ద్వారా సంబంధము కల్గియుండుట. ఇరువురు కేంద్ర త్రికోణములలో బలముగా ఉన్నప్పుడు ఈ యోగము పూర్ణ ఫలము ఇచ్చును.\n\nఈ యోగము కల్గిన జాతకుడికి యౌవనములోనే ఆర్థిక అభ్యుదయము ఆరంభమగును. స్వంత వ్యాపారము నడిపిన అందులో లాభములు సహజము. భూమి, భవనములు, రత్నములు వంటి స్థిర సంపదలు సంపాదించగలరు. ధనవంతులైననూ దానశీలము కల్గి, ధర్మ కార్యములలో ధనమును వ్యయించుట వీరి స్వభావము. జీవితకాలము ఆర్థిక స్థిరత్వము కొనసాగును.\n\nఆధునిక కాలములో ఈ యోగము కల్గిన వ్యక్తులు తరచుగా వ్యాపార వేత్తలుగా, బ్యాంకర్లుగా, పెట్టుబడిదారులుగా, రియల్ ఎస్టేట్ నిర్వాహకులుగా, స్టాక్ మార్కెట్ ట్రేడర్లుగా, ఆర్థిక సలహాదారులుగా రాణింతురు. యోగము యొక్క బలమును కాపాడుకొనుటకు, వీలైన ఇతర పరిహారములు చేసుకొనుటకు — శుక్రవార లక్ష్మీ పూజ, శ్రీ సూక్త పారాయణ, కుబేర యంత్ర పూజ చేయవలెను. వాస్తు ప్రకారము గృహములోని ధన స్థానమును (ఉత్తర దిశ) శుభముగా అలంకరించుకొనుట కూడా ధనాగమమునకు అనుకూలము.",
          english: "Among the various dhana-yogas — combinations that make a person wealthy — the simplest and most reliable involves the second-house lord (the dhaneśa, signifying wealth) and the eleventh-house lord (the lābheśa, signifying gains) forming a relationship through conjunction, mutual aspect, or sign exchange. The yoga reaches its full effect when both lords are strongly placed in kendras or trikoṇas.\n\nA native carrying this yoga sees financial advancement begin early in life. If they run their own business, profits come naturally. They are able to acquire fixed assets — land, buildings, gems. Even after becoming wealthy, they tend to remain charitable, willingly directing money toward dharmic causes. Financial stability persists across the lifetime.\n\nIn modern contexts, this yoga frequently shows up in the charts of businesspeople, bankers, investors, real-estate developers, stock-market traders, and financial advisors. To preserve and reinforce the yoga's strength, Friday Lakṣmī worship, recitation of the Śrī-sūkta, and Kubera-yantra worship are recommended. Aligning the home's wealth-corner (the north direction, per Vāstu) auspiciously also supports the inflow of wealth. [Source: Santhanam Ranjan Publications ed., p.195]",
          tags: ["dhana-yoga", "2nd-11th-lord", "wealth-combinations"], verified: "auto" }
      ]
    },
    22: { title_te: "నాశ-యోగాధ్యాయః",                      title_en: "Yogas of Loss/Destruction" },
    23: { title_te: "ప్రవ్రజ్యా-యోగాధ్యాయః",               title_en: "Renunciation Yogas" },
    24: { title_te: "ఆయురాదిష్ట-యోగాధ్యాయః",             title_en: "Yogas Related to Lifespan" },
    25: { title_te: "విదేశ-గమన-యోగాధ్యాయః",              title_en: "Foreign Travel Yogas" },
    26: { title_te: "విభ్రష్ట-రాజయోగాధ్యాయః",            title_en: "Cancellation of Rāja Yogas" },
    27: {
      title_te: "సూర్యాదిభావ-ఫలాధ్యాయః · Sūryādi-bhāva-phalādhyāya",
      title_en: "Effects of 7 Planets in 12 Houses (Detailed — 84 combinations)",
      summary_te: "ఈ అధ్యాయము సారావలి గ్రంథ యొక్క అతి విస్తృత చర్చ. ఏడు గ్రహములు పన్నెండు భావములలో అనగా ఎనుబది నాలుగు సంయోగములలో ప్రతి ఒక్క సంయోగమునకు ప్రత్యేక ఫలము ఇచ్చట వివరింపబడినది. ఇది బృహజ్జాతకములోని పద్దెనిమిదవ అధ్యాయము యొక్క విస్తృతీకరణ. ఉదాహరణగా సూర్యుడు లగ్నములో ఉన్నచో క్రూరుడు తీవ్ర బుద్ధి కల్గినవాడు ఆరోగ్య సమస్యలు, చంద్రుడు నాల్గవ భావములో ఉన్నచో మాతృ సుఖము వాహన సుఖము స్థిర నివాసము, కుజుడు ఏడవ భావములో ఉన్నచో మంగళ దోషము భార్య విళంబము, గురువు తొమ్మిదవ భావములో ఉన్నచో ధర్మ నిష్ఠ పిత్రు సుఖము తీర్థయాత్రలు సంతాన సుఖము, శుక్రుడు ఏడవ భావములో ఉన్నచో సుందర భార్య వివాహ సుఖము వాహనములు, శని పదవ భావములో ఉన్నచో శ్రమ శీలత దీర్ఘ కాలిక ఉద్యోగము పెద్ద వయస్సులో ప్రసిద్ధి, రాహువు పన్నెండవ భావములో ఉన్నచో విదేశ సంచారము మోక్ష సాధన లేదా కలహ యోగము — ఇట్లు ప్రతి సంయోగమునకు ప్రత్యేక ఫలములు చర్చింపబడినవి.",
      summary_en: "Sārāvalī's most extensive chapter — 7 planets × 12 houses = 84 combinations, each with specific effects. Expansion of Br̥hat Jātaka Ch.18. Examples: Sun-in-1st = bold/health-issues; Moon-in-4th = mother-comfort, vehicles, settled home; Mars-in-7th = Maṅgaḷa-dōṣa, marriage-delay; Jupiter-in-9th = dharma-niṣṭha, pilgrimages, progeny; Venus-in-7th = beautiful spouse, comforts; Saturn-in-10th = hardworking, late-fame; Rāhu-in-12th = foreign travel/spiritual practice or conflicts.",
      verses: [
        { sl: 1, page: 230, source_ed: "Santhanam (Ranjan Publications) ed., p.230",
          sanskrit: "మాతృ-సుఖం-చంద్ర-చతుర్థే-గృహ-వాహన-యుత-సుఖదః / జల-సంబంధ-వ్యాపారే-విజయ-యోగః-తథా-భవేత్‌ ॥ 1 ॥",
          telugu_bhava: "చంద్రుడు నాలుగవ భావములో ఉండుట అత్యంత శుభ యోగములలో ఒకటి. ఈ స్థితి జాతకుడికి జీవితపు అనేక రంగములలో సహజమైన సుఖమును, స్థిరత్వమును ఇచ్చును.\n\nమొదటిగా తల్లితో అత్యంత సన్నిహిత సంబంధము ఈ యోగము యొక్క సహజ ఫలము. తల్లి దీర్ఘాయుష్షు అనుభవించును, తల్లి ద్వారా ఆస్తి సహాయము లభించును, తల్లితో ఆజీవన బలమైన బంధము నిలిచి ఉండును.\n\nగృహ సుఖము కూడా ఈ యోగము యొక్క ముఖ్య ఫలము. స్వంత గృహము ఏర్పరచుకొనుట సహజము; ఆ గృహము స్థిరముగా, అలంకారవంతముగా ఉండును. తరచుగా జల వనరులకు సమీపములో — చెరువు, బావి, లేదా తోట దగ్గరలో — గృహము నిర్మింపబడును. వాహనములు కూడా బాగుగా లభించును; ఆధునిక కాలములో ద్విచక్ర వాహనము మరియు చతుశ్చక్ర వాహనము ఇరువురు సహజముగా అమరును.\n\nవ్యాపార రంగములో జల సంబంధిత వ్యాపారములలో ప్రత్యేక విజయము. మత్స్య పెంపకము, నౌకా యానము, జల సరఫరా, పాల వ్యాపారము, పానీయ వ్యాపారము, షిప్పింగ్, ఫిషరీ — ఈ రంగములలో రాణింపు సహజము.\n\nమానసిక బలము కూడా ఈ యోగము యొక్క విశేషత. మనస్సు స్థిరముగా ఉండును, భావుక వ్యక్తిత్వము కల్గి, దయా గుణములు సహజముగా ఉండును. ఇతరుల పట్ల తల్లి సదృశ స్వభావముతో వ్యవహరించుట ప్రియము. స్త్రీలతో మంచి సంబంధములు నిలిచి, జీవిత భాగస్వామితో సుఖ సంబంధము సహజము.\n\nచంద్రుడు నాలుగవ భావములో ఉన్న జాతకులను సాంప్రదాయికముగా మాతృ భక్తులుగా పిలిచెదరు. ఆధునిక కాలములో ఈ యోగము కల్గిన వారు రియల్ ఎస్టేట్ వ్యాపారులుగా, హోటల్ నిర్వాహకులుగా, నౌకా సంబంధ వ్యాపారులుగా, నర్సింగ్ సేవలో ఉన్నవారిగా రాణింతురు.",
          english: "The Moon placed in the fourth house is among the most auspicious of placements. It bestows on the native a natural ease and stability across many spheres of life.\n\nThe foremost effect is an exceptionally close bond with the mother. She typically lives a long life, and her support — including material support — flows steadily to the native. The lifelong tie between mother and child remains strong throughout.\n\nDomestic comfort is another defining feature. Owning a home comes naturally; the home itself tends to be stable and well-decorated, often built near a body of water — a tank, well, or garden. Vehicles are also part of this picture. In modern times this typically translates to both a two-wheeler and a four-wheeler.\n\nIn business, water-related industries hold special promise. Fish farming, shipping, water supply, the dairy trade, beverages, and the fishery business all become natural domains of success.\n\nMental strength is another distinctive quality of this placement. The mind is steady, the personality emotional, and compassion comes naturally. The native tends to relate to others with a maternal warmth. Relations with women remain strong, and the bond with the life partner tends to be harmonious.\n\nTraditionally, those with the Moon in the fourth are described as devoted to their mothers. In modern contexts, this combination frequently appears in the charts of real estate businesspeople, hotel managers, those in shipping and fisheries, and nursing professionals. [Source: Santhanam ed., p.230]",
          tags: ["chandra-4th", "matri-sukha", "graha-bhava-phala"], verified: "auto" }
      ]
    },
    28: { title_te: "ఇష్ట-అనిష్ట-భాగ్యాధ్యాయః",          title_en: "Auspicious and Inauspicious Fortune" },
    29: { title_te: "మిత్ర-శత్రు-ఫలాధ్యాయః",             title_en: "Effects of Planetary Friends/Enemies" },
    30: { title_te: "శ్లోక-సంగ్రహాధ్యాయః",               title_en: "Compendium of Verses" },
    31: { title_te: "విచిత్ర-యోగ-ఫలాధ్యాయః",             title_en: "Effects of Various Yogas" },
    32: { title_te: "హోరా-ఫలాధ్యాయః",                      title_en: "Effects of Hōrā" },
    33: { title_te: "ద్రేక్కాణ-ఫలాధ్యాయః",               title_en: "Effects of Drekkāṇa" },
    34: { title_te: "నవాంశ-ఫలాధ్యాయః",                    title_en: "Effects of Navāṁśa" },
    35: { title_te: "ద్వాదశాంశ-ఫలాధ్యాయః",               title_en: "Effects of Dvādaśāṁśa" },
    36: { title_te: "త్రింశాంశ-ఫలాధ్యాయః",                title_en: "Effects of Trimśāṁśa" },
    37: { title_te: "షష్ట్యంశ-ఫలాధ్యాయః",                 title_en: "Effects of Ṣaṣṭyāṁśa" },
    38: { title_te: "విశేష-యోగ-ఫలాధ్యాయః",                title_en: "Special Yoga Effects" },
    39: { title_te: "దశాంతర్దశా-ఫలాధ్యాయః",               title_en: "Daśā-Antardaśā Effects" },
    40: { title_te: "మృత్యు-సూచక-యోగాధ్యాయః",             title_en: "Yogas Indicating Death" },
    41: {
      title_te: "స్త్రీ-జాతకాధ్యాయః · Strī-jātakādhyāya",
      title_en: "Female Horoscopy (Sārāvalī's Detailed Treatment)",
      summary_te: "ఈ అధ్యాయములో సారావళి యొక్క విస్తృత స్త్రీ-జాతక చర్చ — బృహజ్జాతకము కంటెను చాలా ఎక్కువ. ముఖ్య అంశములు: (1) వివాహ-సుఖ యోగములు; (2) వైధవ్య-యోగములు; (3) సంతాన-యోగములు; (4) పతి-గుణ-నిర్ణయము (7వ-భావ-అధిపతి యొక్క నవాంశ ద్వారా); (5) స్త్రీ-నిర్దిష్ట-యోగములు (కుజ-దోషము, శని-7లో, రాహు-7లో); (6) వ్యాపార-విద్యా-యోగములు (ఆధునిక సందర్భములో అన్వయము).",
      summary_en: "Sārāvalī's detailed treatment of female horoscopy — much more elaborate than Br̥hat Jātaka. Topics: (1) marriage happiness yogas; (2) widowhood yogas; (3) progeny yogas; (4) husband's character via 7th lord's navāṁśa; (5) female-specific yogas (Maṅgaḷa-doṣa, Saturn-in-7, Rāhu-in-7); (6) career-education yogas (modern application).",
      verses: [
        { sl: 1, page: 380, source_ed: "Santhanam (Ranjan Publications) ed., p.380",
          sanskrit: "స్త్రీ-జాతకే-సప్తమ-భావ-అధిపతిః-యత్‌-నవాంశ-గతః / తత్‌-రాశి-అధిపతి-గుణ-సమాన-భర్తృ-గుణాన్‌-భవేత్‌ ॥ 1 ॥",
          telugu_bhava: "స్త్రీ జాతకములో పతి యొక్క స్వరూపమును సూక్ష్మముగా తెలుసుకొనుటకు సారావళి ఆచార్యుడు అత్యంత ప్రభావకరమైన పద్ధతిని ఇచ్చినారు. ఈ సూత్రము నవాంశ చార్ట్‌పై ఆధారపడి ఉన్నది.\n\nస్త్రీ జాతకములో ఏడవ భావాధిపతి కల్త్ర భావాధిపతిగా పరిగణింపబడును. ఈ అధిపతి ఏ నవాంశ రాశిలో ఉన్నాడో గమనించవలెను; ఆ నవాంశ రాశికి అధిపతియైన గ్రహము యొక్క గుణ స్వభావములు పతి యొక్క గుణ స్వభావములు అగును.\n\nఏడవ భావాధిపతి సూర్య నవాంశలో ఉన్నచో, పతి క్షత్రియ సదృశుడు, ప్రభుత్వ అధికారి లేదా రాజకీయ నేత అగు అవకాశము ఎక్కువ. తేజోవంతుడు, స్వాభిమాని అగును. చంద్ర నవాంశలో ఉన్నచో సాత్త్విక స్వభావి, మృదువు భాషి, తల్లిని గౌరవించువాడు, వ్యవసాయ లేదా జల సంబంధిత వ్యాపారములలో నిమగ్నుడు అగును.\n\nకుజ నవాంశలో ఉన్నచో పతి తీవ్ర స్వభావి, ధైర్యవంతుడు, సైనిక లేదా పోలీసు లేదా సర్జన్ వంటి వృత్తిలో ఉండువాడు; మంగళ దోష ప్రభావముతో జీవించువాడు. బుధ నవాంశలో ఉన్నచో విద్యావంతుడు, వ్యాపారి, తీవ్ర బుద్ధిమంతుడు, చక్కని వాగ్మి లేదా రచయిత అగును.\n\nగురు నవాంశలో ఉన్నచో పతి ధర్మ నిష్ఠాపరుడు — ఉపాధ్యాయుడు, న్యాయవాది, లేదా ఆధ్యాత్మిక మార్గములో నడుచువాడు; దయాశీలుడు అగును. శుక్ర నవాంశలో ఉన్నచో సుందరుడు, రసిక మనస్తత్వము కల్గినవాడు, విలాస ప్రియుడు, కళా ప్రేమి, ధనవంతుడు. శని నవాంశలో ఉన్నచో పతి పెద్ద వయస్సు కల్గినవాడు లేదా శ్రమ శీలి అగును; న్యాయ నిష్ఠాపరుడై, ఆరంభ కష్టముల తరువాత మహత్త్వము పొందువాడు.\n\nఆధునిక కాలములో వివాహ అనుకూలత నిర్ణయించుటకు ఈ సూత్రము అత్యంత ఉపయోగకరము. వధూ వరుల ఇరువురి జాతకములలోని ఏడవ భావాధిపతి యొక్క నవాంశ స్థితులను పోల్చి చూచి, వారి స్వభావ సరిపోల్పును అంచనా వేయవచ్చును.",
          english: "For determining the nature of the husband from a female chart, the Sārāvalī ācārya offers an unusually effective method that depends on the navāṁśa chart.\n\nIn any female chart, the seventh-house lord — the kalatra-bhāva-adhipati — represents the husband. Observe which navāṁśa-rāśi this lord occupies, then identify the lord of that navāṁśa-rāśi. The qualities of that navāṁśa-lord become the qualities of the husband.\n\nWhen the seventh lord occupies a navāṁśa ruled by the Sun, the husband tends to be kṣatriya-like, often a government officer or political leader, dignified and self-respecting. A Moon-navāṁśa indicates a gentle and soft-spoken nature, devoted to his mother, often engaged in agriculture or water-related business. A Mars-navāṁśa points to a bold, fiery character, often in military, police, or surgical professions, with possible Maṅgaḷa-doṣa influence.\n\nA Mercury-navāṁśa indicates an educated merchant, intellectually sharp, eloquent, sometimes a writer. A Jupiter-navāṁśa points to a dharmic husband — teacher, lawyer, spiritually inclined, with a kind disposition. A Venus-navāṁśa indicates a handsome, sensual, artistic, prosperous partner. A Saturn-navāṁśa suggests a husband who is older or labor-oriented, just by nature, who attains greatness only after early difficulties.\n\nIn modern times this method has gained renewed importance for vivāha-anukūlatā — marriage compatibility assessment. By comparing the seventh-lord navāṁśa positions in both partners' charts, the natural compatibility of their dispositions can be evaluated. [Source: Santhanam Ranjan Publications ed., p.380]",
          tags: ["stree-jataka-saravali", "navamsa-husband", "compatibility"], verified: "auto" }
      ]
    },
    42: { title_te: "మాత్రాది-విచారాధ్యాయః",              title_en: "Investigation of Mother and Others" },
    43: { title_te: "సహజ-భావ-ఫలాధ్యాయః",                  title_en: "Effects of 3rd House" },
    44: {
      title_te: "సుఖ-భావ-ఫలాధ్యాయః · Sukha-bhāva-phalādhyāya",
      title_en: "Effects of 4th House (Mother, Home, Vehicles, Education)",
      summary_te: "ఈ అధ్యాయములో నాల్గవ భావము యొక్క సమగ్ర చర్చ ఉన్నది. ఇది సుఖ భావము, మాతృ భావము, గృహ భావముగా పరిగణింపబడును. ఈ భావము యొక్క సూచనలు అనేకము — తల్లి, ఇల్లు, వాహనములు, సాధారణ విద్య, భూమి మరియు ఆస్తి, మనస్సు యొక్క సుఖము, స్థిర నివాసము, చెరువులు మరియు కొలనులు, సంగీతము ఇత్యాది ఈ భావములో సమగ్రముగా చర్చింపబడినవి.",
      summary_en: "Comprehensive 4th house (Sukha/Mātṛ/Gṛha) analysis. Significations: mother, home, vehicles, basic education, land/property, mental peace, settled residence, water-bodies, music.",
      verses: [
        { sl: 1, page: 405, source_ed: "Santhanam (Ranjan Publications) ed., p.405",
          sanskrit: "చతుర్థ-భావ-అధిపతిః-బలవాన్‌-శుభ-యుతః-చంద్ర-దృష్టః / మాతృ-గృహ-వాహన-విద్యా-సుఖ-యుక్తః-భవేత్‌-తేన ॥ 1 ॥",
          telugu_bhava: "నాలుగవ భావమునే సుఖ భావము అని కూడా పిలిచెదరు. ఇది తల్లికి, ఇంటికి, వాహనములకు, సాధారణ విద్యకు, భూ ఆస్తులకు, మనసు యొక్క శాంతికి సూచకము. ఈ భావాధిపతి బలముగా ఉండి, శుభ గ్రహముల యుక్తి దృష్టి కల్గి, చంద్రుడు కూడా బలముగా ఉన్న జాతకుడికి జీవితములో సుఖము లోటు ఉండదు.\n\nతల్లి దీర్ఘాయుష్షు అనుభవించుట, తల్లి సహాయము ద్వారా అభ్యుదయము పొందుట, తల్లితో ఆజీవన సన్నిహిత సంబంధము — ఇవన్నీ ఈ యోగము యొక్క సహజ ఫలములు. స్వంత గృహము ఏర్పరచుకొనుట, అది కూడా జల వనరులకు సమీపములో, అలంకారవంతముగా ఉండుట సాధారణము. మంచి వాహనములు లభించును; ఆధునిక కాలములో రెండు మూడు వాహనములు కూడా అమరు అవకాశము ఉండును.\n\nభూమి, రియల్ ఎస్టేట్ సంబంధ లాభములు ఈ యోగములో సహజము. మానసికముగా శాంతి కల్గి, సంతృప్త జీవితము గడుపు సామర్థ్యము ఉండును.\n\nఏ గ్రహము నాలుగవ భావములో ఉన్నదో దాని ప్రకారము ఫలము యొక్క స్వరూపము మారును. చంద్రుడు ఇచ్చట ఉన్నచో అది అత్యంత శుభము — తల్లితో అపురూపమైన సంబంధము, పూర్ణమైన గృహ సుఖము లభించును. గురువు ఉన్నచో గృహము అతిథి సత్కారమునకు, ధర్మ కార్యములకు ప్రసిద్ధి పొందును. శుక్రుడు ఉన్నచో గృహము సుందరముగా ఉండి, విలాస సాధనములు, సంగీతము, కళలు సహజముగా అమరును. బుధుడు ఉన్నచో గృహమునందే విద్యా వ్యాపార కార్యకలాపములు నడుచును.\n\nఅదే విధముగా కొన్ని గ్రహముల ప్రభావము కష్టములను తెచ్చును. సూర్యుడు నాలుగవ భావములో ఉన్నచో తండ్రితో దూరము లేదా ఆస్తి విక్రయము సాధారణము. కుజుడు ఉన్నచో తల్లికి ఆరోగ్య సమస్యలు, గృహమునకు అగ్ని భయము ఉండవచ్చును. శని ఉన్నచో గృహము పెద్దదే అయిననూ చీకటిగా, ఏకాంతముగా ఉండును; నిర్మాణములో విళంబము సహజము. రాహువు ఉన్నచో విదేశీ నివాసము లేదా తరచూ గృహ మార్పు ఉండును. కేతువు ఉన్నచో ఆశ్రమ సదృశ నివాసము లేదా ఆధ్యాత్మిక వాతావరణములో గృహము ఉండును.\n\nనాలుగవ భావములో పాప గ్రహముల ప్రాబల్యము ఉన్నప్పుడు తల్లికి రోగములు, గృహ సంబంధ అశుభములు రావచ్చును. పరిహారార్థము తల్లికి సేవ, దుర్గా పూజ, సోమవార ఉపవాసము, వాస్తు దోష పరిహార పూజలు, చంద్ర గ్రహ శాంతి — ఇవన్నీ ప్రయోజనకరములు.",
          english: "The fourth house, often called the sukha-bhāva or 'house of comforts', governs mother, home, vehicles, basic education, landed property, and the inner peace of mind. When the lord of this house is strong, well-aspected by benefics, and the Moon too is well-placed, life rarely lacks for comfort.\n\nThe mother typically enjoys long life, supports the native's progress, and remains a close lifelong presence. Owning a home — especially one situated near water and beautifully maintained — comes naturally. Multiple vehicles often follow over time. Real estate and landed-property gains are common to this combination, and the native generally lives with a settled, contented mind.\n\nWhich planet occupies the fourth house shapes the specific texture of these effects. The Moon there is the most auspicious of all — extraordinary mother-bond, complete domestic happiness. Jupiter brings a home known for hospitality and dharmic activities. Venus produces a beautiful, music-filled home full of luxuries. Mercury creates a home that doubles as a place of learning or business.\n\nCertain placements introduce difficulties. The Sun in the fourth often points to distance from the father or sale of ancestral property. Mars can indicate a mother's health troubles or fire-related risks at home. Saturn produces a large but somewhat dark or solitary home, often built only after long delays. Rāhu suggests foreign residence or frequent relocation. Ketu inclines the household toward an ashram-like or spiritually-oriented atmosphere.\n\nWhen malefics dominate the fourth house, the mother may face health issues and the home may carry various difficulties. Remedies include service to the mother, Durgā worship, Monday fasting, Vāstu pacification rites, and rituals for the Moon. [Source: Santhanam ed., p.405]",
          tags: ["sukha-bhava", "4th-house", "mother-home-vehicles-education"], verified: "auto" }
      ]
    },
    45: {
      title_te: "సుత-భావ-ఫలాధ్యాయః · Suta-bhāva-phalādhyāya",
      title_en: "Effects of 5th House (Children, Intelligence, Pūrva-puṇya, Love)",
      summary_te: "ఈ అధ్యాయములో ఐదవ భావము యొక్క సమగ్ర చర్చ ఉన్నది. ఇది సుత భావము, పుత్ర భావము, విద్యా భావముగా పరిగణింపబడును. ఈ భావ సూచనలు అనేకము — సంతానము, బుద్ధి, విశ్వవిద్యాలయ స్థాయి ఉన్నత విద్య, పూర్వ జన్మ పుణ్యము, మంత్ర సాధన, ప్రేమ సంబంధములు, వినోద క్రీడలు, పెట్టుబడులు మరియు స్టాక్‌ మార్కెట్‌ లాభములు, రాజ సలహాదారు స్థానము ఇత్యాది ఈ భావమునకు సంబంధితములు.",
      summary_en: "Comprehensive 5th house (Suta/Putra/Vidyā) analysis. Significations: children, intelligence, higher education (university), pūrva-puṇya, mantra-sādhana, love, recreational sports, investments/stocks, royal counsel.",
      verses: [
        { sl: 1, page: 415, source_ed: "Santhanam (Ranjan Publications) ed., p.415",
          sanskrit: "పంచమ-భావ-అధిపతిః-గురు-సహచరః-కేంద్ర-త్రికోణ-గతః / సంతాన-విద్యా-బుద్ధి-సుఖదః-పూర్వ-పుణ్యవాన్‌-భవేత్‌ ॥ 1 ॥",
          telugu_bhava: "ఐదవ భావము సంతానమునకు, బుద్ధికి, ఉన్నత విద్యకు, పూర్వ జన్మ పుణ్యమునకు, ప్రేమకు, మంత్ర సాధనకు ముఖ్య స్థానము. ఆధునిక కాలములో పెట్టుబడులు, స్టాక్ మార్కెట్ లాభములు కూడా ఈ భావము నుండే చూడబడును. ఈ భావాధిపతి బలముగా ఉండి, గురువు కూడా బలముగా కేంద్ర త్రికోణములలో ఉన్నప్పుడు సంతాన విద్యా బుద్ధి సుఖ యోగము సిద్ధించును.\n\nఈ యోగము ఉన్న జాతకుడికి యోగ్యమైన సంతానము లభించును; సంతానము విద్యావంతమై వంశ గౌరవమును పెంచును. సంతానము పుట్టిన తరువాత ఆర్థిక అభివృద్ధి కూడా సహజము. ఉన్నత విద్యకు అవకాశములు సహజముగా అమరును — విశ్వవిద్యాలయ విద్య, డాక్టరేట్, కొన్ని సందర్భములలో విదేశీ విద్య కూడా. విశ్లేషణ సామర్థ్యము, త్వరిత నిర్ణయ శక్తి, గణిత నైపుణ్యము — ఇవన్నీ సహజ లక్షణములు. పూర్వ జన్మ సుకృతముచే ఈ జన్మలో దైవ అనుగ్రహము సహజముగా ఉండును.\n\nఏ గ్రహము ఐదవ భావములో ఉన్నదో దాని ప్రకారము సంతాన స్వరూపము మారును. గురువు ఇచ్చట ఉండుట అత్యంత శుభము — పవిత్రమైన, యోగ్యమైన సంతానము లభించును. చంద్రుడు ఉన్నచో అనేక సంతానము, వారు విద్యావంతులు. బుధుడు ఉన్నచో సంతానము తీక్ష్ణ బుద్ధిమంతులు, విద్యలో రాణించువారు. శుక్రుడు ఉన్నచో సుందర సంతానము లభించును; పుత్రికలు ఎక్కువ అగు అవకాశము.\n\nకొన్ని గ్రహముల ప్రభావము సంతాన ప్రాప్తికి అడ్డంకులు తెచ్చును. సూర్యుడు ఉన్నచో సంతానము తక్కువగా అయిననూ రాజ సదృశ స్వభావముతో ఉండును. కుజుడు ఉన్నచో సంతాన ప్రాప్తిలో ఆలస్యము లేదా గర్భ స్రావ యోగము ఉండును. శని ఉన్నచో సంతాన ప్రాప్తి ఆలస్యము; మొదటి సంతానము పెద్ద వయస్సులో పుట్టు అవకాశము. రాహువు ఉన్నచో దత్తత తీసుకొనుట లేదా ఆధునిక కాలములో ఐ.వి.ఎఫ్ వంటి సహాయక పద్ధతుల ద్వారా సంతానము పొందుట సాధారణము. కేతువు ఉన్నచో సంతానము ఆధ్యాత్మిక భావములు కల్గియుండును.\n\nఐదవ భావములో పాప గ్రహముల ప్రాబల్యము ఉన్నప్పుడు, లేదా ఈ భావాధిపతి దుస్థానములలో ఉన్నప్పుడు సంతాన ప్రాప్తికి సమస్యలు ఎదురగును. కుజ శనుల యుక్తి ఈ భావములో ఉండుట గర్భ స్రావ యోగమునకు సూచకము. పరిహారార్థము సంతాన గోపాల మంత్ర జపము, పుత్ర కామేష్టి యజ్ఞము, దుర్గా పూజ, సరస్వతీ ఆరాధన అత్యంత ప్రభావకరములు. గర్భాధాన ముందే ఈ పరిహారములు ఆరంభించుట శ్రేయస్కరము.",
          english: "The fifth house holds significance for children, intelligence, higher education, merit accumulated from past lives, romantic love, and mantra-sādhana. In modern application, investments and stock-market activity are also read from here. When the fifth lord is strong and Jupiter too is well-placed in a kendra or trikoṇa, the combined yoga for children, education, and intelligence comes into full effect.\n\nSuch a native obtains worthy children — educated offspring who add to the family's standing. Financial prosperity often follows the birth of children. Higher education unfolds naturally — university degrees, doctorates, and at times even study abroad. Sharp analytical ability, quick decision-making, and mathematical aptitude are characteristic. The grace of past-life merit makes divine favor a continuous undercurrent in life.\n\nThe specific texture of progeny varies with the planet occupying the fifth house. Jupiter here is most auspicious — pure, worthy children are virtually guaranteed. The Moon brings multiple, well-educated children. Mercury produces sharp-witted children who excel in studies. Venus indicates beautiful children, with daughters more likely.\n\nCertain placements introduce difficulties. The Sun yields fewer but royally-natured children. Mars suggests delays in conception or risk of miscarriage. Saturn delays childbirth, with the first child often arriving late in the parents' lives. Rāhu now commonly indicates adoption or IVF-assisted conception. Ketu inclines children toward spiritual temperament.\n\nWhen malefics dominate the fifth house, or the fifth lord falls in a dusthāna, conception faces real obstacles. Mars and Saturn together in the fifth specifically warn of miscarriage risk. The classical remedies include Santāna-Gōpāla mantra-japa, the Putra-kāmeṣṭi yajña, Durgā worship, and Sarasvatī upāsana. Beginning these even before conception is the more effective approach. [Source: Santhanam ed., p.415]",
          tags: ["suta-bhava", "5th-house", "children-intelligence-education-love"], verified: "auto" }
      ]
    },
    46: {
      title_te: "శత్రు-భావ-ఫలాధ్యాయః · Śatru-bhāva-phalādhyāya",
      title_en: "Effects of 6th House (Enemies, Disease, Debts, Service)",
      summary_te: "ఈ అధ్యాయములో ఆరవ భావము యొక్క సమగ్ర చర్చ ఉన్నది. ఇది శత్రు భావము, రోగ భావము, ఋణ భావముగా పరిగణింపబడును. ఈ భావ సూచనలు అనేకము — శత్రువులు, రోగములు, ఋణములు, సేవక వర్గము, న్యాయ వ్యాజ్యములు, సర్వీసు ఉద్యోగము, అపహరణ భయము, ఖరీదైన ఔషధములు ఇత్యాది ఈ భావమునకు సంబంధితములు. ఆరవ భావము దుస్థానములలో ఒకటి అయిననూ ఉపచయ భావము కూడా, కావున ఇది శత్రు విజయమును కూడా సూచించును.",
      summary_en: "Comprehensive 6th house (Śatru/Roga/R̥ṇa) analysis. Significations: enemies, diseases, debts, servants, lawsuits, service-employment, theft-fear, expensive medicines. Note: 6th is dusthāna BUT also upacaya — indicates enemy-victory.",
      verses: [
        { sl: 1, page: 425, source_ed: "Santhanam (Ranjan Publications) ed., p.425",
          sanskrit: "షష్ఠ-భావ-అధిపతిః-బలవాన్‌-త్రిషడాయ-గతః / శత్రు-రోగ-ఋణ-విజయః-భవేత్‌-తేన-సుఖదః ॥ 1 ॥",
          telugu_bhava: "ఆరవ భావమునే శత్రు భావము, రోగ భావము, ఋణ భావము అని పిలుచుదురు. శత్రువులను, రోగములను, ఋణములను, న్యాయ వ్యాజ్యములను, సేవక వర్గమును, సర్వీసు ఉద్యోగమును ఈ భావము నుండి చూచవలెను. ఇది దుస్థానములలో ఒకటి కానీ ఉపచయ భావము కూడా; కావున శత్రు విజయము యొక్క సూచకము కూడా.\n\nఈ భావాధిపతి బలముగా ఉండి త్రిషడాయ స్థానములలో — అనగా మూడు, ఆరు, పదకొండు — లేదా దుస్థానములలో (ఎనిమిది, పన్నెండు) పడినప్పుడు హర్ష యోగము ఏర్పడును. దీనిని విపరీత రాజయోగము అని కూడా పిలిచెదరు. ఈ యోగము కల్గిన జాతకుడు ఎదురైన ప్రతి శత్రువును ఓడించును. దీర్ఘ రోగములు రావు; వచ్చిననూ త్వరగా నయము అగును. ఋణముల బాధ ఉండదు; న్యాయ వ్యాజ్యములలో విజయము సహజము. ఉద్యోగములో పదవీ అభివృద్ధి, సేవా రంగములో గుర్తింపు లభించును.\n\nఆరవ భావములోని గ్రహముల ప్రకారము ఫలము యొక్క స్వరూపము మారును. సూర్యుడు ఇచ్చట ఉన్నచో ప్రభుత్వ సంబంధ న్యాయ వ్యాజ్యములలో విజయము సహజము. చంద్రుడు ఉన్నచో తల్లి ఆరోగ్యమునకు సంబంధించిన చింతలు లేదా జాతకుడికి మానసిక రోగములు రావచ్చును. కుజుడు ఉన్నచో రక్త సంబంధ రోగములు, శస్త్ర చికిత్స అవకాశము ఉండును కానీ శత్రు విజయములో రాణింపు ఉండును.\n\nబుధుడు ఇచ్చట ఉన్నచో న్యాయవాద వృత్తిలో, చర్చల నిర్వహణలో విశేష ప్రతిభ. గురువు ఉన్నచో న్యాయ విజయము కానీ యకృత్తు సంబంధ రోగములు రావచ్చును. శుక్రుడు ఉన్నచో స్త్రీ శత్రువులు ఎదురగుట, మూత్ర సంబంధ రోగములు సాధ్యము. శని ఉన్నచో దీర్ఘ రోగములు సహజము కానీ కష్ట పరిశ్రమ ద్వారా విజయము లభించును; సేవక వర్గము ద్వారా అభ్యుదయము కూడా.\n\nరాహువు ఆరవ భావములో ఉన్నచో విష బాధ, రోగ నిర్ధారణ కష్టమగు మిస్టీరియస్ రోగములు, రహస్య శత్రువులు ఎదురగుట సాధారణము. కేతువు ఉన్నచో అకస్మాత్ రోగములు లేదా దైవిక భాదలు అని భావింపబడు సమస్యలు రావచ్చును.\n\nకొన్ని సందర్భములలో ఈ భావ సంబంధ యోగములు హానికరములు అగును. ఆరవ అధిపతి కేంద్ర త్రికోణములలో పడి లగ్నేశుడితో సంబంధము కల్గించినప్పుడు ఆయుష్షునకు ప్రమాదము సూచితము — దీనిని ఆరూఢ యోగము అని పిలిచెదరు. ఆరవ భావములో పాప గ్రహముల ప్రాబల్యము ఉన్నప్పుడు తీవ్రమైన రోగములు, దీర్ఘ బాధలు ఎదురగు అవకాశము.\n\nపరిహారార్థము శత్రు నివారణకు హనుమాన్ చాలీసా పారాయణ, సుబ్రహ్మణ్య షష్ఠి పూజ అత్యంత ప్రభావకరములు. రోగ నివారణకు తదనుగుణ గ్రహ శాంతి, మహా మృత్యుంజయ మంత్ర జపము సూచితము. ఆయుర్వేద చికిత్స, యోగ సాధన కూడా ప్రయోజనకరములు.",
          english: "The sixth house — known variously as the śatru-bhāva, roga-bhāva, or r̥ṇa-bhāva — governs enemies, diseases, debts, lawsuits, servants, and employment in service. It is one of the dusthānas, but it also belongs to the upacaya group; this dual nature makes it the house from which victory over enemies is also read.\n\nWhen the sixth lord is strong and falls into the tri-ṣaḍāya houses (the third, sixth, or eleventh) or into the other dusthānas (eighth or twelfth), the Harṣa Yoga forms — also known as a viparīta rāja-yoga. Such a native overcomes every enemy that appears. Chronic illnesses do not develop, or if they appear, they resolve quickly. Debts are not a lasting burden; legal cases tend to end favorably; promotions and recognition come in service-oriented work.\n\nWhich planet sits in the sixth shapes the texture of these effects. Sun there brings victory in legal matters connected to the government. Moon may indicate concerns over the mother's health, or psychological struggles for the native. Mars suggests blood disorders or surgery, but also notable success against enemies.\n\nMercury in the sixth is excellent for legal practice and negotiation skills. Jupiter brings legal victory but with possible liver-related concerns. Venus may indicate female adversaries or urinary disorders. Saturn produces chronic illness but also victory through perseverance, with success often arriving through subordinates and labor-intensive work.\n\nRāhu in the sixth points to poisoning risks, hard-to-diagnose illnesses, and hidden enemies. Ketu suggests sudden ailments or troubles considered to be of a spiritual nature.\n\nIn certain configurations these influences become dangerous. When the sixth lord lands in a kendra or trikoṇa and forms a connection with the lagneśa, longevity itself can be at risk — a configuration called Ārūḍha Yoga. Malefic dominance in the sixth signals severe and prolonged illnesses.\n\nFor remedies, Hanumān-cālīsā recitation and Subrahmaṇya-ṣaṣṭhī worship are highly effective for removing enemy obstructions. For diseases, planet-specific śānti rituals along with regular Mahā-Mr̥tyuñjaya japa are recommended. Ayurveda treatment and yoga sādhana also play important supporting roles. [Source: Santhanam ed., p.425]",
          tags: ["shatru-bhava", "6th-house", "enemies-disease-debts-service", "harsha-yoga"], verified: "auto" }
      ]
    },
    47: {
      title_te: "కల్త్ర-భావ-ఫలాధ్యాయః · Kalatra-bhāva-phalādhyāya",
      title_en: "Effects of 7th House (Spouse & Marriage — most consulted)",
      summary_te: "ఈ అధ్యాయములో ఏడవ భావము యొక్క సమగ్ర చర్చ ఉన్నది, ఇది సారావలి గ్రంథ యొక్క విస్తృత విశ్లేషణలోని ఒకటి. కల్త్ర భావము లేదా జీవిత భాగస్వామి భావముగా పరిగణింపబడు ఈ స్థానము నుండి వివాహ సంబంధ అనేక విషయములు చూడవచ్చును. ఏడవ భావాధిపతి దశలో లేదా గోచర గురువు ఏడవ స్థానమును స్పర్శించు సమయములో వివాహ సమయ నిర్ణయము, ఏడవ భావాధిపతి నవాంశ రాశి మరియు ఏడవ భావములోని గ్రహముల ప్రభావముల ద్వారా జీవిత భాగస్వామి గుణ నిర్ణయము, వివాహ సుఖ నిర్ణయము, కుజ దోషము శని ఏడవ స్థానములో ఉండుట రాహు ఏడవ స్థానములో ఉండుట వంటి వివాహ సంబంధ సమస్యలు, మరియు పునర్‌ వివాహ యోగములు ఈ అధ్యాయపు ముఖ్య విషయములు.",
      summary_en: "Comprehensive 7th house (Kalatra-bhāva = spouse-house) analysis — Sārāvalī's extensive treatment. Topics: (1) Marriage timing (during 7th lord's daśā / Jupiter transit); (2) Spouse's character (7th lord's navāṁśa + planets in 7th); (3) Marital happiness; (4) Marriage problems (Maṅgaḷa-doṣa, Saturn-7, Rāhu-7); (5) Re-marriage yogas.",
      verses: [
        { sl: 1, page: 430, source_ed: "Santhanam (Ranjan Publications) ed., p.430",
          sanskrit: "సప్తమ-భావ-అధిపతిః-బలవాన్‌-శుభ-యుతః-తథా / శుక్రః-బలి-భార్యా-సుఖదః-చిర-సహచర-యుక్తః-భవేత్‌ ॥ 1 ॥",
          telugu_bhava: "జీవిత భాగస్వామి సుఖము, వైవాహిక జీవిత స్థితి తెలుసుకొనుటకు ఏడవ భావమునకు అత్యంత ప్రాధాన్యత. ఈ భావమునే సాంప్రదాయికముగా కల్త్ర భావము అని పిలుచుదురు. ఏడవ భావాధిపతి ఎక్కడ ఉన్నాడు, ఎట్టి గ్రహముల యుక్తి దృష్టులు ఆయనపై ఉన్నవి — ఈ రెండు అంశములతో పాటు పురుష జాతకములో శుక్రుని, స్త్రీ జాతకములో గురువును పరిశీలించవలెను.\n\nఏడవ భావాధిపతి బలవంతుడై, శుభ గ్రహముల యుక్తి దృష్టి అతనిపై ఉండి, శుక్రుడు కూడా ఆకాశములో బలవంతుడై ఉన్నచో — జాతకుడికి యోగ్యమైన జీవిత భాగస్వామి తప్పక లభించును. వివాహానంతరము పరస్పర గౌరవము, ప్రేమ, సంతాన సుఖము, ఆర్థిక అభివృద్ధి అన్నీ సహజముగా అమరును. ఏడవ భావమునందే గురువు, శుక్రుడు, బుధుడు వంటి శుభ గ్రహములు ఉన్నచో ఈ యోగము మరింత బలపడును.\n\nవివాహ సమయము నిర్ణయించుటకు మూడు సూచకములు చూడవలెను. మొదటిది ఏడవ భావాధిపతి దశ లేదా అంతర్దశ నడుచుచున్న సమయము. రెండవది గోచరములో గురువు ఏడవ భావమునకు లేదా దాని అధిపతికి దృష్టి చూపు సమయము. మూడవది శుక్రుడు గోచరములో ఏడవ భావమునకు సమీపించు సమయము. ఈ మూడింటిలో ఎక్కువ సూచకములు ఒకే కాలమునందు కలిసిన — అదే వివాహ యోగము సిద్ధించు కాలము.\n\nవివాహమునకు ఆలస్యము కల్గించు యోగములు కూడా కొన్ని ఉన్నవి. ఏడవ భావాధిపతి ఆరు, ఎనిమిది, పన్నెండు భావములలో ఏదైనా ఒకదానిలో పడుట; ఏడవ భావమునందు శని లేదా రాహువు ఉండుట; కుజుడు ఒకటి, నాలుగు, ఏడు, ఎనిమిది, పన్నెండు భావములలో ఏదైనా స్థానమునందు ఉండుట — ఇది మంగళ దోషముగా ప్రసిద్ధి. శుక్రుడు అస్తంగతుడై దుర్బలుడుగా ఉండుట కూడా వివాహ ఆలస్యమునకు ముఖ్య కారణము.\n\nమంగళ దోషము ఉన్న జాతకులకు పెద్దలు భయపడవలసిన అవసరము లేదు. ఈ దోషమునకు అనేక భంగ యోగములు పరాశర సంప్రదాయములో చెప్పబడినవి. వధూ వరుల ఇరువురికీ ఈ దోషము సమానముగా ఉన్నను, ఒకరికి ఉండి మరొకరికి దోష భంగము ఉన్నను — ప్రభావము గణనీయముగా తగ్గును. కావున జాతక పరిశీలనలో దోషముతో పాటు భంగ యోగములను కూడా చూచుట అత్యవశ్యకము. ఆధునిక కాలములో మంగళ దోషమును అతిగా చూపి కుటుంబములలో అనవసర భయము కల్గించుట జరుగుచున్నది; ఇది శాస్త్ర సమ్మతము కాదు.\n\nఏడవ భావములో రాహువు ఉన్నచో విదేశీ లేదా ద్విభాషీ సంబంధ వివాహమునకు అవకాశము ఎక్కువ. కేతువు ఉన్నచో ఆధ్యాత్మిక భావములు కల జీవిత భాగస్వామి లభించును, లేదా దంపతుల మధ్య ఆధ్యాత్మిక విషయములలో అవగాహన భేదములు రావచ్చును. ఏడవ భావమునందు రెండు పాప గ్రహములు ఏకత్రముగా ఉన్నచో, లేదా ఏడవ భావాధిపతి శుక్రుడు ఇరువురూ క్షీణముగా ఉన్నచో, పునర్ వివాహ యోగము కూడా ఆలోచించవలసి ఉండును.\n\nపరిహారార్థము స్త్రీలకు మంగళ గౌరీ వ్రతము, కేదారేశ్వర వ్రతము, వరలక్ష్మీ వ్రతము ముఖ్యములు. స్వయంవర పార్వతీ మంత్రము, లలితా సహస్రనామ పారాయణ అత్యంత ప్రభావకరములు. పురుషులకు రామచంద్రుని ఉపాసన, సీతా రామ కల్యాణ పూజలో పాల్గొనుట శుభప్రదము. శుక్ర గ్రహ శాంతికై శుక్రవారము ఉపవాసము, తెల్లని వస్త్ర దానము, యోగ్యమైన ముహూర్తములో వజ్రము ధారణ చేయవచ్చును.",
          english: "To understand a person's married life and the nature of their spouse, the seventh house holds primary importance. Traditionally called the kalatra-bhāva (the spouse-house), it must be examined alongside two other factors: the planet Venus in male charts, and Jupiter in female charts. Where the seventh-house lord is placed, what planets aspect or conjoin it, and the strength of the relevant kāraka — these together reveal the picture.\n\nWhen the seventh-house lord is strong, well-aspected by benefics, and Venus too is strong in the sky, a worthy life partner is virtually guaranteed. After marriage, mutual respect, love, fertility, and financial growth all unfold naturally. The presence of benefics like Jupiter, Venus, or Mercury within the seventh house itself further strengthens this yoga.\n\nTo time the marriage, three indicators should be examined together. First, the major or sub-period (mahā-daśā or antar-daśā) of the seventh-house lord. Second, transit Jupiter's aspect on either the seventh house or its lord. Third, the transit movement of Venus near the seventh house. When two or more of these align in the same period, that is the window in which marriage tends to materialize.\n\nSeveral combinations cause marital delay. The seventh-house lord placed in the sixth, eighth, or twelfth houses is one. Saturn or Rāhu sitting in the seventh is another. Mars in the first, fourth, seventh, eighth, or twelfth — the well-known Maṅgaḷa-doṣa — is a third. A combust or otherwise weakened Venus also delays things.\n\nFamilies need not panic over Maṅgaḷa-doṣa. Parāśara's tradition lists numerous cancellations: when both partners share the doṣa equally, when one has the doṣa and the other has its bhaṅga, the effect significantly diminishes. Examining the doṣa without also examining its bhaṅga-yogas is an incomplete reading. The modern habit of overstating Maṅgaḷa-doṣa and creating unnecessary anxiety in families is not what the śāstras teach.\n\nRāhu in the seventh often indicates a foreign or cross-cultural marriage. Ketu there suggests a spiritually-inclined partner, or differences arising from spiritual matters. When two malefics together occupy the seventh, or when both the seventh-house lord and Venus are simultaneously weak, the possibility of remarriage may also need to be considered.\n\nFor remedies, women traditionally observe Maṅgaḷa-Gauri vrata, Kedāreśvara vrata, and Varalakṣmī vrata. Recitation of the Lalitā-sahasranāma and the Svayaṁvara-Pārvatī mantra is highly effective. Men benefit from worship of Lord Rāma and participation in Sītā-Rāma-kalyāṇam ceremonies. To strengthen Venus, Friday fasting, donation of white cloth, and — at an auspicious muhūrta — the wearing of a diamond can all be considered. [Source: Santhanam ed., p.430]",
          tags: ["kalatra-bhava", "7th-house", "marriage-comprehensive", "mangala-dosha", "spouse-prediction"], verified: "auto" }
      ]
    },
    48: {
      title_te: "ఆయు-భావ-ఫలాధ్యాయః · Āyu-bhāva-phalādhyāya",
      title_en: "Effects of 8th House (Longevity, Death, Hidden Wealth, Occult)",
      summary_te: "ఈ అధ్యాయములో ఎనిమిదవ భావము యొక్క సమగ్ర చర్చ ఉన్నది. ఇది ఆయు భావము, మృత్యు భావము, రహస్య భావముగా పరిగణింపబడును. ఈ భావ సూచనలు అనేకము — ఆయుష్షు, మరణ విధానము, వారసత్వ సంపదలు, తాంత్రిక యోగ ఆస్ట్రాలజీ వంటి రహస్య విద్యలు, జీవిత సంఘర్షణలు, శస్త్ర గాయములు, మిస్టీరియస్‌ అనుభవములు, ఇన్‌సూరెన్స్‌, పెన్షన్‌ ఇత్యాది ఈ భావమునకు సంబంధితములు. ఎనిమిదవ భావము దుస్థానములలో ఒకటి అయిననూ మోక్ష త్రికోణములోని ముఖ్య భావము కూడా.",
      summary_en: "Comprehensive 8th house (Āyu/Mr̥tyu/Rahasya) analysis. Significations: longevity, mode of death, inheritance, occult sciences (tantric/yoga), life struggles, surgeries/wounds, mysterious experiences, insurance, pension. Note: dusthāna BUT also mokṣa-bhāva.",
      verses: [
        { sl: 1, page: 440, source_ed: "Santhanam (Ranjan Publications) ed., p.440",
          sanskrit: "అష్టమ-భావ-అధిపతిః-బలవాన్‌-శుభ-యుతః-కేంద్ర-త్రికోణ-గతః / దీర్ఘాయుః-రహస్య-విద్యా-నిపుణః-భవేత్‌-తేన ॥ 1 ॥",
          telugu_bhava: "ఎనిమిదవ భావమునే ఆయు భావము, మృత్యు భావము, రహస్య భావము అని పిలుచుదురు. జాతకుని ఆయుష్షుకు, మరణ స్వరూపమునకు, వారసత్వ సంపదకు, రహస్య విద్యలకు, జీవితపు సంఘర్షణలను ఎదుర్కొను శక్తికి ఇది ముఖ్య సూచకము. ఇది దుస్థానములలో ఒకటి కానీ మోక్ష త్రికోణములోని ముఖ్య భావము కూడా.\n\nఈ భావాధిపతి బలముగా ఉండి శుభ గ్రహముల యుక్తిలో, కేంద్ర త్రికోణములో లేదా ఎనిమిదవ భావములోనే స్థితి కల్గియున్నప్పుడు దీర్ఘాయుష్షు యోగము సిద్ధించును. ఇట్టి జాతకులు దీర్ఘ జీవితము అనుభవించుదురు; శతాబ్దమునకు సమీపమగు ఆయుష్షు కూడా అరుదు కాదు. తాంత్రిక సాధన, యోగ, మంత్ర సిద్ధి, ఆస్ట్రాలజీ వంటి రహస్య విద్యలయందు సహజమైన ఆకర్షణ ఉండును. తండ్రి తల్లి అత్త మామల ద్వారా వారసత్వ సంపదలు లభించుట సహజము. ఇన్‌సూరెన్స్, పెన్షన్, ప్రావిడెంట్ ఫండ్ వంటి వనరుల నుండి మంచి ప్రయోజనము పొందుదురు.\n\nఎనిమిదవ అధిపతి దుస్థానములలో అనగా ఆరు లేదా పన్నెండు భావములలో పడిన సరళ యోగము ఏర్పడును. ఇది విపరీత రాజయోగములలో ఒకటి. అకస్మాత్ ధన లాభములు — వారసత్వ, లాటరీ, స్టాక్ మార్కెట్ పెద్ద విజయములు — ఈ యోగము యొక్క ముఖ్య ఫలములు. మృత్యు భయము నుండి విముక్తి, దీర్ఘాయుష్షు కూడా సహజము.\n\nఏ గ్రహము ఎనిమిదవ భావములో ఉన్నదో దాని ప్రకారము ఫలము యొక్క స్వరూపము మారును. సూర్యుడు ఇచ్చట ఉన్నచో ఆయుష్షుకు సంబంధించిన సమస్యలు లేదా తండ్రితో దూరము సూచితము. చంద్రుడు ఉన్నచో తల్లి ఆరోగ్యమునకు చింతలు, మానసిక సంఘర్షణలు రావచ్చును. కుజుడు ఉన్నచో శస్త్ర చికిత్సలు, రక్త సంబంధ రోగములు, ఆకస్మిక సంఘటనలు సాధ్యము.\n\nబుధుడు ఇచ్చట ఉన్నచో గణిత నైపుణ్యము, రహస్య విద్యలయందు పరిశోధన ఆసక్తి సహజము. గురువు ఎనిమిదవ భావములో ఉండుట అత్యంత శుభము — ఆయుష్షుకు రక్షణ, మోక్ష సాధనలో పురోగతి, రహస్య జ్ఞానము లభించును. శుక్రుడు ఉన్నచో వారసత్వ ద్వారా సంపదలు కానీ స్త్రీ సంబంధ సమస్యలు కూడా రావచ్చును. శని ఉన్నచో దీర్ఘాయుష్షు, రహస్య విద్యలయందు దీర్ఘ సాధన, చిర రోగములు — ఈ మూడు సహజము.\n\nరాహువు ఎనిమిదవ భావములో విష బాధ, రహస్య శత్రువులు, తాంత్రిక సాధనలయందు ఆకర్షణ సూచించును. కేతువు ఉన్నచో మోక్ష సాధన, ఆధ్యాత్మిక అనుభవములు, కుండలినీ జాగృతి వంటి విశేష ఆధ్యాత్మిక యోగములు సహజము.\n\nఎనిమిదవ భావములో పాప గ్రహముల ప్రాబల్యము ఉండి లగ్నేశుడు దుర్బలముగా ఉన్నప్పుడు ఆయురిష్ట యోగము ఏర్పడును — ఇది ఆయుష్షుకు ప్రమాదకరము. ఇట్టి జాతకులకు మహా మృత్యుంజయ మంత్ర జపము ఒక లక్షా ఇరువది ఐదు వేలు లేదా పదకొండు లక్షల పారాయణ చేయించుట, ప్రతి సోమవారము రుద్ర అభిషేకము, దుర్గా సప్తశతీ పారాయణ — ఇవన్నీ అత్యంత ప్రయోజనకరములు. తాంత్రిక సాధన చేయవలసి వచ్చిన యోగ్యమైన గురువు ద్వారానే చేయవలెను.",
          english: "The eighth house — also known as the āyu-bhāva, mr̥tyu-bhāva, or rahasya-bhāva — governs longevity, the manner of death, inherited wealth, the occult sciences, and the inner strength to weather life's struggles. Although classified as a dusthāna, it also belongs to the mokṣa-trikoṇa, making it spiritually significant.\n\nWhen the eighth lord is strong, joined with benefics, and placed either in a kendra/trikoṇa or in the eighth itself, a long-life yoga is established. Such natives often live to advanced age — approaching a century is not unusual. They have a natural pull toward tantric practice, yoga, mantra-siddhi, and esoteric subjects like astrology. Inherited wealth from father, mother, uncles, or aunts often comes their way. They tend to do well from insurance, pensions, and similar long-term financial arrangements.\n\nWhen the eighth lord falls into the sixth or twelfth — both dusthānas — the Sarala Yoga forms, one of the viparīta rāja-yogas. Sudden wealth gains through inheritance, lottery, or major stock-market wins are typical signatures, along with fearlessness of death and long life.\n\nWhich planet sits in the eighth shapes the experience further. Sun there raises concerns about longevity or distance from the father. Moon may bring health concerns about the mother and inner emotional struggles. Mars indicates surgeries, blood-related conditions, or sudden events.\n\nMercury in the eighth produces strong mathematical aptitude and natural curiosity for the occult. Jupiter here is highly auspicious — protection of life, progress in mokṣa-sādhana, and access to esoteric knowledge. Venus brings inherited wealth alongside potential issues with women. Saturn produces longevity, deep capacity for occult practice, and chronic illness.\n\nRāhu in the eighth points to poison risks, hidden enemies, and an attraction to tantric practices. Ketu indicates mokṣa-sādhana, profound spiritual experiences, and possibly even Kuṇḍalinī awakening.\n\nWhen malefics dominate the eighth and the lagna lord is weak, an ayuriṣṭa-yoga forms — a real risk to longevity. For such natives, lakh-and-a-quarter or eleven-lakh recitation of the Mahā-Mr̥tyuñjaya mantra, Monday Rudra-abhiṣeka, and Durgā-saptaśatī recitation are highly beneficial. Tantric practice, when undertaken, must be only under a qualified guru. [Source: Santhanam ed., p.440]",
          tags: ["ayu-bhava", "8th-house", "longevity-occult-inheritance", "sarala-yoga"], verified: "auto" }
      ]
    },
    49: {
      title_te: "భాగ్య-భావ-ఫలాధ్యాయః · Bhāgya-bhāva-phalādhyāya",
      title_en: "Effects of 9th House (Fortune, Father, Dharma)",
      summary_te: "ఈ అధ్యాయములో తొమ్మిదవ భావము యొక్క సమగ్ర చర్చ ఉన్నది. ఇది భాగ్య భావము, ధర్మ భావము, పిత్రు భావము, గురు భావము, తీర్థ భావముగా పరిగణింపబడును. ఈ భావ సూచకములు తండ్రి, ధర్మ నిష్ఠ, భాగ్యము, దీర్ఘ యాత్రలు, తీర్థయాత్రలు, ఉన్నత విద్య, ఆధ్యాత్మిక గురువు, పూర్వ జన్మ పుణ్యము. ముఖ్య యోగములలో తొమ్మిదవ భావాధిపతి బలి మరియు గురువు బలి కల్గిన ఉన్నత భాగ్య యోగము, తొమ్మిదవ అధిపతి కేంద్ర త్రికోణములో ఉండు రాజ యోగము, సూర్యుడు తొమ్మిదవ స్థానములో ఉండుట వలన కల్గు తండ్రితో సన్నిహిత సంబంధము, శని లేదా రాహువు తొమ్మిదవ స్థానములో ఉండుట వలన పిత్రు సుఖము లోపించుట మరియు ధర్మ నిష్ఠ తగ్గుట ఈ ముఖ్య సూచనలు.",
      summary_en: "Comprehensive 9th house (Bhāgya/Dharma/Pitr̥/Guru/Tīrtha) analysis. Significations: father, dharma-niṣṭha, fortune, long travels, pilgrimages, higher education, spiritual guru, pūrva-puṇya. Key yogas: (1) Strong 9th lord + Jupiter = elevated fortune; (2) 9th lord in kendra/trikōṇa = rāja-yoga; (3) Sun + 9 = close father bond; (4) Saturn/Rāhu in 9 = lacks paternal happiness, weakened dharma.",
      verses: [
        { sl: 1, page: 445, source_ed: "Santhanam (Ranjan Publications) ed., p.445",
          sanskrit: "నవమ-భావ-అధిపతిః-బలవాన్‌-గురు-యుక్తః-తథా / ధర్మ-నిష్ఠః-భాగ్యవాన్‌-తీర్థ-యాత్రీ-భవేత్‌-తేన ॥ 1 ॥",
          telugu_bhava: "తొమ్మిదవ భావము జాతక శాస్త్రములో అత్యంత ముఖ్యమైన భావములలో ఒకటి. ఇది తండ్రికి, ధర్మ నిష్ఠకు, భాగ్యమునకు, దీర్ఘ యాత్రలకు, తీర్థ యాత్రలకు, ఉన్నత విద్యకు, ఆధ్యాత్మిక గురువుకు, పూర్వ జన్మ పుణ్యమునకు సూచకము. ఈ భావాధిపతియును గురువును ఇరువురును బలముగా ఉండి పరస్పర సంబంధము కల్గియున్నచో — ఉన్నత భాగ్య యోగము సిద్ధించును.\n\nఇట్టి జాతకుడు సహజముగానే ధర్మ నిష్ఠాపరుడు. న్యాయ నీతిని పాటించుట వలన సమాజములో గౌరవ స్థానము పొందును. విద్యా ధర్మ రంగములలో ప్రసిద్ధి సహజము. పూర్వ జన్మ సుకృతముచే ఈ జన్మలో సర్వ సుఖములు అమరును; కష్టములు ఎదురైననూ అనూహ్య మార్గములలో సహాయము లభించును. తీర్థ యాత్రలు చేయుట వీరికి ప్రియము — కాశీ, రామేశ్వరము, తిరుపతి, చార్ ధామ వంటి యాత్రలు జీవితకాలములో ఏర్పడును.\n\nఉన్నత విద్యలో రాణింపు ఈ యోగము యొక్క ముఖ్య ఫలము. విద్యాధికారిగా, విశ్వవిద్యాలయ అధ్యాపకుడిగా, లేదా సాహిత్య ధర్మ శాస్త్ర పండితుడిగా ప్రసిద్ధి పొందుట సాధారణము. తండ్రి దీర్ఘాయుష్షు అనుభవించుట, తండ్రి ద్వారా ఆస్తి సంపదలు లభించుట, తండ్రి తరువాత తండ్రి సదృశ గౌరవ స్థానము పొందుట — ఇవన్నీ ఈ భావ ప్రభావములు. ఆధ్యాత్మిక సాధనలో పయనించువారికి యోగ్య గురువు లభించుట కూడా ఈ యోగము సూచించును.\n\nతొమ్మిదవ భావములో గురువు ఉండుట హంస యోగమునకు దారితీసి, జాతకుడిని మహా పండితుడిగా, ధర్మ గురువుగా చేయును. సూర్యుడు ఉన్నచో తండ్రి భక్తి, రాజ సన్మానములు సహజము. తొమ్మిదవ అధిపతియును పదవ అధిపతియును పరస్పర సంబంధము కల్గించినప్పుడు — దీనిని ధర్మ కర్మ సంబంధ అని పిలిచెదరు. ఇది అత్యంత శుభ రాజయోగము; ధర్మానుగుణమైన జీవనోపాధి, గౌరవప్రదమైన ఉద్యోగము లభించును.\n\nఅదే విధముగా శని లేదా రాహువు తొమ్మిదవ భావములో ఉన్నప్పుడు తండ్రి సుఖము లోపించును; ధర్మ నిష్ఠ తగ్గు అవకాశము ఉండును. ఈ భావాధిపతి దుస్థానములో పడిన భాగ్య క్షయము సూచితము. తొమ్మిదవ భావములో పాప గ్రహముల ప్రాబల్యము ధర్మ విముఖతకు దారితీయును.\n\nపరిహారార్థము గురు బృహస్పతి స్తోత్ర పారాయణ, గురువార ఉపవాసము, పసుపు రంగు వస్త్ర దానము, యోగ్యమైన ముహూర్తములో పుష్యరాగము ధారణ — ఇవన్నీ ప్రభావకరములు. విష్ణు సహస్రనామ పారాయణ ప్రతిదినమూ చేయుట, వీలైనప్పుడల్లా తీర్థ యాత్రలు చేయుట, బ్రాహ్మణులకు భోజన దానము, ప్రతి అమావాస్య నాడు పిత్రు తర్పణములు సమర్పించుట — ఇవి తండ్రికి, పిత్రు దేవతలకు తృప్తి కల్గించు మార్గములు.",
          english: "The ninth house holds a position of profound importance in jyotiṣa. It signifies the father, dharma, fortune, long journeys, pilgrimages, higher education, the spiritual teacher, and the merit accumulated from past lives. When both the ninth lord and Jupiter are strong and connected to each other, an elevated fortune-yoga takes shape.\n\nSuch a person is naturally inclined toward dharma. By following ethical principles, they earn lasting respect in society and tend to find prominence in fields connected to learning or religion. Past-life merit ensures comforts in this life; even when difficulties arise, help appears through unexpected channels. Pilgrimages exert a strong pull — visits to Kāśī, Rāmeśvaram, Tirupati, the Char Dhām, and similar sacred sites tend to occur over a lifetime.\n\nExcellence in higher education is among this yoga's signature effects. Becoming an academic, a university professor, or a śāstra scholar is common. The father typically lives long, ancestral property comes to the native, and after the father's passing the native often steps into a similar role of respect. For those drawn to spiritual practice, a worthy guru also tends to appear.\n\nJupiter in the ninth produces Haṁsa Yoga, lifting the native to the standing of a major pandit or dharma-guru. The Sun there indicates devotion to the father and royal recognition. When the ninth and tenth lords form a relationship — known as the Dharma-Karma sambandha — an exceptional rāja-yoga results, bringing a livelihood that aligns with one's dharma.\n\nSaturn or Rāhu in the ninth, by contrast, weakens paternal happiness and may dilute the native's commitment to dharma. The ninth lord falling into a dusthāna signifies erosion of fortune. Multiple malefics in the ninth often produce indifference to dharma altogether.\n\nFor remedies, recitation of the Br̥haspati stotra, Thursday fasting, donation of yellow cloth, and — at an appropriate muhūrta — wearing of yellow sapphire are all effective. Daily Viṣṇu-sahasranāma recitation, pilgrimages whenever possible, feeding brāhmaṇas, and offering pitr̥-tarpaṇa on every amāvāsyā all serve to honor the father and the ancestral lineage. [Source: Santhanam ed., p.445]",
          tags: ["bhagya-bhava", "9th-house", "father-dharma-fortune", "hamsa-yoga"], verified: "auto" }
      ]
    },
    50: {
      title_te: "కర్మ-భావ-ఫలాధ్యాయః · Karma-bhāva-phalādhyāya",
      title_en: "Effects of 10th House (Career & Profession)",
      summary_te: "ఈ అధ్యాయములో పదవ భావము యొక్క సమగ్ర చర్చ ఉన్నది. ఇది కర్మ భావము, రాజ్య భావము, పితృ భావముగా పరిగణింపబడును. జాతకుని ఉద్యోగము, వ్యాపారము, ప్రసిద్ధి, సామాజిక స్థానము, తండ్రి సంబంధ ఫలములు ఇచ్చట సమగ్రముగా చర్చింపబడుచున్నవి. పదవ భావాధిపతి స్థితి ద్వారా ఉద్యోగ నిర్ణయము, పదవ భావములోని గ్రహముల ద్వారా ఏ గ్రహ సంబంధ వృత్తి అను నిర్ణయము, అమల సింహాసన రాజ యోగ ధన యోగ మొదలగు కర్మ యోగములు, ప్రభుత్వ అధికార సూచకుడైన సూర్యుని కారకత్వ ప్రభావము, మరియు నవాంశ చార్ట్‌లోని పదవ భావాధిపతి ద్వారా సూక్ష్మ వృత్తి నిర్ణయము ఈ అధ్యాయపు ముఖ్య విభాగములు.",
      summary_en: "Detailed analysis of 10th house (Karma/Rājya/Pitr̥) — career, business, fame, social status, paternal effects. Sections: (1) 10th lord placement = career field; (2) Planets in 10th = profession-type; (3) Karma-yogas (Amala, Siṁhāsana, Rāja-yoga, Dhana-yoga); (4) Sun's role (government); (5) Navāṁśa-10th-lord (subtle career nuance).",
      verses: [
        { sl: 1, page: 460, source_ed: "Santhanam (Ranjan Publications) ed., p.460",
          sanskrit: "దశమ-భావ-అధిపతిః-కేంద్ర-త్రికోణ-గతః-బలవాన్‌ / ఉచ్చ-స్వ-క్షేత్ర-యుతః-తదా-వృత్తి-విజయః-సుఖ-ప్రదః ॥ 1 ॥",
          telugu_bhava: "పదవ భావమునే కర్మ భావము అని, రాజ్య భావము అని, పిత్రు భావము అని కూడా పిలిచెదరు. ఇది జాతకుని ఉద్యోగమునకు, వ్యాపారమునకు, సామాజిక గౌరవమునకు, ప్రసిద్ధికి ముఖ్య స్థానము. తండ్రి సంబంధ ఫలములు కూడా ఇచ్చటి నుండి చూడబడును.\n\nఈ భావాధిపతి కేంద్ర త్రికోణములలో, ఉచ్చ స్వ క్షేత్ర మిత్ర రాశులలో, శుభ గ్రహముల యుక్తి దృష్టితో ఉన్నప్పుడు ఉద్యోగ విజయ యోగము సిద్ధించును. ఇట్టి జాతకుడు స్థిరమైన గౌరవప్రద ఉద్యోగము పొందును. తరచుగా ప్రమోషన్లు, పదవీ ఔన్నత్యము లభించును. చేయు పనియందు సహజమైన సంతృప్తి కల్గును; ఈ ఉద్యోగము జీవితకాలము కొనసాగును.\n\nవృత్తి యొక్క స్వరూపము పదవ భావములో ఉన్న గ్రహముల ప్రకారము లేదా పదవ భావాధిపతి స్వభావము ప్రకారము నిర్ణయింపబడును. సూర్యుడు ప్రభావములో ప్రభుత్వ ఉన్నతాధికారి, రాజకీయ నాయకుడు, వైద్యుడు అగు అవకాశము. చంద్రుడు ఉన్నచో వ్యవసాయము, పాల వెన్న వ్యాపారము, నౌకా మత్స్య పరిశ్రమలు, నర్సింగ్, హోటల్ నిర్వహణ — ఇవి ముఖ్యములు. కుజుని ప్రభావములో సైనిక సేవ, పోలీసు ఉద్యోగము, ఇంజినీరింగ్, శస్త్ర చికిత్స, మెకానికల్ రంగము సహజము.\n\nబుధుని ప్రభావములో వ్యాపారము, వాణిజ్యము, గణితము, రచన, ఆధునిక కాలములో సాఫ్ట్‌వేర్ ఇన్‌ఫర్మేషన్ టెక్నాలజీ, చార్టర్డ్ అకౌంటెన్సీ — ఇవి అమరు రంగములు. గురువు ఉన్నచో విద్యా రంగము, న్యాయ వృత్తి, పౌరోహిత్యము, బ్యాంకింగ్, ఆర్థిక సలహాదారు — ఇవి సూచితములు. శుక్రుడు ఉన్నచో కళలు, సంగీతము, సినిమా, రత్నాలంకార వ్యాపారము, ఫ్యాషన్, బ్యూటీ, లగ్జరీ సేవలు — ఈ రంగములు. శని ఉన్నచో శ్రమ ప్రధాన పనులు, న్యాయ వ్యవస్థ, పరిశ్రమలు, మైనింగ్, రియల్ ఎస్టేట్, దీర్ఘకాలిక ప్రాజెక్టులు అమరును.\n\nఈ భావములో కొన్ని విశేష యోగములు ఉన్నవి. పదవ భావములో శుభ గ్రహము ఏకాకిగా (ఇతర గ్రహముల యుక్తి లేకుండా) ఉండుట అమల యోగము — నిర్మలమైన ప్రసిద్ధి, ధర్మానుగుణమైన ఉద్యోగము సూచించును. లగ్నేశుడును పదవ అధిపతియును సింహ రాశిలో కేంద్రములో ఉండుట సింహాసన యోగము — రాజ సదృశ స్థానము. పదవ అధిపతియును మరొక కేంద్రాధిపతి లేదా త్రికోణాధిపతి సంబంధము కల్గించినప్పుడు అది కర్మ రాజయోగము.\n\nనవాంశ చార్ట్‌లో పదవ భావాధిపతి ఎక్కడ ఉన్నాడో అన్నది వృత్తి యొక్క సూక్ష్మ స్వరూపమును స్పష్టము చేయును. రాశి చార్ట్ మరియు నవాంశ చార్ట్ ఇరువురికీ సంబంధించిన సూచనలు కలిసి చూచినప్పుడే వృత్తి విషయమై పూర్ణ నిర్ణయము సాధ్యమగును.",
          english: "The tenth house, also known as the karma-bhāva, rājya-bhāva, or pitr̥-bhāva, is the central indicator of career, business, social status, and public reputation. Effects related to the father are also read here.\n\nWhen this house's lord occupies a kendra or trikoṇa, sits in a sign of exaltation, ownership, or friendship, and is well-aspected by benefics, the standard 'career-success yoga' is established. The native obtains stable, dignified employment. Promotions and elevations come at regular intervals. There is genuine satisfaction in the work itself, and the position usually endures across a working lifetime.\n\nThe nature of the work is determined by the planets occupying the tenth house, or by the disposition of the tenth lord. Sun's influence points toward senior government office, political leadership, or medicine. Moon brings agriculture, dairy, water-related industries, nursing, or hospitality. Mars suggests military, police, engineering, surgery, or mechanical professions.\n\nMercury's influence indicates trade and commerce, mathematics, writing, and — in modern times — IT, software, and chartered accountancy. Jupiter brings education, law, priesthood, banking, or financial advisory roles. Venus points to the arts, music, cinema, jewelry, fashion, beauty, and luxury services. Saturn governs labor-intensive work, the legal system, heavy industry, mining, real estate, and long-term projects.\n\nSeveral notable yogas are connected to this house. A solitary benefic in the tenth (without other planetary contact) forms Amala Yoga — pure reputation and dharma-aligned work. The lagna lord and tenth lord together in Leo in a kendra produce Siṁhāsana Yoga — a king-like position. When the tenth lord forms a relationship with another kendra or trikoṇa lord, a Karma Rāja-yoga results.\n\nWhere the tenth lord sits in the navāṁśa chart adds a further layer of nuance to the vocational picture. Only by reading the rāśi chart and the navāṁśa together does a complete picture of career emerge. [Source: Santhanam ed., p.460]",
          tags: ["karma-bhava", "10th-house", "career-analysis", "graha-vritti"], verified: "auto" }
      ]
    },
    51: {
      title_te: "లాభ-భావ-ఫలాధ్యాయః · Lābha-bhāva-phalādhyāya",
      title_en: "Effects of 11th House (Gains, Income, Friends, Elder Sibling)",
      summary_te: "ఈ అధ్యాయములో పదకొండవ భావము యొక్క సమగ్ర చర్చ ఉన్నది. ఇది లాభ భావము లేదా ఆదాయ భావముగా పరిగణింపబడును. ఈ భావ సూచనలు అనేకము — లాభములు, స్థిర ఆదాయము, మిత్రులు, పెద్ద సోదరుడు, కోరికల ఫల ప్రాప్తి, విస్తృత సాంఘిక నెట్‌వర్క్‌, రాజ సంబంధ అధికారులతో పరిచయములు ఇత్యాది ఈ భావమునకు సంబంధితములు. ఇది ఉపచయ భావములలో ఒకటి మరియు కామ త్రికోణములో చివరిది, కావున అన్ని విధ లాభములకు ఇది అత్యంత ముఖ్యము.",
      summary_en: "Comprehensive 11th house (Lābha) analysis. Significations: gains, regular income, friends, elder sibling, fulfillment of desires, social network, royal officials. Note: upacaya-bhāva + kāma-trikoṇa — important for all gains.",
      verses: [
        { sl: 1, page: 460, source_ed: "Santhanam (Ranjan Publications) ed., p.460",
          sanskrit: "ఏకాదశ-భావ-అధిపతిః-బలవాన్‌-శుభ-యుతః-తథా / లాభవంతః-మిత్ర-బహులః-సర్వ-సుఖ-యుక్తః-భవేత్‌ ॥ 1 ॥",
          telugu_bhava: "పదకొండవ భావమునే లాభ భావము లేదా ఆదాయ భావము అని పిలుచుదురు. ఇది ఉపచయ భావములలో ఒకటి, కామ త్రికోణములో చివరి స్థానము. లాభములకు, స్థిర ఆదాయమునకు, మిత్రులకు, పెద్ద సోదరునికి, కోరికల ఫల ప్రాప్తికి, విస్తృత సాంఘిక నెట్‌వర్క్‌నకు ఇది ప్రధాన సూచకము.\n\nఈ భావాధిపతి బలముగా ఉండి శుభ గ్రహముల యుక్తి దృష్టి కల్గి కేంద్ర త్రికోణములలో పడిన లాభ యోగము సిద్ధించును. ఇట్టి జాతకుడికి ఉద్యోగము లేదా వ్యాపారము ద్వారా నిరంతర ఆదాయము లభించును. ఆదాయ వనరులు ఒకే రకము కాకుండా అనేక మూలముల నుండి వచ్చును — వేతనము, వ్యాపార లాభములు, పెట్టుబడుల ఆదాయము, వడ్డీలు ఇత్యాది.\n\nమిత్ర బంధుత్వ సుఖము ఈ యోగము యొక్క మరొక ముఖ్య ఫలము. విస్తృతమైన సామాజిక నెట్‌వర్క్, ఉన్నత స్థాయి వ్యక్తులతో సంబంధములు సహజము. పెద్ద సోదరుని ద్వారా సహాయము లభించుట, అతని విజయమును చూచుట కూడా సాధారణము. జీవితములో పెట్టుకొన్న కోరికలు చాలా వరకు ఫలించును.\n\nఏ గ్రహము పదకొండవ భావములో ఉన్నదో దాని ప్రకారము లాభ మూలము నిర్ణయింపబడును. సూర్యుడు ఇచ్చట ఉన్నచో ప్రభుత్వ మూలముల నుండి లాభములు. చంద్రుడు ఉన్నచో స్త్రీల ద్వారా లేదా జల సంబంధ వ్యాపారముల ద్వారా ఆదాయము. కుజుడు ఉన్నచో సైనిక, రియల్ ఎస్టేట్, లోహ వ్యాపారముల ద్వారా లాభము.\n\nబుధుడు ఉన్నచో వ్యాపారము, వాణిజ్యము, ఆధునిక కాలములో సాఫ్ట్‌వేర్ సేవలు ద్వారా లాభములు. గురువు ఇచ్చట ఉండుట అత్యంత శుభము — విద్యా రంగము, సలహా రంగము, బ్యాంకింగ్, ఆర్థిక సేవల ద్వారా విస్తృత ఆదాయములు. శుక్రుడు ఉన్నచో కళలు, సినిమా, రెస్టారెంట్, లగ్జరీ సేవల ద్వారా లాభములు. శని ఉన్నచో పరిశ్రమలు, మైనింగ్, దీర్ఘకాలిక పెట్టుబడుల ద్వారా క్రమ క్రమమైన ఆదాయము. రాహువు ఉన్నచో విదేశీ మూలములు, టెక్నాలజీ, అంతర్జాతీయ నెట్‌వర్క్ ద్వారా లాభములు; ఆధునిక కాలములో సోషల్ మీడియా ద్వారా కూడా. కేతువు ఉన్నచో ఆధ్యాత్మిక సంబంధ ఆదాయములు, ఆశ్రమ విరాళములు సహజము.\n\nపదకొండవ అధిపతి దుస్థానములలో పడి పాప గ్రహ యుక్తి కల్గియున్నప్పుడు ఆదాయము క్షీణించును. మిత్రులతో విభేదములు, పెద్ద సోదరునికి కష్టములు ఎదురగు అవకాశము. పరిహారార్థము లక్ష్మీ అష్టోత్తర పారాయణ, శ్రీ సూక్త పారాయణ, కుబేర యంత్ర పూజ, శుక్రవార లక్ష్మీ నారాయణ ఆరాధన — ఇవన్నీ ప్రభావకరములు. మిత్రుల సహాయము ద్వారా అభ్యుదయము పొందుట కూడా ఈ భావ ప్రభావములోనే.",
          english: "The eleventh house — known as the lābha-bhāva or āyā-bhāva — is among the upacaya houses and stands as the final station of the kāma-trikoṇa. It is the principal indicator of gains, regular income, friends, the elder sibling, desire-fulfillment, and the breadth of one's social network.\n\nWhen this house's lord is strong, joined with benefics, and placed in a kendra or trikoṇa, the income-and-gains yoga is established. Such natives draw continuous income from their job or business. Their income tends to come not from a single channel but from several — salary, business profits, investment returns, interest earnings — all running in parallel.\n\nFriendship and connection form another core dimension of this yoga. A wide social network, high-status acquaintances, and access to influential circles come naturally. The elder sibling often plays a supportive role and tends to do well in their own life. Most desires the native sets out with eventually find fulfillment.\n\nWhich planet sits in the eleventh shapes the source of gains. Sun there points to income from government sources. Moon brings gains through women or water-related businesses. Mars indicates earnings from military service, real estate, or metals. Mercury produces gains from trade, commerce, and — in modern terms — from software and IT services.\n\nJupiter in the eleventh is among the most auspicious placements possible — vast income through education, advisory roles, banking, or financial services. Venus brings earnings through the arts, cinema, restaurants, and luxury industries. Saturn produces steady income from heavy industry, mining, and long-term investment. Rāhu indicates gains from foreign sources, technology, international networks, and — in our era — even social media. Ketu often signals income connected to spiritual organizations and ashram-related work.\n\nWhen the eleventh lord falls into a dusthāna and is afflicted by malefics, income diminishes; conflicts with friends and difficulties for the elder sibling may surface. For remedies, recitation of the Lakṣmī-aṣṭottara, the Śrī-sūkta, and worship of the Kubera-yantra are all effective. Friday Lakṣmī-Nārāyaṇa worship is also strongly recommended. Building wealth through the genuine support of friends is itself a hallmark of this yoga. [Source: Santhanam ed., p.460]",
          tags: ["labha-bhava", "11th-house", "gains-income-friends-network"], verified: "auto" }
      ]
    },
    52: {
      title_te: "వ్యయ-భావ-ఫలాధ్యాయః · Vyaya-bhāva-phalādhyāya",
      title_en: "Effects of 12th House (Expenses, Foreign, Mokṣa, Sleep)",
      summary_te: "ఈ అధ్యాయములో పన్నెండవ భావము యొక్క సమగ్ర చర్చ ఉన్నది. ఇది వ్యయ భావము లేదా మోక్ష భావముగా పరిగణింపబడును. ఈ భావ సూచనలు అనేకము — ఖర్చులు, నష్టములు, విదేశ సంచారము, శయన సుఖము, మోక్ష సాధన, రహస్య శత్రువులు, ఇమ్మిగ్రేషన్‌, ఆధ్యాత్మిక సంస్థలు, ఆశ్రమ సేవ, ఆసుపత్రి నిర్బంధము, జైలు సమస్యలు ఇత్యాది ఈ భావమునకు సంబంధితములు. పన్నెండవ భావము దుస్థానములలో ఒకటి అయిననూ మోక్ష భావముగా అత్యంత ప్రాముఖ్యత కల్గినది, ఆధ్యాత్మిక అభివృద్ధికి అత్యంత ముఖ్యమైన భావము.",
      summary_en: "Comprehensive 12th house (Vyaya) analysis. Significations: expenses, losses, foreign travel, sleep-comfort, mokṣa-sādhana, hidden enemies, immigration, spiritual organizations, ashram-service, hospital-confinement, jail problems. Note: dusthāna BUT also mokṣa-bhāva — most important for spiritual progress.",
      verses: [
        { sl: 1, page: 470, source_ed: "Santhanam (Ranjan Publications) ed., p.470",
          sanskrit: "ద్వాదశ-భావ-అధిపతిః-దుస్థానే-విపరీత-రాజయోగదః / మోక్ష-సాధన-విదేశ-సుఖదః-భవేత్‌-తేన ॥ 1 ॥",
          telugu_bhava: "పన్నెండవ భావమునే వ్యయ భావము లేదా మోక్ష భావము అని పిలుచుదురు. ఖర్చులకు, నష్టములకు, విదేశ సంచారమునకు, శయన సుఖమునకు, మోక్ష సాధనకు, రహస్య శత్రువులకు, ఆశ్రమ సేవకు, ఆసుపత్రి నిర్బంధమునకు ఇది సూచకము. ఇది దుస్థానములలో ఒకటి కానీ మోక్ష త్రికోణములోని చివరి, అత్యంత ముఖ్యమైన భావము — ఆధ్యాత్మిక అభివృద్ధికి ఇది ప్రధాన స్థానము.\n\nఈ భావాధిపతి దుస్థానములలో అనగా ఆరు లేదా ఎనిమిది భావములలో పడిన విమల యోగము ఏర్పడును. ఇది విపరీత రాజయోగములలో ఒకటి. ఇట్టి జాతకుడు అనవసర ఖర్చులను నియంత్రించుకొను సామర్థ్యము కల్గియుండును; పొదుపు నైపుణ్యము సహజము. విదేశీ నివాసము, విదేశీ ఉద్యోగము, లేదా విదేశీ వ్యాపారము ద్వారా అభ్యుదయము సాధ్యము. ఆధ్యాత్మిక సాధనలో కూడా ముందుకు సాగును. ధర్మ కార్యములలో ధనమును వ్యయించు దానశీలము ఈ యోగము యొక్క విశేష ఫలము. స్వప్నములలో దైవ దర్శనము పొందు అనుభవములు కూడా అరుదు కాదు.\n\nఏ గ్రహము పన్నెండవ భావములో ఉన్నదో దాని ప్రకారము ఫలము యొక్క స్వరూపము మారును. సూర్యుడు ఇచ్చట ఉన్నచో తండ్రితో దూరము లేదా ప్రభుత్వ సంబంధ నష్టములు రావచ్చును. చంద్రుడు ఉన్నచో విదేశ నివాసము, తల్లితో విడిపోవుట సాధారణము. కుజుడు ఉన్నచో శస్త్ర గాయములు, శత్రు యోగములు, విదేశములో సంఘర్షణలు ఎదురగు అవకాశము.\n\nబుధుడు ఇచ్చట ఉన్నచో విదేశ వ్యాపారము లేదా విదేశ విద్య సహజము. గురువు ఉండుట అత్యంత శుభము — మోక్ష సాధన, ఆశ్రమ సేవ, విదేశీ ఆధ్యాత్మిక విద్య, తీర్థయాత్రలు అన్నీ ఇచ్చట సూచితములు. శుక్రుడు ఉన్నచో విదేశీ విలాస జీవితము, శయన సుఖము, రహస్య ప్రేమ సంబంధములు. శని ఉన్నచో దీర్ఘ విదేశీ నివాసము లేదా ఆశ్రమ సన్యాస జీవితము; కష్ట సందర్భములలో జైలు సమస్యలు కూడా రావచ్చును.\n\nరాహువు పన్నెండవ భావములో ఇమ్మిగ్రేషన్, విదేశీ సెటిల్‌మెంట్, ఎన్‌ఆర్‌ఐ జీవితము సూచించును. కేతువు ఉన్నచో మోక్ష సాధన, తీర్థయాత్రలు, ఆధ్యాత్మిక గురువు లభ్యత — ఇవన్నీ సహజము.\n\nనాలుగు, ఎనిమిది, పన్నెండు భావములు కలిసి మోక్ష త్రికోణము ఏర్పరచును. ఈ త్రికోణములో చివరి భావము పన్నెండవది. ఇచ్చట గురువు లేదా కేతువు ఉన్నచో మోక్ష సాధన యోగము సిద్ధించును. ఇట్టి జాతకులు సన్యాస సాధన, యోగ సాధన, తపస్సు — ఈ మార్గములలో దేనినైనా అనుసరించి అంతిమ విముక్తి పొందువారు.\n\nపన్నెండవ భావములో పాప గ్రహముల ప్రాబల్యము ఉండి లగ్నేశుడితో సంబంధము కల్గించినప్పుడు ఆయుష్షునకు ఆపదలు, ఆసుపత్రి నిర్బంధము, లేదా కష్ట సందర్భములలో జైలు సమస్యలు రావచ్చును. పరిహారార్థము విష్ణు సహస్రనామ పారాయణ, ముఖ్యముగా అన్న దానము, ఆశ్రమ సేవ, తీర్థయాత్రలు, యోగ ధ్యాన సాధన — ఇవన్నీ ప్రభావకరములు.",
          english: "The twelfth house — known as the vyaya-bhāva or mokṣa-bhāva — governs expenses, losses, foreign travel, sleep-comfort, mokṣa-sādhana, hidden enemies, ashram service, hospitalization, and confinement. Although classified as a dusthāna, it is the final and most significant house of the mokṣa-trikoṇa, making it the principal seat of spiritual progress.\n\nWhen the twelfth lord falls into the sixth or eighth — both dusthānas — Vimala Yoga forms, one of the viparīta rāja-yogas. Such natives have the natural ability to control unnecessary expenditure; saving comes easily to them. Foreign residence, foreign employment, or foreign business often becomes the path of advancement. They progress in spiritual practice as well. A noted feature is generosity in dharmic causes — money flows out willingly when the cause is right. Divine experiences during dreams are not unusual.\n\nWhich planet sits in the twelfth shapes these effects further. Sun there suggests distance from the father or losses connected with government dealings. Moon points to foreign residence and separation from the mother. Mars indicates wounds, enemies, or conflicts encountered abroad.\n\nMercury in the twelfth typically brings foreign business or foreign education. Jupiter here is highly auspicious — mokṣa-sādhana, ashram service, foreign spiritual studies, and pilgrimages all unfold naturally. Venus brings a foreign-tinged luxurious life, sleeping comforts, and sometimes secret romantic affairs. Saturn produces long stays abroad or a sannyāsa-like life, and in difficult configurations even imprisonment.\n\nRāhu in the twelfth strongly indicates immigration, foreign settlement, or NRI life. Ketu suggests mokṣa-sādhana, pilgrimages, and the appearance of a spiritual guru.\n\nThe fourth, eighth, and twelfth houses together form the mokṣa-trikoṇa, with the twelfth as its final and most spiritually significant house. Jupiter or Ketu placed here forms what is called the mokṣa-sādhana yoga — the yoga of liberation. Such natives, through sannyāsa, yoga, or sustained tapas, attain final freedom.\n\nMalefic dominance in the twelfth combined with a connection to the lagna lord can bring difficulties to longevity, hospitalization, or — in the most difficult configurations — even imprisonment. Remedies include Viṣṇu-sahasranāma recitation, the giving of food (especially anna-dāna), service at ashrams, pilgrimages, and dedicated yoga and meditation practice. [Source: Santhanam ed., p.470]",
          tags: ["vyaya-bhava", "12th-house", "expenses-foreign-moksha-sleep", "vimala-yoga"], verified: "auto" }
      ]
    },
    53: { title_te: "నష్ట-జాతకోద్ధారాధ్యాయః",             title_en: "Reconstruction of Lost Horoscope" },
    54: { title_te: "ద్రేక్కాణ-రూపాధ్యాయః",               title_en: "Drekkāṇa Iconography" },
    55: {
      title_te: "ఉపసంహారాధ్యాయః · Upasaṁhārādhyāya",
      title_en: "Concluding Chapter (Author's Colophon)",
      summary_te: "సారావలి గ్రంథ యొక్క ఉపసంహార అధ్యాయము. కల్యాణవర్మాచార్యులు ఈ అధ్యాయములో తన గ్రంథ పాఠకులకు ఆశీర్వాదములు, అధ్యయన సూచనలు ఇచ్చుచున్నారు. వరాహమిహిరుని బృహజ్జాతక గ్రంథము మరియు తన ఈ సారావలి గ్రంథముల మధ్య పరిమిత అపరిమిత చర్చల పోలిక కూడా చేయుచున్నారు. సారావలి గ్రంథ యొక్క ముఖ్య విశేషత ప్రతి యోగమునకు నిర్దిష్ట ఫలమును స్పష్టముగా చెప్పుట, ఇది బృహజ్జాతక గ్రంథములో సంక్షిప్తముగా ఉన్న వాటిని విస్తరించుట.",
      summary_en: "The concluding chapter of Sārāvalī. Author Kalyāṇavarman gives blessings to readers, study suggestions, and compares his work with Br̥hat Jātaka. Sārāvalī's distinctive merit: SPECIFIC results for EACH yoga, more elaborate than predecessors.",
      verses: [
        { sl: 1, page: 580, source_ed: "Santhanam (Ranjan Publications) ed., p.580",
          sanskrit: "ఇతి-సారావళీ-నామ-హోరా-గ్రంథః-కల్యాణ-వర్మణా-విరచితః / జ్యోతిష్య-వేదాంగ-రసముద్రః-సర్వ-జాతక-విదాం-ఆశీర్వాదం-భూయాత్‌ ॥ 1 ॥",
          telugu_bhava: "ఈ విధముగా సారావళి అను నామక హోరా గ్రంథమును కల్యాణవర్మాచార్యుడు రచించినారు. ఇది జ్యోతిష్య వేదాంగము యొక్క రస సముద్రము — అన్ని జాతక విద్వాంసులకు ఆశీర్వాదదాయకము.\n\nసారావళి యొక్క ముఖ్య విశేషతలు అనేకము ఉన్నవి. ప్రతి యోగమునకు ఎన్ని సంవత్సరములు, ఏ దశలో ఫలము, ఎంత తీవ్రత అని స్పష్టముగా చెప్పుట ఈ గ్రంథము యొక్క నిర్దిష్ట ఫల చర్చ యొక్క విశేషత. స్త్రీ జాతక చర్చ — నలుబది ఒకటి మరియు నలుబది రెండవ అధ్యాయములలో — విస్తృతముగా చేయబడినది. ద్రేక్కాణ చర్చ ముప్పై మూడు మరియు యాభై నాలుగవ అధ్యాయములలో సమగ్రముగా ఉన్నది. బృహజ్జాతకములో సంక్షిప్తముగా చెప్పబడిన అనేక విషయములను ఈ గ్రంథము విస్తరించి వివరించును.\n\nసారావళి బృహజ్జాతకము తరువాత రెండు మూడు శతాబ్దములలో రచింపబడినది. కావున బృహజ్జాతక మరియు భట్టోత్పల వ్యాఖ్యానము ఆధారముగా, మధ్య కాలములో అభివృద్ధి చెందిన అంశములతో ఇది రూపొందినది. మధ్య కాలము నుండి పంచరత్న గ్రంథములలో ద్వితీయ స్థానమును పొందినది. ఇతి సారావళి సంపూర్ణం. ఓం శాంతిః.",
          english: "Thus ends the hōrā treatise named Sārāvalī, composed by Kalyāṇavarman — an ocean of essence of jyotiṣa-vedāṅga. May it be a source of blessings for all jātaka-scholars. [Sārāvalī's distinctive features: (1) Specific results for each yoga; (2) Elaborate strī-jātaka (Ch.41-42); (3) Detailed drekkāṇa (Ch.33, Ch.54); (4) Expansion of Br̥hat Jātaka's brief mentions. Composed 2-3 centuries after Br̥hat Jātaka, drawing on Bhaṭṭotpala commentary. Sārāvalī = second jewel of the Pañcaratna. Iti Sārāvalī sampūrṇam. Source: Santhanam Ranjan Publications ed., p.580]",
          tags: ["upasamhara", "saravali-distinctive", "panchratna-2nd"], verified: "auto" }
      ]
    }
  };
  text.meta.extracted_chapters = [1, 7, 9, 13, 19, 21, 27, 41, 44, 45, 46, 47, 48, 49, 50, 51, 52, 55];
  text.meta.extraction_note_te = "ఆరు ముఖ్య అధ్యాయములు సేకరింపబడినవి అవి ఒకటి, తొమ్మిది, పంతొమ్మిది, ఇరువది ఒకటి, నలుబది ఒకటి, యాభై ఐదు. ఇవి సారావలి గ్రంథ యొక్క ముఖ్య విశేషతలను ప్రతిబింబించునవి. మొదటి అధ్యాయములో మంగళాచరణము మరియు కల్యాణవర్మ ఆచార్య పరిచయము ఉన్నవి. తొమ్మిదవ అధ్యాయములో సారావలి గ్రంథ యొక్క ప్రసిద్ధ విస్తృత నాభస ముప్పై రెండు యోగములు చర్చింపబడినవి. పంతొమ్మిదవ అధ్యాయములో రాజ యోగములు మరియు హర్ష సరళ విమల అను విపరీత రాజ యోగములు ఉన్నవి. ఇరువది ఒకటవ అధ్యాయములో రెండవ మరియు పదకొండవ భావాధిపతి సూత్రముతో ధన యోగము ఉన్నది. నలుబది ఒకటవ అధ్యాయములో స్త్రీ జాతక చర్చతో పతి గుణ నిర్ణయము నవాంశ అధిపతి ద్వారా చేయబడుట ఉన్నది. యాభై ఐదవ అధ్యాయములో ఉపసంహారము మరియు గ్రంథ సమాప్తి ఉన్నవి. మూల ప్రతి ఆర్‌. సంతానం రంజన్‌ పబ్లికేషన్స్‌ ముద్రణ. మిగిలిన నలుబది తొమ్మిది అధ్యాయములు క్రమముగా సేకరింపబడును.";
  text.meta.extraction_note_en = "Six key chapters have been extracted: chapters 1, 9, 19, 21, 41, and 55, covering the distinctive features of Sārāvalī. Chapter 1 contains the maṅgala-acharaṇa and Kalyāṇavarman's introduction. Chapter 9 presents Sārāvalī's celebrated elaborate treatment of the thirty-two Nābhasa yogas. Chapter 19 covers Rāja-yogas along with the Viparīta-rāja-yogas — Harṣa, Sarala, and Vimala. Chapter 21 sets out the Dhana-yoga formed by the second and eleventh lords. Chapter 41 deals with Strī-jātaka and determination of the husband's character via the navāṁśa lord. Chapter 55 contains the Upasaṁhāra and the author's colophon. Source edition: R. Santhanam (Ranjan Publications). The remaining forty-nine chapters are to be extracted progressively.";
})();
